.TH "C++ wrapper" 3 "Thu Apr 16 2020" "Version 0.31" "liblo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C++ wrapper \- 
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBlo::Method\fP"
.br
.RI "\fIClass representing an OSC method, proxy for \fBlo_method\fP\&. \fP"
.ti -1c
.RI "class \fBlo::Address\fP"
.br
.RI "\fIClass representing an OSC destination address, proxy for \fBlo_address\fP\&. \fP"
.ti -1c
.RI "class \fBlo::Message\fP"
.br
.RI "\fIClass representing an OSC message, proxy for \fBlo_message\fP\&. \fP"
.ti -1c
.RI "class \fBlo::Server\fP"
.br
.RI "\fIClass representing a local OSC server, proxy for \fBlo_server\fP\&. \fP"
.ti -1c
.RI "class \fBlo::ServerThread\fP"
.br
.RI "\fIClass representing a server thread, proxy for \fBlo_server_thread\fP\&. \fP"
.ti -1c
.RI "class \fBlo::Blob\fP"
.br
.RI "\fIClass representing an OSC blob, proxy for \fBlo_blob\fP\&. \fP"
.ti -1c
.RI "struct \fBlo::PathMsg\fP"
.br
.RI "\fIClass representing an OSC path (std::string) and \fBlo::Message\fP pair\&. \fP"
.ti -1c
.RI "class \fBlo::Bundle\fP"
.br
.RI "\fIClass representing an OSC bundle, proxy for \fBlo_bundle\fP\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This is a header-only C++11 wrapper defining a set of classes that wrap liblo functionality in an object-oriented way\&.
.PP
The classes are meant to be used instead of the C structs defined by liblo, and can be used to do nice C++11 things like assigning methods as lambda functions and other types of callbacks, supporting a variety of parameter combinations, as well as to create messages and bundles of messages using a nice initializer list syntax\&.
.PP
Please see \fBexamples/cpp_example\&.cpp\fP for more information on how to use it\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for liblo from the source code\&.
