.TH "lo::Bundle" 3 "Thu Apr 16 2020" "Version 0.31" "liblo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lo::Bundle \- 
.PP
Class representing an OSC bundle, proxy for \fBlo_bundle\fP\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Class representing an OSC bundle, proxy for \fBlo_bundle\fP\&. 
.PP
Definition at line 953 of file lo_cpp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for liblo from the source code\&.
