.TH "lo_cpp.h" 3 "Thu Apr 16 2020" "Version 0.31" "liblo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lo_cpp.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBlo::Method\fP"
.br
.RI "\fIClass representing an OSC method, proxy for \fBlo_method\fP\&. \fP"
.ti -1c
.RI "class \fBlo::Address\fP"
.br
.RI "\fIClass representing an OSC destination address, proxy for \fBlo_address\fP\&. \fP"
.ti -1c
.RI "class \fBlo::Message\fP"
.br
.RI "\fIClass representing an OSC message, proxy for \fBlo_message\fP\&. \fP"
.ti -1c
.RI "class \fBlo::Server\fP"
.br
.RI "\fIClass representing a local OSC server, proxy for \fBlo_server\fP\&. \fP"
.ti -1c
.RI "class \fBlo::ServerThread\fP"
.br
.RI "\fIClass representing a server thread, proxy for \fBlo_server_thread\fP\&. \fP"
.ti -1c
.RI "class \fBlo::Blob\fP"
.br
.RI "\fIClass representing an OSC blob, proxy for \fBlo_blob\fP\&. \fP"
.ti -1c
.RI "struct \fBlo::PathMsg\fP"
.br
.RI "\fIClass representing an OSC path (std::string) and \fBlo::Message\fP pair\&. \fP"
.ti -1c
.RI "class \fBlo::Bundle\fP"
.br
.RI "\fIClass representing an OSC bundle, proxy for \fBlo_bundle\fP\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBlo::version\fP ()"
.br
.RI "\fIReturn the library version as an std::string\&. \fP"
.ti -1c
.RI "\fBlo_timetag\fP \fBlo::now\fP ()"
.br
.RI "\fIReturn the current time in \fBlo_timetag\fP format\&. \fP"
.ti -1c
.RI "\fBlo_timetag\fP \fBlo::immediate\fP ()"
.br
.RI "\fIReturn the OSC timetag representing 'immediately'\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The liblo C++ wrapper 
.PP
Definition in file \fBlo_cpp\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for liblo from the source code\&.
