.TH "lo::Method" 3 "Thu Apr 16 2020" "Version 0.31" "liblo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lo::Method \- 
.PP
Class representing an OSC method, proxy for \fBlo_method\fP\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Class representing an OSC method, proxy for \fBlo_method\fP\&. 
.PP
Definition at line 136 of file lo_cpp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for liblo from the source code\&.
