#!/bin/csh
#
# Shell script to test sending OSC messages to CO
#
# Create a convenient alias
alias ssoo "sendOSC -h localhost 54321"
#
# Play a note on instrument 1
#
ssoo /i1/p
sleep 3
#
# Set a value and play another note
#
ssoo /i2/cf,50.0
ssoo /i2/p
sleep 3
#
ssoo /i1/du,5.0
ssoo /i1/p
sleep 5
#
# play a note with parameters: dur/amp/car/mod/ind
#
ssoo /i4/pn,4.0,0.3,220.0,357.4,3.0
sleep 4
#
ssoo /i2/pn,4.0,0.2,210.0,387.4,6.0
ssoo /i3/pn,5.0,0.2,270.0,307.4,3.0
sleep 3
#
# now quit
#
#ssoo /q
