CSL: /Content/Code/CSL/CSL/Sources/Granulator.cpp File Reference
Granulator.cpp File Reference
#include "Granulator.h"
Functions
void * createGrains (void *theArg)
void * reapGrains (void *theArg)
Function Documentation
void* createGrains (void * theArg)
Definition at line 123 of file Granulator.cpp.
References csl::Grain::amplitude, C_TIME, csl::Grain::delay, csl::Grain::duration, csl::Grain::env, csl::CGestalt::frameRate(), csl::fRandB(), csl::GrainCloud::gNow, csl::GrainCloud::gState, csl::GrainCloud::isPlaying, csl::kFree, csl::kSched, csl::logMsg(), csl::GrainCloud::mDensityBase, csl::GrainCloud::mDensityRange, csl::GrainCloud::mDurationBase, csl::GrainCloud::mDurationRange, csl::GrainCloud::mEnvelopeBase, csl::GrainCloud::mEnvelopeRange, csl::GrainCloud::mOffsetBase, csl::GrainCloud::mOffsetRange, csl::GrainCloud::mPlayingGrains, csl::GrainCloud::mRateBase, csl::GrainCloud::mRateRange, csl::GrainCloud::mSamples, csl::GrainCloud::mSilentGrains, csl::GrainCloud::mVolumeBase, csl::GrainCloud::mVolumeRange, csl::GrainCloud::mWidthBase, csl::GrainCloud::mWidthRange, csl::Grain::nextGrain, csl::Grain::numSamples, csl::GrainCloud::numSamples, csl::Grain::pan, csl::Grain::position, csl::Grain::rate, csl::Grain::samples, csl::GrainCloud::sampsPerTick, csl::sleepMsec(), csl::sleepUsec(), and csl::Grain::time.
Referenced by csl::GrainCloud::startThreads().
void* reapGrains (void * theArg)
Definition at line 174 of file Granulator.cpp.
References csl::Grain::duration, csl::GrainCloud::gState, csl::GrainCloud::isPlaying, csl::kFree, csl::kSched, csl::logMsg(), csl::GrainCloud::mPlayingGrains, csl::GrainCloud::mSilentGrains, csl::Grain::nextGrain, csl::sleepMsec(), and csl::Grain::time.
Referenced by csl::GrainCloud::startThreads().