CSL: /Content/Code/CSL/CSL/IO/JackIO.cpp File Reference
JackIO.cpp File Reference
#include "JackIO.h"
Functions
int JackCallback (jack_nframes_t nframes, void *arg)
void jack_shutdown (void *arg)
Function Documentation
int JackCallback (jack_nframes_t nframes, void * arg)
Definition at line 12 of file JackIO.cpp.
References csl::kIOExit, csl::kIORunning, csl::JackIO::mClient, csl::JackIO::mInput_port, csl::Buffer::mNumChannels, csl::Buffer::mNumFrames, csl::JackIO::mOutput_port, csl::IO::mOutputBuffer, csl::IO::mStatus, and csl::IO::pullInput().
Referenced by csl::JackIO::open().
void jack_shutdown (void * arg)
Definition at line 35 of file JackIO.cpp.
References csl::logMsg().
Referenced by csl::JackIO::open().