CSL: /Content/Code/CSL/CSL/IO/PAIO.cpp File Reference
PAIO.cpp File Reference
#include "PAIO.h"
#include <iostream>
Functions
static int pa_callback (const void *inputPointer, void *outputPointer, unsigned long framesPerBuffer, const PaStreamCallbackTimeInfo *outTime, PaStreamCallbackFlags statusFlags, void *userData)
Function Documentation
static int pa_callback (const void * inputPointer, void * outputPointer, unsigned long framesPerBuffer, const PaStreamCallbackTimeInfo * outTime, PaStreamCallbackFlags statusFlags, void * userData) static
Definition at line 41 of file PAIO.cpp.
References csl::kIORunning, csl::logMsg(), csl::IO::mGraph, csl::IO::mInputBuffer, csl::IO::mInputPointer, csl::Buffer::mNumFrames, csl::IO::mNumFramesPlayed, csl::IO::mNumInChannels, csl::IO::mOutputBuffer, csl::IO::mStatus, and csl::IO::pullInput().
Referenced by csl::PAIO::open().