CSL: /Content/Code/CSL/CSL/Spatializers/VBAP/PracticalSocket.cpp File Reference
PracticalSocket.cpp File Reference
#include "PracticalSocket.h"
#include <sys/types.h>
#include <sys/socket.h>
#include <string.h>
#include <stdlib.h>
#include <netdb.h>
#include <arpa/inet.h>
#include <unistd.h>
#include <netinet/in.h>
#include <errno.h>
Typedefs
typedef void raw_type
Functions
static void fillAddr (const string &address, unsigned short port, sockaddr_in &addr)
Typedef Documentation
typedef void raw_type
Definition at line 35 of file PracticalSocket.cpp.
Function Documentation
static void fillAddr (const string & address, unsigned short port, sockaddr_in & addr) static
Definition at line 64 of file PracticalSocket.cpp.
Referenced by CommunicatingSocket::connect(), UDPSocket::sendTo(), and Socket::setLocalAddressAndPort().