CSL: /Content/Code/CSL/CSL/Tests/Test_Panners.cpp File Reference
Test_Panners.cpp File Reference
#include "Test_Support.cpp"
#include "Convolver.h"
#include "Convolver2.h"
#include <unistd.h>
#include "InOut.h"
#include "SpatialAudio.h"
#include "Binaural.h"
Macros
#define USE_TEST_MAIN
#define USE_CONVOLVER
#define IR_FILE "/Content/Code/CSL/CSL_Data/7.0s_Cathedral C.aiff"
NEW (1905) Convolver.
#define USE_SND_FILES
Functions
void testPan ()
Pan a sine to stereo.
void testN2MPan ()
Pan a sine to "N" channels.
void testSineMixer ()
Test mixer – really slow additive synthesis.
void testPanMix ()
Pan and mix 2 sines.
void testBigPanMix ()
Pan and mix many sines.
void testOscBank ()
Make a bank or 50 sines with random walk panners and glissandi.
void testCMapIO ()
swap sound channels with a ChannelMappedBuffer InOut Constructor: InOut(input, inChan, outChan, [ch-1 ... ch-outChan]);
void test_Binaural_horiz ()
Spatializer with HRTF.
void test_Binaural_vertAxial ()
Repeat a short test file moving in circles around the vertical plane at AZ = CSL_PIHALF (axial plane in line with your ears, easy to localize)
void test_Binaural_vertMedian ()
Repeat a short test file moving in circles around the vertical plane at AZ = 0 (median plane between your ears, hard to localize)
void test_Ambi_horiz ()
Spatializer with Ambisonics.
void test_SimpleP ()
Spatializer with simple panners & filters and/or reverb.
void test_VBAP_horiz ()
Spatializer with VBAP.
void test_convolution ()
float * load_filter_data (char *fname, unsigned &siz)
void test_convolution_file (float *data, unsigned len)
void test_convolution_files ()
void runTests ()
Variables
float test_IR [400]
Macro Definition Documentation
#define USE_TEST_MAIN
Definition at line 12 of file Test_Panners.cpp.
#define USE_CONVOLVER
Definition at line 16 of file Test_Panners.cpp.
#define IR_FILE "/Content/Code/CSL/CSL_Data/7.0s_Cathedral C.aiff"
NEW (1905) Convolver.
Definition at line 417 of file Test_Panners.cpp.
Referenced by test_convolution().
#define USE_SND_FILES
Definition at line 467 of file Test_Panners.cpp.
Function Documentation
void testPan ()
Pan a sine to stereo.
Definition at line 29 of file Test_Panners.cpp.
References CSL_PI, csl::logMsg(), Osc, and runTest().
void testN2MPan ()
Pan a sine to "N" channels.
Definition at line 41 of file Test_Panners.cpp.
References CSL_PI, csl::logMsg(), Osc, and runTest().
void testSineMixer ()
Test mixer – really slow additive synthesis.
Definition at line 55 of file Test_Panners.cpp.
References csl::Mixer::addInput(), csl::logMsg(), Osc, and runTest().
void testPanMix ()
Pan and mix 2 sines.
Definition at line 74 of file Test_Panners.cpp.
References csl::Mixer::addInput(), CSL_PI, csl::logMsg(), Osc, and runTest().
void testBigPanMix ()
Pan and mix many sines.
Definition at line 98 of file Test_Panners.cpp.
References csl::Mixer::addInput(), CSL_PI, csl::Mixer::deleteInputs(), csl::fRandM(), csl::logMsg(), Osc, and runTest().
void testOscBank ()
Make a bank or 50 sines with random walk panners and glissandi.
Definition at line 122 of file Test_Panners.cpp.
References csl::Mixer::addInput(), csl::Mixer::deleteInputs(), csl::logMsg(), Osc, and runTest().
void testCMapIO ()
swap sound channels with a ChannelMappedBuffer InOut Constructor: InOut(input, inChan, outChan, [ch-1 ... ch-outChan]);
Copy in-out plug
Definition at line 147 of file Test_Panners.cpp.
References kNoProc, csl::logMsg(), Osc, and runTest().
void test_Binaural_horiz ()
Spatializer with HRTF.
Repeat a short test file moving in circles around the horizontal plane
Definition at line 246 of file Test_Panners.cpp.
References csl::Spatializer::addSource(), CSL_NAME_LEN, csl::SpatialSource::dump(), csl::kBinaural, csl::logMsg(), csl::SpatialSource::setPosition(), csl::sleepSec(), and theIO.
Referenced by runTests().
void test_Binaural_vertAxial ()
Repeat a short test file moving in circles around the vertical plane at AZ = CSL_PIHALF (axial plane in line with your ears, easy to localize)
Definition at line 280 of file Test_Panners.cpp.
References csl::Spatializer::addSource(), CSL_PIHALF, csl::SpatialSource::dump(), csl::kBinaural, csl::logMsg(), csl::SpatialSource::setPosition(), csl::sleepSec(), and theIO.
void test_Binaural_vertMedian ()
Repeat a short test file moving in circles around the vertical plane at AZ = 0 (median plane between your ears, hard to localize)
Definition at line 306 of file Test_Panners.cpp.
References csl::Spatializer::addSource(), csl::SpatialSource::dump(), csl::kBinaural, csl::logMsg(), csl::SpatialSource::setPosition(), csl::sleepSec(), and theIO.
void test_Ambi_horiz ()
Spatializer with Ambisonics.
Definition at line 333 of file Test_Panners.cpp.
References csl::Spatializer::addSource(), csl::SpatialSource::dump(), csl::kAmbisonic, csl::logMsg(), csl::SpatialSource::setPosition(), csl::sleepSec(), and theIO.
void test_SimpleP ()
Spatializer with simple panners & filters and/or reverb.
Definition at line 358 of file Test_Panners.cpp.
References csl::Mixer::addInput(), csl::Spatializer::addSource(), csl::SpatialSource::dump(), csl::kSimple, csl::logMsg(), csl::SpatialSource::setPosition(), csl::sleepSec(), and theIO.
void test_VBAP_horiz ()
Spatializer with VBAP.
Definition at line 386 of file Test_Panners.cpp.
References csl::Spatializer::addSource(), csl::SpatialSource::dump(), csl::kVBAP, csl::logMsg(), csl::SpatialSource::setPosition(), csl::sleepSec(), and theIO.
void test_convolution ()
Definition at line 469 of file Test_Panners.cpp.
References IR_FILE, csl::logMsg(), csl::sleepSec(), theIO, and csl::Abst_SoundFile::trigger().
float* load_filter_data (char * fname, unsigned & siz)
Definition at line 499 of file Test_Panners.cpp.
References csl::Abst_SoundFile::buffer(), CSL_WORD_LEN, csl::JSoundFile::duration(), csl::kLogError, csl::kLogFatal, len, csl::logMsg(), csl::Buffer::mDidIAllocateBuffers, csl::WavetableOscillator::mWavetable, and SAFE_MALLOC.
Referenced by test_convolution_files().
void test_convolution_file (float * data, unsigned len)
Definition at line 553 of file Test_Panners.cpp.
References csl::logMsg(), csl::Buffer::rms(), csl::sleepSec(), and theIO.
Referenced by test_convolution_files().
void test_convolution_files ()
Definition at line 573 of file Test_Panners.cpp.
References len, load_filter_data(), and test_convolution_file().
void runTests ()
Definition at line 603 of file Test_Panners.cpp.
References test_Binaural_horiz().
Variable Documentation
float test_IR[400]
Definition at line 421 of file Test_Panners.cpp.