CSL: /Content/Code/CSL/CSL/Tests/Test_Support.cpp File Reference
Test_Support.cpp File Reference
#include "Test_Support.h"
#include <stdlib.h>
Macros
#define READ_CSL_OPTS
Functions
void runTest (UnitGenerator &vox, double dur)
void runTest (UnitGenerator &vox)
void dumpTest (UnitGenerator &vox)
int find_option (int argc, const char **argv, char flag, unsigned *datum)
void usage (const char *name)
Variables
IO_CLASS * theIO = 0
Macro Definition Documentation
#define READ_CSL_OPTS
Definition at line 114 of file Test_Support.cpp.
Function Documentation
void runTest (UnitGenerator & vox, double dur)
Definition at line 54 of file Test_Support.cpp.
References csl::sleepSec(), and theIO.
Referenced by dumpAMFMSin(), echo_test(), filt_test(), mic_test(), panner_test(), runTest(), test50RandFreqEnv(), test_ifft(), test_SHARC(), test_SHARC2(), test_vector_ifft(), testADSR2(), testADSR_FM(), testAMFMEnvs(), testAMFMSin(), testARSin(), testARSin2(), testBasicWaves(), testBigPanMix(), testBiquads(), testBlockDownsizer(), testBlockUpsizer(), testClipper(), testCMapIO(), testComplexEnvelope(), testDynamicFilters(), testDynamicMixer(), testDynamicVoice(), testEnvScale(), testFancy_FM(), testFancyFMInstrument(), testFanMix1(), testFanMix2(), testFilters(), testFIR(), testFMInstrument(), testFrequencyEnv(), testGliss(), testGrainCloud(), testManyRandSOS(), testMonoFilePlayer(), testN2MPan(), testNDynamicFilters(), testNoises(), testOscBank(), testPan(), testPanMix(), testRandFreqEnv(), testSAFilter(), testScaledSin(), testSimpleSines(), testSineMixer(), testSndFileInstrument(), testSOSInstrument(), testSplitJoin1(), testSplitJoin2(), testStereoFilePlayer(), testString(), testSumOfSines1F(), testSumOfSinesCached(), testSumOfSinesNonCached(), testSumOfSinesSteps(), testSweep(), testSwell(), testWaveShaper(), testWaveTableFromFile(), and testWavetableInterpolation().
void runTest (UnitGenerator & vox)
Definition at line 64 of file Test_Support.cpp.
References runTest().
void dumpTest (UnitGenerator & vox)
Definition at line 70 of file Test_Support.cpp.
References csl::UnitGenerator::dump(), and theIO.
Referenced by dumpAMFMSin().
int find_option (int argc, const char ** argv, char flag, unsigned * datum)
Definition at line 93 of file Test_Support.cpp.
void usage (const char * name)
Definition at line 152 of file Test_Support.cpp.
Variable Documentation
IO_CLASS* theIO = 0
Definition at line 29 of file Test_Support.cpp.
Referenced by dumpTest(), echo_test(), filt_test(), mic_test(), panner_test(), runTest(), test_Ambi_horiz(), test_Binaural_horiz(), test_Binaural_vertAxial(), test_Binaural_vertMedian(), test_convolution(), test_convolution_file(), test_SimpleP(), test_VBAP_horiz(), testMultiTap(), testReverb(), testSndFileBank(), testSoundFileTranspose(), testStereoverb(), and testStringChorus().