CSL: /Content/Code/CSL/CSL/Tests/OSC/Test_OSC_Client.cpp File Reference
Test_OSC_Client.cpp File Reference
#include "CSL_Core.h"
#include "lo/lo.h"
Macros
#define NUM_NOTES 100
Functions
void noteLoop (lo_address &ad)
int main (int argc, char **Argv)
Macro Definition Documentation
#define NUM_NOTES 100
Definition at line 16 of file Test_OSC_Client.cpp.
Referenced by noteLoop().
Function Documentation
void noteLoop (lo_address & ad)
Definition at line 44 of file Test_OSC_Client.cpp.
References CSL_WORD_LEN, csl::fRand1(), csl::fRandM(), csl::iRandM(), csl::iRandV(), csl::keyToFreq(), csl::kLogError, csl::logMsg(), NUM_NOTES, and csl::sleepSec().
Referenced by main().
int main (int argc, char ** Argv)
Definition at line 24 of file Test_OSC_Client.cpp.
References CSL_WORD_LEN, csl::kLogError, csl::logMsg(), noteLoop(), csl::CGestalt::outPort(), and csl::sleepSec().