CSL: /Content/Code/CSL/CSL/Tests/Test_Audio.cpp File Reference
Test_Audio.cpp File Reference
#include "Test_Support.cpp"
Macros
#define USE_TEST_MAIN
Functions
void audio_dump ()
void mic_test ()
void filt_test ()
void echo_test ()
void panner_test ()
void listener_test ()
Variables
juce::AudioDeviceManager * gAudioDeviceManager
testStruct audioTestList []
Macro Definition Documentation
#define USE_TEST_MAIN
Definition at line 11 of file Test_Audio.cpp.
Function Documentation
void audio_dump ()
Definition at line 21 of file Test_Audio.cpp.
References gAudioDeviceManager, and csl::logMsg().
void mic_test ()
Definition at line 37 of file Test_Audio.cpp.
References csl::logMsg(), runTest(), and theIO.
void filt_test ()
Definition at line 48 of file Test_Audio.cpp.
References BW_BAND_PASS, csl::logMsg(), runTest(), and theIO.
void echo_test ()
Definition at line 58 of file Test_Audio.cpp.
References csl::logMsg(), runTest(), csl::Stereoverb::setRoomSize(), and theIO.
void panner_test ()
Definition at line 69 of file Test_Audio.cpp.
References CSL_PI, csl::logMsg(), Osc, runTest(), and theIO.
void listener_test ()
Definition at line 96 of file Test_Audio.cpp.
Variable Documentation
juce::AudioDeviceManager* gAudioDeviceManager
Referenced by audio_dump().
testStruct audioTestList[]
Initial value:
= {
    "Dump audio ports",     audio_dump,     "Dump list of audio ports to stdout",
    "Echo audio in",            mic_test,       "Play the microphone input back the output",
    "Filter input",         filt_test,      "Apply a band-pass filter to the live input",
    "Echo input",           echo_test,      "Add echo to the live input",
    "Input panner",         panner_test,    "Stereo panner on the live input",
    "Input listener",           listener_test,  "Demonstrate recording input listener",
    NULL,                   NULL,           NULL
}
Definition at line 115 of file Test_Audio.cpp.