CSL: /Content/Code/CSL/CSL/Utilities/fft_N.h File Reference
fft_N.h File Reference
#include <stdbool.h>
#include <stddef.h>
Macros
#define CFTTYPE float
Functions
void Fft_setup (size_t n)
bool Fft_transform (CFTTYPE real[], CFTTYPE imag[], size_t n)
bool Fft_inverseTransform (CFTTYPE real[], CFTTYPE imag[], size_t n)
bool Fft_transformRadix2 (CFTTYPE real[], CFTTYPE imag[], size_t n)
bool Fft_transformBluestein (CFTTYPE real[], CFTTYPE imag[], size_t n)
bool Fft_convolveReal (const CFTTYPE x[], const CFTTYPE y[], CFTTYPE out[], size_t n)
bool Fft_convolveComplex (const CFTTYPE xreal[], const CFTTYPE ximag[], const CFTTYPE yreal[], const CFTTYPE yimag[], CFTTYPE outreal[], CFTTYPE outimag[], size_t n)
Macro Definition Documentation
#define CFTTYPE float
Definition at line 34 of file fft_N.h.
Function Documentation
void Fft_setup (size_t n)
Definition at line 42 of file fft_N.c.
References CFTTYPE, cos_table, len, sin_table, and size.
bool Fft_transform (CFTTYPE real[], CFTTYPE imag[], size_t n)
Definition at line 72 of file fft_N.c.
References Fft_transformRadix2(), and len.
Referenced by Fft_inverseTransform().
bool Fft_inverseTransform (CFTTYPE real[], CFTTYPE imag[], size_t n)
Definition at line 87 of file fft_N.c.
References Fft_transform().
bool Fft_transformRadix2 (CFTTYPE real[], CFTTYPE imag[], size_t n)
Definition at line 91 of file fft_N.c.
References CFTTYPE, cos_table, reverse_bits(), sin_table, and size.
Referenced by Fft_transform().
bool Fft_transformBluestein (CFTTYPE real[], CFTTYPE imag[], size_t n)
bool Fft_convolveReal (const CFTTYPE x[], const CFTTYPE y[], CFTTYPE out[], size_t n)
bool Fft_convolveComplex (const CFTTYPE xreal[], const CFTTYPE ximag[], const CFTTYPE yreal[], const CFTTYPE yimag[], CFTTYPE outreal[], CFTTYPE outimag[], size_t n)