CSL: /Content/Code/CSL/CSL/Spatializers/VBAP/VBAP.cpp File Reference
VBAP.cpp File Reference
#include "VBAP.h"
Classes
struct Connection
Macros
#define MAX_NUM_VBAP_TRIPLETS 512
VBAP.h – Vector Base Amplitude Panning class (v2 - Nov 2006) See the copyright notice and acknowledgment of authors in the file COPYRIGHT Doug McCoy, 2004.
#define MIN_VOLUME_TO_LENGTH_RATIO 0.01
Functions
double vecAngle (CPoint v1, CPoint v2)
CPoint vectorMultiply (CPoint &v, CSLMatrix &m)
Macro Definition Documentation
#define MAX_NUM_VBAP_TRIPLETS 512
VBAP.h – Vector Base Amplitude Panning class (v2 - Nov 2006) See the copyright notice and acknowledgment of authors in the file COPYRIGHT Doug McCoy, 2004.
Definition at line 9 of file VBAP.cpp.
Referenced by csl::SpeakerSetLayout::addTriple(), and csl::SpeakerSetLayout::SpeakerSetLayout().
#define MIN_VOLUME_TO_LENGTH_RATIO 0.01
Definition at line 10 of file VBAP.cpp.
Referenced by csl::SpeakerSetLayout::findSpeakerTriplets().
Function Documentation
double vecAngle (CPoint v1, CPoint v2)
Definition at line 20 of file VBAP.cpp.
References csl::CPoint::len().
Referenced by csl::SpeakerSetLayout::evaluateCrossing(), and csl::SpeakerSetLayout::findSpeakerTriplets().
CPoint vectorMultiply (CPoint & v, CSLMatrix & m)
Definition at line 29 of file VBAP.cpp.
References math::matrix::RowNo().
Referenced by csl::SpeakerSetLayout::findSpeakerTriplets(), and csl::VBAP::nextBuffer().