CSL: /Content/Code/CSL/CSL/Spatializers/VBAP/VBAP_test.cpp File Reference
VBAP_test.cpp File Reference
#include "VBAP.h"
#include "string.h"
#include "SpeakerLayout.h"
#include <time.h>
#include "CSL_Includes.h"
#include "PAIO.h"
Functions
int main (int argc, const char *argv[])
Function Documentation
int main (int argc, const char * argv[])
Definition at line 17 of file VBAP_test.cpp.
References csl::SpatialPanner::addSource(), csl::PAIO::close(), gIO, csl::kAuto, csl::logMsg(), csl::PAIO::open(), csl::SpatialSource::setPosition(), csl::IO::setRoot(), csl::Scalable::setScale(), csl::sleepMsec(), csl::PAIO::start(), csl::PAIO::stop(), and csl::Envelope::trigger().