CSL: csl::AmbisonicEncoder Class Reference
csl::AmbisonicEncoder Class Reference
#include <Ambisonic.h>
Public Member Functions
AmbisonicEncoder ()
Default constructor.
AmbisonicEncoder (SpatialSource &input, unsigned order=1)
Initialize with uniform Ambisonic order.
AmbisonicEncoder (SpatialSource &input, unsigned horder, unsigned vorder)
Initialize with hybrid Ambisonic order.
virtual ~AmbisonicEncoder ()
Destructor.
void setInput (SpatialSource &input)
Set my input.
SpatialSource * input ()
virtual void nextBuffer (Buffer &outputBuffer, unsigned outBufNum) throw (CException)
Does the DSP processing for the Ambisonic Encoder.
AmbisonicOrder order ()
unsigned frameRate ()
void setFrameRate (unsigned rate)
get/set the receiver's frame rate
virtual unsigned numChannels ()
void setNumChannels (unsigned ch)
get/set the receiver's number of outputs
BufferCopyPolicy copyPolicy ()
void setCopyPolicy (BufferCopyPolicy ch)
get/set the receiver's buffer copy policy
virtual void nextBuffer (Buffer &outputBuffer) throw (CException)
get a buffer of Frames – this is the core CSL "pull" function; the given buffer can be written into, and a changed() message is sent.
virtual bool isFixed ()
query whether I'm fixed (StaticVariable overrides this)
virtual bool isActive ()
query whether I'm currently active (Envelopes can go inactive)
void addOutput (UnitGenerator *ugen)
add to or return the UGen vector of outputs
void removeOutput (UnitGenerator *ugen)
UGenVector outputs ()
virtual unsigned numOutputs ()
bool checkFanOut (Buffer &outputBuffer) throw (CException)
check for fan-out and copy previous buffer; return true if fanning out
void handleFanOut (Buffer &outputBuffer) throw (CException)
virtual void setValue (sample theValue)
set/get the value (not allowed in the abstract, useful for static values)
virtual sample value ()
virtual void dump ()
pretty-print the receiver
virtual void trigger ()
void attachObserver (Observer *)
(possibly notify obersvers on my death)
void detachObserver (Observer *)
void changed (void *argument)
this is what I send to myself to notify my observers; It's not overridden in general. It results in the observers receiving update() calls < override evaluate to filter updates to the observer map
virtual int evaluate (void *argument)
Protected Member Functions
void initialize ()
Initializing method called by constructors.
void setOrder (AmbisonicOrder order)
Returns the Ambisonic order.
unsigned channelsToUniformOrder (const unsigned channels)
unsigned greaterOrder (const AmbisonicOrder order)
Compares the horizontal and vertical Ambisonic order of a hybrid order and returns the largest.
unsigned orderToChannels (const AmbisonicOrder order)
Returns the number of Ambisonic channels from a hybrid Ambisonic order: N = 2*M_h + 1 + (M_v + 1)^2 - (2*M_v + 1)
unsigned orderToChannels (unsigned order)
Returns the number of Ambisonic channels corresponding to a uniform Ambisonic order: N = (M+1)^2.
unsigned orderToHorizontalChannels (const AmbisonicOrder order)
Returns the number of horizontal Ambisonic channels from a hybrid Ambisonic order: N_h = 2*M_h + 1.
unsigned orderToVerticalChannels (const AmbisonicOrder order)
Returns the number of vertical Ambisonic channels from a hybrid Ambisonic order: N_v = (M_v + 1)^2 - (2*M_v + 1)
void channelIndexer (unsigned *indexArray)
Calculates a lookup table to map Ambisonic channel index to actually used UnitGenerator channel.
void invChannelIndexer (unsigned *indexArray)
Calculates a lookup table to map actually used UnitGenerator channel to Ambisonic channel index.
void zeroBuffer (Buffer &outputBuffer, unsigned outBufNum)
utility method to zero out an outputBuffer
Protected Attributes
SampleBuffer mWeights
Encoding weights for each order (per source)
Port * mInputPort
Holds the input to be encoded.
AmbisonicOrder mOrder
the order of the Unit Generator
unsigned mFrameRate
trigger ignored here
unsigned mNumChannels
my "expected" number of output channels
BufferCopyPolicy mCopyPolicy
the policy I use if asked for more or fewer channels
UGenVector mOutputs
the vector of my output UGens
unsigned mNumOutputs
the number of outputs
Buffer * mOutputCache
my past output ring buffer (only used in case of fan-out)
unsigned mSequence
the highest-seen buffer seq number
Related Functions
(Note that these are not member functions.)
void singularValueDecomposition (sample **a, int m, int n, sample *w, sample **v)
void fumaEncodingWeights (SampleBuffer weights, const AmbisonicOrder &order, float azimuth, float elevation)
void fumaIndexedEncodingWeights (SampleBuffer weights, const AmbisonicOrder &order, sample &azimuth, sample &elevation)
Detailed Description
Definition at line 123 of file Ambisonic.h.
Constructor & Destructor Documentation
AmbisonicEncoder::AmbisonicEncoder ()
Default constructor.
Definition at line 191 of file Ambisonic.cpp.
AmbisonicEncoder::AmbisonicEncoder (SpatialSource & input, unsigned order = 1)
Initialize with uniform Ambisonic order.
Definition at line 193 of file Ambisonic.cpp.
References initialize(), and setInput().
AmbisonicEncoder::AmbisonicEncoder (SpatialSource & input, unsigned horder, unsigned vorder)
Initialize with hybrid Ambisonic order.
Definition at line 198 of file Ambisonic.cpp.
References initialize(), and setInput().
AmbisonicEncoder::~AmbisonicEncoder () virtual
Destructor.
Definition at line 203 of file Ambisonic.cpp.
References mInputPort, and mWeights.
Member Function Documentation
void AmbisonicEncoder::setInput (SpatialSource & input)
Set my input.
Use to set the input to be encoded.
Definition at line 226 of file Ambisonic.cpp.
References csl::UnitGenerator::addOutput(), input(), csl::logMsg(), mInputPort, csl::Port::mUGen, and csl::UnitGenerator::removeOutput().
Referenced by AmbisonicEncoder().
SpatialSource* csl::AmbisonicEncoder::input () inline
Definition at line 133 of file Ambisonic.h.
References mInputPort, and csl::Port::mUGen.
Referenced by setInput().
void AmbisonicEncoder::nextBuffer (Buffer & outputBuffer, unsigned outBufNum) throw (CException) virtual
Does the DSP processing for the Ambisonic Encoder.
Reimplemented from csl::UnitGenerator.
Definition at line 245 of file Ambisonic.cpp.
References csl::SpatialSource::azimuth(), csl::Buffer::buffer(), csl::SpatialSource::elevation(), csl::fumaEncodingWeights(), csl::kLogError, csl::kSamples, csl::logMsg(), csl::Buffer::mIsPopulated, csl::Buffer::mNumFrames, csl::Buffer::mType, and csl::Buffer::zeroBuffers().
void AmbisonicEncoder::initialize () protected
Initializing method called by constructors.
Definition at line 214 of file Ambisonic.cpp.
References AMBI_INVSQRT2, csl::UnitGenerator::mNumChannels, and mWeights.
Referenced by AmbisonicEncoder().
AmbisonicOrder csl::AmbisonicUnitGenerator::order () inline inherited
Definition at line 78 of file Ambisonic.h.
References csl::AmbisonicUnitGenerator::mOrder.
Referenced by csl::AmbisonicMixer::addInput(), and csl::AmbisonicDecoder::makeTransposedReEncodingMatrix().
void AmbisonicUnitGenerator::setOrder (AmbisonicOrder order) protected inherited
Returns the Ambisonic order.
Definition at line 59 of file Ambisonic.cpp.
References csl::AmbisonicUnitGenerator::initOrder(), and csl::AmbisonicUnitGenerator::mOrder.
unsigned AmbisonicUnitGenerator::channelsToUniformOrder (const unsigned channels) protected inherited
Definition at line 66 of file Ambisonic.cpp.
Referenced by csl::AmbisonicDecoder::makeInPhase(), and csl::AmbisonicDecoder::makeMaxRE().
unsigned AmbisonicUnitGenerator::greaterOrder (const AmbisonicOrder order) protected inherited
Compares the horizontal and vertical Ambisonic order of a hybrid order and returns the largest.
Definition at line 71 of file Ambisonic.cpp.
References csl::AmbisonicOrder::horizontalOrder, and csl::AmbisonicOrder::verticalOrder.
Referenced by csl::AmbisonicUnitGenerator::channelIndexer(), csl::AmbisonicRotator::initialize(), csl::AmbisonicDecoder::initialize(), and csl::AmbisonicDecoder::makeMaxRE().
unsigned AmbisonicUnitGenerator::orderToChannels (const AmbisonicOrder order) protected inherited
Returns the number of Ambisonic channels from a hybrid Ambisonic order: N = 2*M_h + 1 + (M_v + 1)^2 - (2*M_v + 1)
Definition at line 75 of file Ambisonic.cpp.
References csl::AmbisonicOrder::horizontalOrder, and csl::AmbisonicOrder::verticalOrder.
Referenced by csl::AmbisonicUnitGenerator::channelIndexer(), csl::AmbisonicRotator::initialize(), csl::AmbisonicDecoder::initialize(), csl::AmbisonicUnitGenerator::initOrder(), and csl::AmbisonicUnitGenerator::invChannelIndexer().
unsigned AmbisonicUnitGenerator::orderToChannels (unsigned order) protected inherited
Returns the number of Ambisonic channels corresponding to a uniform Ambisonic order: N = (M+1)^2.
Definition at line 80 of file Ambisonic.cpp.
unsigned AmbisonicUnitGenerator::orderToHorizontalChannels (const AmbisonicOrder order) protected inherited
Returns the number of horizontal Ambisonic channels from a hybrid Ambisonic order: N_h = 2*M_h + 1.
Definition at line 85 of file Ambisonic.cpp.
References csl::AmbisonicOrder::horizontalOrder.
unsigned AmbisonicUnitGenerator::orderToVerticalChannels (const AmbisonicOrder order) protected inherited
Returns the number of vertical Ambisonic channels from a hybrid Ambisonic order: N_v = (M_v + 1)^2 - (2*M_v + 1)
Definition at line 90 of file Ambisonic.cpp.
References csl::AmbisonicOrder::verticalOrder.
void AmbisonicUnitGenerator::channelIndexer (unsigned * indexArray) protected inherited
Calculates a lookup table to map Ambisonic channel index to actually used UnitGenerator channel.
Definition at line 98 of file Ambisonic.cpp.
References csl::AmbisonicUnitGenerator::greaterOrder(), csl::AmbisonicOrder::horizontalOrder, csl::AmbisonicUnitGenerator::mOrder, csl::AmbisonicUnitGenerator::orderToChannels(), and csl::AmbisonicOrder::verticalOrder.
Referenced by csl::AmbisonicRotator::initialize(), and csl::AmbisonicDecoder::initialize().
void AmbisonicUnitGenerator::invChannelIndexer (unsigned * indexArray) protected inherited
Calculates a lookup table to map actually used UnitGenerator channel to Ambisonic channel index.
Definition at line 146 of file Ambisonic.cpp.
References csl::AmbisonicOrder::horizontalOrder, csl::AmbisonicUnitGenerator::mOrder, csl::AmbisonicUnitGenerator::orderToChannels(), and csl::AmbisonicOrder::verticalOrder.
Referenced by csl::AmbisonicDecoder::initialize().
unsigned csl::UnitGenerator::frameRate () inline inherited
Definition at line 249 of file CSL_Core.h.
References csl::UnitGenerator::mFrameRate.
Referenced by csl::CASoundFile::dump(), csl::Abst_SoundFile::dump(), and csl::SoundCue::dump().
void csl::UnitGenerator::setFrameRate (unsigned rate) inline inherited
get/set the receiver's frame rate
Definition at line 250 of file CSL_Core.h.
References csl::UnitGenerator::mFrameRate.
virtual unsigned csl::UnitGenerator::numChannels () inline virtual inherited
Reimplemented in csl::Splitter, and csl::Stereoverb.
Definition at line 252 of file CSL_Core.h.
References csl::UnitGenerator::mNumChannels.
Referenced by csl::AmbisonicMixer::addInput(), csl::BlockResizer::BlockResizer(), csl::Port::checkBuffer(), csl::Effect::Effect(), csl::AmbisonicRotator::initialize(), csl::AmbisonicDecoder::initialize(), csl::Mixer::nextBuffer(), csl::Convolver2::setIRFile(), csl::Convolver::setIRFile(), and csl::SpatialSource::SpatialSource().
void csl::UnitGenerator::setNumChannels (unsigned ch) inline inherited
get/set the receiver's number of outputs
Definition at line 253 of file CSL_Core.h.
References csl::UnitGenerator::mNumChannels.
Referenced by csl::BinauralPanner::BinauralPanner(), csl::Spatializer::Spatializer(), csl::VBAP::speakerLayoutChanged(), and csl::VBAP::VBAP().
BufferCopyPolicy csl::UnitGenerator::copyPolicy () inline inherited
Definition at line 255 of file CSL_Core.h.
References csl::UnitGenerator::mCopyPolicy.
void csl::UnitGenerator::setCopyPolicy (BufferCopyPolicy ch) inline inherited
get/set the receiver's buffer copy policy
Definition at line 256 of file CSL_Core.h.
References csl::UnitGenerator::mCopyPolicy.
Referenced by csl::AmbisonicPanner::AmbisonicPanner(), csl::BinauralPanner::BinauralPanner(), csl::AmbisonicUnitGenerator::initOrder(), csl::Noise::Noise(), csl::PinkNoise::PinkNoise(), csl::Spatializer::Spatializer(), and csl::VBAP::VBAP().
void UnitGenerator::nextBuffer (Buffer & outputBuffer) throw (CException) virtual inherited
get a buffer of Frames – this is the core CSL "pull" function; the given buffer can be written into, and a changed() message is sent.
Reimplemented in csl::Joiner, csl::Splitter, csl::FanOut, csl::SoundCue, csl::Stereoverb, csl::StereoWidth, csl::Abst_SoundFile, csl::NtoMPanner, csl::RemoteStream, csl::BufferStream, csl::LSoundFile, csl::GrainPlayer, csl::Panner, csl::RingBuffer, csl::Instrument, csl::VBAP, csl::IFFT, csl::SpatialSource, csl::BinauralPanner, csl::InOut, csl::Spatializer, csl::Mixer, csl::SpatialPanner, csl::RingBufferTap, csl::Convolver, csl::Convolver, csl::AmbisonicPanner, csl::Convolver2, csl::BlockResizer, csl::FFT, csl::DelayLine, csl::SimplePanner, csl::SimplePanner, and csl::Microphone.
Definition at line 726 of file CSL_Core.cpp.
References csl::kCopy, csl::kExpand, csl::kIgnore, and csl::logMsg().
Referenced by csl::DistanceSimulator::nextBuffer(), csl::RingBufferTap::nextBuffer(), csl::Mixer::nextBuffer(), csl::AmbisonicMixer::nextBuffer(), csl::SpatialSource::nextBuffer(), csl::BufferStream::nextBuffer(), csl::Controllable::pullInput(), csl::PAIO::test(), and csl::FileIO::writeNextBuffer().
virtual bool csl::UnitGenerator::isFixed () inline virtual inherited
query whether I'm fixed (StaticVariable overrides this)
Reimplemented in csl::StaticVariable, and csl::BinaryOp.
Definition at line 271 of file CSL_Core.h.
virtual bool csl::UnitGenerator::isActive () inline virtual inherited
query whether I'm currently active (Envelopes can go inactive)
Reimplemented in csl::Joiner, csl::Effect, csl::RandEnvelope, csl::SoundCue, csl::Abst_SoundFile, csl::Stereoverb, csl::Envelope, csl::Instrument, csl::Mixer, and csl::KarplusString.
Definition at line 273 of file CSL_Core.h.
Referenced by csl::Instrument::isActive(), csl::Port::isActive(), csl::Mixer::nextBuffer(), csl::BinauralPanner::nextBuffer(), csl::AmbisonicMixer::nextBuffer(), and csl::VBAP::nextBuffer().
void UnitGenerator::addOutput (UnitGenerator * ugen) inherited
add to or return the UGen vector of outputs
Definition at line 670 of file CSL_Core.cpp.
References csl::Buffer::allocateBuffers(), csl::CGestalt::blockSize(), csl::UnitGenerator::mNumOutputs, csl::UnitGenerator::mOutputCache, and csl::UnitGenerator::mOutputs.
Referenced by csl::Mixer::addInput(), csl::Controllable::addInput(), csl::AmbisonicRotator::initialize(), csl::AmbisonicDecoder::initialize(), setInput(), and csl::IO::setRoot().
void UnitGenerator::removeOutput (UnitGenerator * ugen) inherited
Definition at line 680 of file CSL_Core.cpp.
References csl::UnitGenerator::mNumOutputs, and csl::UnitGenerator::mOutputs.
Referenced by csl::IO::clearRoot(), setInput(), csl::AmbisonicDecoder::~AmbisonicDecoder(), and csl::AmbisonicRotator::~AmbisonicRotator().
UGenVector csl::UnitGenerator::outputs () inline inherited
Definition at line 277 of file CSL_Core.h.
References csl::UnitGenerator::mOutputs.
virtual unsigned csl::UnitGenerator::numOutputs () inline virtual inherited
Definition at line 278 of file CSL_Core.h.
References csl::UnitGenerator::mNumOutputs.
bool UnitGenerator::checkFanOut (Buffer & outputBuffer) throw (CException) inherited
check for fan-out and copy previous buffer; return true if fanning out
Definition at line 699 of file CSL_Core.cpp.
void UnitGenerator::handleFanOut (Buffer & outputBuffer) throw (CException) inherited
Definition at line 713 of file CSL_Core.cpp.
References csl_max.
virtual void csl::UnitGenerator::setValue (sample theValue) inline virtual inherited
set/get the value (not allowed in the abstract, useful for static values)
Reimplemented in csl::DynamicVariable, and csl::StaticVariable.
Definition at line 284 of file CSL_Core.h.
virtual sample csl::UnitGenerator::value () inline virtual inherited
Reimplemented in csl::StaticVariable.
Definition at line 285 of file CSL_Core.h.
void UnitGenerator::dump (void) virtual inherited
pretty-print the receiver
Reimplemented in csl::RandEnvelope, csl::SumOfSines, csl::SoundCue, csl::Abst_SoundFile, csl::Filter, csl::Envelope, csl::BufferStream, csl::VBAP, csl::SineAsScaled, csl::LineSegment, csl::SpatialSource, csl::SineAsPhased, csl::Mixer, csl::Window, csl::KarplusString, csl::Oscillator, csl::AmbisonicPanner, csl::BinaryOp, csl::Lorenz, csl::Clipper, csl::Noise, and csl::CASoundFile.
Definition at line 693 of file CSL_Core.cpp.
References csl::logMsg(), and csl::UnitGenerator::mOutputs.
Referenced by csl::Noise::dump(), csl::Clipper::dump(), csl::Filter::dump(), csl::Port::dump(), dumpTest(), and testSimpleSines().
virtual void csl::UnitGenerator::trigger (void) inline virtual inherited
Reimplemented in csl::Joiner, csl::Effect, csl::RandEnvelope, csl::SoundCue, csl::Abst_SoundFile, csl::Envelope, csl::LineSegment, and csl::KarplusString.
Definition at line 288 of file CSL_Core.h.
Referenced by csl::Instrument::play(), csl::Instrument::release(), and csl::Port::trigger().
void UnitGenerator::zeroBuffer (Buffer & outputBuffer, unsigned outBufNum) protected inherited
utility method to zero out an outputBuffer
Definition at line 663 of file CSL_Core.cpp.
References csl::Buffer::buffer(), and csl::Buffer::mMonoBufferByteSize.
void Model::attachObserver (Observer * o) inherited
(possibly notify obersvers on my death)
register/remove observers
Definition at line 502 of file CGestalt.cpp.
References csl::logMsg(), csl::Observer::mKey, and csl::Observer::mPeriod.
Referenced by csl::SpatialPanner::setSpeakerLayout().
void Model::detachObserver (Observer * o) inherited
Definition at line 518 of file CGestalt.cpp.
References csl::logMsg().
Referenced by csl::SpatialPanner::setSpeakerLayout(), and csl::SpatialPanner::~SpatialPanner().
void Model::changed (void * argument) inherited
this is what I send to myself to notify my observers; It's not overridden in general. It results in the observers receiving update() calls < override evaluate to filter updates to the observer map
Definition at line 540 of file CGestalt.cpp.
References csl::logMsg().
Referenced by csl::SpeakerLayout::addSpeaker(), csl::MIDIIn::handleIncomingMidiMessage(), and csl::SpeakerLayout::setDefaultSpeakerLayout().
virtual int csl::Model::evaluate (void * argument) inline virtual inherited
Reimplemented in csl::MIDIIn.
Definition at line 270 of file CGestalt.h.
Friends And Related Function Documentation
void singularValueDecomposition (sample ** a, int m, int n, sample * w, sample ** v) related
Given a matrix a[m][n], this routine computes its singular value decomposition, A = U*W*V^{T}. The matrix U replaces a on output. The diagonal matrix of singular values W is output as a vector w[n]. The matrix V (not the transpose V^{T}) is output as v[n][n]. m must be greater or equal to n; if it is smaller, then a should be filled up to square with zero rows.
Definition at line 630 of file AmbisonicUtilities.cpp.
References MAX, PYTHAG, and SIGN.
Referenced by csl::AmbisonicDecoder::asPseudoInverse().
void fumaEncodingWeights (SampleBuffer weights, const AmbisonicOrder & order, float azimuth, float elevation) related
Definition at line 868 of file AmbisonicUtilities.cpp.
References csl::AmbisonicOrder::horizontalOrder, and csl::AmbisonicOrder::verticalOrder.
Referenced by csl::AmbisonicDecoder::makeTransposedReEncodingMatrix().
void fumaIndexedEncodingWeights (SampleBuffer weights, const AmbisonicOrder & order, sample & azimuth, sample & elevation) related
Definition at line 933 of file AmbisonicUtilities.cpp.
References csl::AmbisonicOrder::horizontalOrder, and csl::AmbisonicOrder::verticalOrder.
Member Data Documentation
SampleBuffer csl::AmbisonicEncoder::mWeights protected
Encoding weights for each order (per source)
Definition at line 139 of file Ambisonic.h.
Referenced by initialize(), and ~AmbisonicEncoder().
Port* csl::AmbisonicEncoder::mInputPort protected
Holds the input to be encoded.
Definition at line 140 of file Ambisonic.h.
Referenced by input(), setInput(), and ~AmbisonicEncoder().
AmbisonicOrder csl::AmbisonicUnitGenerator::mOrder protected inherited
the order of the Unit Generator
Definition at line 83 of file Ambisonic.h.
Referenced by csl::AmbisonicMixer::addInput(), csl::AmbisonicUnitGenerator::AmbisonicUnitGenerator(), csl::AmbisonicUnitGenerator::channelIndexer(), csl::AmbisonicMixer::initialize(), csl::AmbisonicRotator::initialize(), csl::AmbisonicDecoder::initialize(), csl::AmbisonicUnitGenerator::initOrder(), csl::AmbisonicUnitGenerator::invChannelIndexer(), csl::AmbisonicDecoder::makeTransposedReEncodingMatrix(), csl::AmbisonicUnitGenerator::order(), csl::AmbisonicRotator::rotateFirstOrderHorizontal(), csl::AmbisonicRotator::rotateSecondOrderHorizontal(), csl::AmbisonicRotator::rotateSecondOrderVertical(), csl::AmbisonicUnitGenerator::setOrder(), csl::AmbisonicRotator::setTilt(), and csl::AmbisonicRotator::setTumble().
unsigned csl::UnitGenerator::mFrameRate protected inherited
trigger ignored here
the frame rate – initialized to be the default by the constructor
Definition at line 288 of file CSL_Core.h.
Referenced by csl::Abst_SoundFile::convertRate(), csl::Lorenz::dump(), csl::Abst_SoundFile::durationInSecs(), csl::UnitGenerator::frameRate(), csl::Filter::init(), csl::CASoundFile::initFromSndfile(), csl::JSoundFile::initFromSndfile(), csl::LSoundFile::initFromSndfile(), csl::RandEnvelope::nextSegment(), csl::SquareBL::nextWaveInto(), csl::SumOfSines::nextWaveInto(), csl::DelayLine::setDelayTime(), csl::UnitGenerator::setFrameRate(), csl::Abst_SoundFile::setStartSec(), csl::Abst_SoundFile::setStopSec(), csl::Butter::setupCoeffs(), csl::Formant::setupCoeffs(), csl::Notch::setupCoeffs(), and csl::Moog::setupCoeffs().
unsigned csl::UnitGenerator::mNumChannels protected inherited
my "expected" number of output channels
Definition at line 292 of file CSL_Core.h.
Referenced by csl::AmbisonicMixer::addInput(), csl::Mixer::allocateOpBuffer(), csl::AmbisonicDecoder::asProjection(), csl::AmbisonicDecoder::asPseudoInverse(), csl::BlockResizer::BlockResizer(), csl::Abst_SoundFile::channels(), csl::Abst_SoundFile::checkBuffer(), csl::FMInstrument::FMInstrument(), csl::GrainPlayer::GrainPlayer(), csl::AdditiveInstrument::init(), csl::JSoundFile::initFromSndfile(), csl::LSoundFile::initFromSndfile(), csl::AmbisonicMixer::initialize(), csl::SndFileInstrument::initialize(), csl::AmbisonicRotator::initialize(), initialize(), csl::AmbisonicDecoder::initialize(), csl::AmbisonicUnitGenerator::initOrder(), csl::RemoteStream::initPacket(), csl::Joiner::isActive(), csl::Joiner::Joiner(), csl::AmbisonicDecoder::makeInPhase(), csl::AmbisonicDecoder::makeMaxRE(), csl::Abst_SoundFile::mergeToMono(), csl::Mixer::Mixer(), csl::UnitGenerator::numChannels(), csl::Panner::Panner(), csl::CASoundFile::readBufferFromFile(), csl::JSoundFile::readBufferFromFile(), csl::LSoundFile::readBufferFromFile(), csl::RemoteStream::RemoteStream(), csl::UnitGenerator::setNumChannels(), csl::WavetableOscillator::setWaveform(), csl::Joiner::trigger(), and csl::AmbisonicRotator::~AmbisonicRotator().
BufferCopyPolicy csl::UnitGenerator::mCopyPolicy protected inherited
the policy I use if asked for more or fewer channels
Definition at line 293 of file CSL_Core.h.
Referenced by csl::UnitGenerator::copyPolicy(), and csl::UnitGenerator::setCopyPolicy().
UGenVector csl::UnitGenerator::mOutputs protected inherited
the vector of my output UGens
Definition at line 294 of file CSL_Core.h.
Referenced by csl::UnitGenerator::addOutput(), csl::UnitGenerator::dump(), csl::UnitGenerator::outputs(), and csl::UnitGenerator::removeOutput().
unsigned csl::UnitGenerator::mNumOutputs protected inherited
the number of outputs
Definition at line 295 of file CSL_Core.h.
Referenced by csl::UnitGenerator::addOutput(), csl::UnitGenerator::numOutputs(), and csl::UnitGenerator::removeOutput().
Buffer* csl::UnitGenerator::mOutputCache protected inherited
my past output ring buffer (only used in case of fan-out)
Definition at line 296 of file CSL_Core.h.
Referenced by csl::UnitGenerator::addOutput().
unsigned csl::UnitGenerator::mSequence protected inherited
the highest-seen buffer seq number
Definition at line 297 of file CSL_Core.h.
The documentation for this class was generated from the following files:
/Content/Code/CSL/CSL/Spatializers/Ambisonic/Ambisonic.h
/Content/Code/CSL/CSL/Spatializers/Ambisonic/Ambisonic.cpp