CSL: csl::Interleaver Class Reference
csl::Interleaver Class Reference
Interleaver handles copying interleaved sample buffers (like sound files and inter-process sockets) to/from non-interleaved CSL-style Buffer objects.
#include <CSL_Core.h>
Public Member Functions
void interleave (Buffer &output, SampleBuffer samples, unsigned numFrames, unsigned numChannels) throw (CException)
Interleave = copy from CSL-style Buffer object to an interleaved sample vector.
void interleave (Buffer &output, short *samples, unsigned numFrames, unsigned numChannels) throw (CException)
void interleaveAndRemap (Buffer &output, SampleBuffer samples, unsigned numFrames, unsigned numChannels, unsigned *channelMap) throw (CException)
Interleave = copy from CSL-style Buffer object to an interleaved sample vector Remap = re-assign channels from the source buffer to the target while interleaving.
void deinterleave (Buffer &output, SampleBuffer samples, unsigned numFrames, unsigned numChannels) throw (CException)
De-interleave = copy from interleaved SampleBuffer to CSL Buffer object.
void deinterleave (Buffer &output, short *samples, unsigned numFrames, unsigned numChannels) throw (CException)
Detailed Description
Interleaver handles copying interleaved sample buffers (like sound files and inter-process sockets) to/from non-interleaved CSL-style Buffer objects.
Definition at line 672 of file CSL_Core.h.
Member Function Documentation
void Interleaver::interleave (Buffer & output, SampleBuffer samples, unsigned numFrames, unsigned numChannels) throw (CException)
Interleave = copy from CSL-style Buffer object to an interleaved sample vector.
Definition at line 1285 of file CSL_Core.cpp.
References csl_min.
void Interleaver::interleave (Buffer & output, short * samples, unsigned numFrames, unsigned numChannels) throw (CException)
Definition at line 1302 of file CSL_Core.cpp.
References csl_min.
void Interleaver::interleaveAndRemap (Buffer & output, SampleBuffer samples, unsigned numFrames, unsigned numChannels, unsigned * channelMap) throw (CException)
Interleave = copy from CSL-style Buffer object to an interleaved sample vector Remap = re-assign channels from the source buffer to the target while interleaving.
Remap = re-assign channels from the source buffer to the target while interleaving.
Definition at line 1319 of file CSL_Core.cpp.
References csl_min.
void Interleaver::deinterleave (Buffer & output, SampleBuffer samples, unsigned numFrames, unsigned numChannels) throw (CException)
De-interleave = copy from interleaved SampleBuffer to CSL Buffer object.
Definition at line 1337 of file CSL_Core.cpp.
References csl_min.
Referenced by csl::IO::getInput(), csl::CASoundFile::readBufferFromFile(), and csl::LSoundFile::readBufferFromFile().
void Interleaver::deinterleave (Buffer & output, short * samples, unsigned numFrames, unsigned numChannels) throw (CException)
Definition at line 1361 of file CSL_Core.cpp.
References csl_min.
The documentation for this class was generated from the following files:
/Content/Code/CSL/CSL/Kernel/CSL_Core.h
/Content/Code/CSL/CSL/Kernel/CSL_Core.cpp