CSL: csl::AmbisonicRotator Class Reference
csl::AmbisonicRotator Class Reference
#include <AmbisonicUtilities.h>
Public Member Functions
AmbisonicRotator (AmbisonicUnitGenerator &input)
initializes with no rotation
AmbisonicRotator (UnitGenerator &input, unsigned order)
initializes with uniform Ambisonic order and no rotation
AmbisonicRotator (UnitGenerator &input, unsigned vorder, unsigned horder)
initializes with hybrid Ambisonic order and no rotation
~AmbisonicRotator ()
void setNthInput (float amount, Axes axis)
void setTilt (float amount)
void setTumble (float amount)
void setRotate (float amount)
virtual void nextBuffer (Buffer &outputBuffer, unsigned outBufNum) throw (CException)
really compute the next buffer given an offset base channel; this is called by nextBuffer, possibly multiple times
AmbisonicOrder order ()
unsigned frameRate ()
void setFrameRate (unsigned rate)
get/set the receiver's frame rate
virtual unsigned numChannels ()
void setNumChannels (unsigned ch)
get/set the receiver's number of outputs
BufferCopyPolicy copyPolicy ()
void setCopyPolicy (BufferCopyPolicy ch)
get/set the receiver's buffer copy policy
virtual void nextBuffer (Buffer &outputBuffer) throw (CException)
get a buffer of Frames – this is the core CSL "pull" function; the given buffer can be written into, and a changed() message is sent.
virtual bool isFixed ()
query whether I'm fixed (StaticVariable overrides this)
virtual bool isActive ()
query whether I'm currently active (Envelopes can go inactive)
void addOutput (UnitGenerator *ugen)
add to or return the UGen vector of outputs
void removeOutput (UnitGenerator *ugen)
UGenVector outputs ()
virtual unsigned numOutputs ()
bool checkFanOut (Buffer &outputBuffer) throw (CException)
check for fan-out and copy previous buffer; return true if fanning out
void handleFanOut (Buffer &outputBuffer) throw (CException)
virtual void setValue (sample theValue)
set/get the value (not allowed in the abstract, useful for static values)
virtual sample value ()
virtual void dump ()
pretty-print the receiver
virtual void trigger ()
void attachObserver (Observer *)
(possibly notify obersvers on my death)
void detachObserver (Observer *)
void changed (void *argument)
this is what I send to myself to notify my observers; It's not overridden in general. It results in the observers receiving update() calls < override evaluate to filter updates to the observer map
virtual int evaluate (void *argument)
Protected Member Functions
void setOrder (AmbisonicOrder order)
Returns the Ambisonic order.
unsigned channelsToUniformOrder (const unsigned channels)
unsigned greaterOrder (const AmbisonicOrder order)
Compares the horizontal and vertical Ambisonic order of a hybrid order and returns the largest.
unsigned orderToChannels (const AmbisonicOrder order)
Returns the number of Ambisonic channels from a hybrid Ambisonic order: N = 2*M_h + 1 + (M_v + 1)^2 - (2*M_v + 1)
unsigned orderToChannels (unsigned order)
Returns the number of Ambisonic channels corresponding to a uniform Ambisonic order: N = (M+1)^2.
unsigned orderToHorizontalChannels (const AmbisonicOrder order)
Returns the number of horizontal Ambisonic channels from a hybrid Ambisonic order: N_h = 2*M_h + 1.
unsigned orderToVerticalChannels (const AmbisonicOrder order)
Returns the number of vertical Ambisonic channels from a hybrid Ambisonic order: N_v = (M_v + 1)^2 - (2*M_v + 1)
void channelIndexer (unsigned *indexArray)
Calculates a lookup table to map Ambisonic channel index to actually used UnitGenerator channel.
void invChannelIndexer (unsigned *indexArray)
Calculates a lookup table to map actually used UnitGenerator channel to Ambisonic channel index.
void zeroBuffer (Buffer &outputBuffer, unsigned outBufNum)
utility method to zero out an outputBuffer
Protected Attributes
unsigned mNumFrames
unsigned mGreaterOrder
unsigned mNumChannelsGreaterOrder
unsigned * mChannelIndex
unsigned * mInputChannelIndex
bool mShouldRotate
bool mShouldTurn
bool mShouldTilt
AmbisonicOrder mOrder
the order of the Unit Generator
unsigned mFrameRate
trigger ignored here
unsigned mNumChannels
my "expected" number of output channels
BufferCopyPolicy mCopyPolicy
the policy I use if asked for more or fewer channels
UGenVector mOutputs
the vector of my output UGens
unsigned mNumOutputs
the number of outputs
Buffer * mOutputCache
my past output ring buffer (only used in case of fan-out)
unsigned mSequence
the highest-seen buffer seq number
Private Member Functions
void initialize (UnitGenerator &input)
void tiltFirstOrder ()
void tiltSecondOrder ()
void tiltThirdOrder ()
void tumbleFirstOrder ()
void tumbleSecondOrder ()
void tumbleThirdOrder ()
void rotateZerothOrder ()
void rotateFirstOrderHorizontal ()
void rotateSecondOrderHorizontal ()
void rotateThirdOrderHorizontal ()
void rotateFirstOrderVertical ()
void rotateSecondOrderVertical ()
void rotateThirdOrderVertical ()
Private Attributes
Port * mInputPort
sample mRotate
sample mTumble
sample mTilt
SampleBuffer mSinAngle
SampleBuffer mCosAngle
SampleBufferVector mOutPtr
SampleBufferVector mInPtr
Related Functions
(Note that these are not member functions.)
void singularValueDecomposition (sample **a, int m, int n, sample *w, sample **v)
void fumaEncodingWeights (SampleBuffer weights, const AmbisonicOrder &order, float azimuth, float elevation)
void fumaIndexedEncodingWeights (SampleBuffer weights, const AmbisonicOrder &order, sample &azimuth, sample &elevation)
Detailed Description
Definition at line 84 of file AmbisonicUtilities.h.
Constructor & Destructor Documentation
AmbisonicRotator::AmbisonicRotator (AmbisonicUnitGenerator & input)
initializes with no rotation
Definition at line 146 of file AmbisonicUtilities.cpp.
References initialize().
AmbisonicRotator::AmbisonicRotator (UnitGenerator & input, unsigned order)
initializes with uniform Ambisonic order and no rotation
Definition at line 151 of file AmbisonicUtilities.cpp.
References initialize().
AmbisonicRotator::AmbisonicRotator (UnitGenerator & input, unsigned vorder, unsigned horder)
initializes with hybrid Ambisonic order and no rotation
Definition at line 156 of file AmbisonicUtilities.cpp.
References initialize().
AmbisonicRotator::~AmbisonicRotator (void)
Definition at line 161 of file AmbisonicUtilities.cpp.
References mChannelIndex, mCosAngle, mInPtr, mInputChannelIndex, mInputPort, csl::UnitGenerator::mNumChannels, mOutPtr, mSinAngle, csl::Port::mUGen, and csl::UnitGenerator::removeOutput().
Member Function Documentation
void AmbisonicRotator::setNthInput (float amount, Axes axis)
Definition at line 241 of file AmbisonicUtilities.cpp.
References csl::kLogError, csl::kROTATE, csl::kTILT, csl::kTUMBLE, csl::logMsg(), setRotate(), setTilt(), and setTumble().
void AmbisonicRotator::setTilt (float amount)
Definition at line 259 of file AmbisonicUtilities.cpp.
References csl::AmbisonicOrder::isUniform, csl::kLogWarning, csl::logMsg(), csl::AmbisonicUnitGenerator::mOrder, mShouldTilt, and mTilt.
Referenced by setNthInput().
void AmbisonicRotator::setTumble (float amount)
Definition at line 270 of file AmbisonicUtilities.cpp.
References csl::AmbisonicOrder::isUniform, csl::kLogWarning, csl::logMsg(), csl::AmbisonicUnitGenerator::mOrder, mShouldTurn, and mTumble.
Referenced by setNthInput().
void AmbisonicRotator::setRotate (float amount)
Definition at line 282 of file AmbisonicUtilities.cpp.
References mRotate, and mShouldRotate.
Referenced by csl::AmbisonicPanner::rotate(), and setNthInput().
void AmbisonicRotator::nextBuffer (Buffer & outputBuffer, unsigned outBufNum) throw (CException) virtual
really compute the next buffer given an offset base channel; this is called by nextBuffer, possibly multiple times
Reimplemented from csl::UnitGenerator.
Definition at line 297 of file AmbisonicUtilities.cpp.
References csl::Buffer::buffer(), csl::kLogError, csl::kSamples, csl::logMsg(), csl::Buffer::mIsPopulated, csl::Buffer::mNumFrames, and csl::Buffer::mType.
void AmbisonicRotator::initialize (UnitGenerator & input) private
Definition at line 187 of file AmbisonicUtilities.cpp.
References csl::UnitGenerator::addOutput(), csl::AmbisonicUnitGenerator::channelIndexer(), csl::AmbisonicUnitGenerator::greaterOrder(), csl::AmbisonicOrder::horizontalOrder, csl::AmbisonicOrder::isUniform, csl::kLogWarning, csl::logMsg(), mChannelIndex, mCosAngle, mGreaterOrder, mInPtr, mInputChannelIndex, mInputPort, csl::UnitGenerator::mNumChannels, mNumChannelsGreaterOrder, csl::AmbisonicUnitGenerator::mOrder, mOutPtr, mShouldRotate, mShouldTilt, mShouldTurn, mSinAngle, csl::UnitGenerator::numChannels(), csl::AmbisonicUnitGenerator::orderToChannels(), and csl::AmbisonicOrder::verticalOrder.
Referenced by AmbisonicRotator().
void AmbisonicRotator::tiltFirstOrder () private
Definition at line 397 of file AmbisonicUtilities.cpp.
References mCosAngle, mNumFrames, mOutPtr, and mSinAngle.
void AmbisonicRotator::tiltSecondOrder () private
Definition at line 412 of file AmbisonicUtilities.cpp.
References mCosAngle, mGreaterOrder, mNumFrames, mOutPtr, mSinAngle, and tiltThirdOrder().
void AmbisonicRotator::tiltThirdOrder () private
Definition at line 434 of file AmbisonicUtilities.cpp.
References mCosAngle, mNumFrames, mOutPtr, and mSinAngle.
Referenced by tiltSecondOrder().
void AmbisonicRotator::tumbleFirstOrder () private
Definition at line 461 of file AmbisonicUtilities.cpp.
References mCosAngle, mNumFrames, mOutPtr, and mSinAngle.
void AmbisonicRotator::tumbleSecondOrder () private
Definition at line 474 of file AmbisonicUtilities.cpp.
References mCosAngle, mGreaterOrder, mNumFrames, mOutPtr, mSinAngle, and tumbleThirdOrder().
void AmbisonicRotator::tumbleThirdOrder () private
Definition at line 494 of file AmbisonicUtilities.cpp.
References mCosAngle, mNumFrames, mOutPtr, and mSinAngle.
Referenced by tumbleSecondOrder().
void csl::AmbisonicRotator::rotateZerothOrder () private
void AmbisonicRotator::rotateFirstOrderHorizontal () private
Definition at line 522 of file AmbisonicUtilities.cpp.
References csl::AmbisonicOrder::horizontalOrder, mCosAngle, mNumFrames, csl::AmbisonicUnitGenerator::mOrder, mOutPtr, mSinAngle, and rotateSecondOrderHorizontal().
void AmbisonicRotator::rotateSecondOrderHorizontal () private
Definition at line 540 of file AmbisonicUtilities.cpp.
References csl::AmbisonicOrder::horizontalOrder, mCosAngle, mNumFrames, csl::AmbisonicUnitGenerator::mOrder, mOutPtr, mSinAngle, and rotateThirdOrderHorizontal().
Referenced by rotateFirstOrderHorizontal().
void AmbisonicRotator::rotateThirdOrderHorizontal () private
Definition at line 567 of file AmbisonicUtilities.cpp.
References mCosAngle, mNumFrames, mOutPtr, and mSinAngle.
Referenced by rotateSecondOrderHorizontal().
void csl::AmbisonicRotator::rotateFirstOrderVertical () private
void AmbisonicRotator::rotateSecondOrderVertical () private
Definition at line 553 of file AmbisonicUtilities.cpp.
References mCosAngle, mNumFrames, csl::AmbisonicUnitGenerator::mOrder, mOutPtr, mSinAngle, rotateThirdOrderVertical(), and csl::AmbisonicOrder::verticalOrder.
void AmbisonicRotator::rotateThirdOrderVertical () private
Definition at line 583 of file AmbisonicUtilities.cpp.
References mCosAngle, mNumFrames, mOutPtr, and mSinAngle.
Referenced by rotateSecondOrderVertical().
AmbisonicOrder csl::AmbisonicUnitGenerator::order () inline inherited
Definition at line 78 of file Ambisonic.h.
References csl::AmbisonicUnitGenerator::mOrder.
Referenced by csl::AmbisonicMixer::addInput(), and csl::AmbisonicDecoder::makeTransposedReEncodingMatrix().
void AmbisonicUnitGenerator::setOrder (AmbisonicOrder order) protected inherited
Returns the Ambisonic order.
Definition at line 59 of file Ambisonic.cpp.
References csl::AmbisonicUnitGenerator::initOrder(), and csl::AmbisonicUnitGenerator::mOrder.
unsigned AmbisonicUnitGenerator::channelsToUniformOrder (const unsigned channels) protected inherited
Definition at line 66 of file Ambisonic.cpp.
Referenced by csl::AmbisonicDecoder::makeInPhase(), and csl::AmbisonicDecoder::makeMaxRE().
unsigned AmbisonicUnitGenerator::greaterOrder (const AmbisonicOrder order) protected inherited
Compares the horizontal and vertical Ambisonic order of a hybrid order and returns the largest.
Definition at line 71 of file Ambisonic.cpp.
References csl::AmbisonicOrder::horizontalOrder, and csl::AmbisonicOrder::verticalOrder.
Referenced by csl::AmbisonicUnitGenerator::channelIndexer(), initialize(), csl::AmbisonicDecoder::initialize(), and csl::AmbisonicDecoder::makeMaxRE().
unsigned AmbisonicUnitGenerator::orderToChannels (const AmbisonicOrder order) protected inherited
Returns the number of Ambisonic channels from a hybrid Ambisonic order: N = 2*M_h + 1 + (M_v + 1)^2 - (2*M_v + 1)
Definition at line 75 of file Ambisonic.cpp.
References csl::AmbisonicOrder::horizontalOrder, and csl::AmbisonicOrder::verticalOrder.
Referenced by csl::AmbisonicUnitGenerator::channelIndexer(), initialize(), csl::AmbisonicDecoder::initialize(), csl::AmbisonicUnitGenerator::initOrder(), and csl::AmbisonicUnitGenerator::invChannelIndexer().
unsigned AmbisonicUnitGenerator::orderToChannels (unsigned order) protected inherited
Returns the number of Ambisonic channels corresponding to a uniform Ambisonic order: N = (M+1)^2.
Definition at line 80 of file Ambisonic.cpp.
unsigned AmbisonicUnitGenerator::orderToHorizontalChannels (const AmbisonicOrder order) protected inherited
Returns the number of horizontal Ambisonic channels from a hybrid Ambisonic order: N_h = 2*M_h + 1.
Definition at line 85 of file Ambisonic.cpp.
References csl::AmbisonicOrder::horizontalOrder.
unsigned AmbisonicUnitGenerator::orderToVerticalChannels (const AmbisonicOrder order) protected inherited
Returns the number of vertical Ambisonic channels from a hybrid Ambisonic order: N_v = (M_v + 1)^2 - (2*M_v + 1)
Definition at line 90 of file Ambisonic.cpp.
References csl::AmbisonicOrder::verticalOrder.
void AmbisonicUnitGenerator::channelIndexer (unsigned * indexArray) protected inherited
Calculates a lookup table to map Ambisonic channel index to actually used UnitGenerator channel.
Definition at line 98 of file Ambisonic.cpp.
References csl::AmbisonicUnitGenerator::greaterOrder(), csl::AmbisonicOrder::horizontalOrder, csl::AmbisonicUnitGenerator::mOrder, csl::AmbisonicUnitGenerator::orderToChannels(), and csl::AmbisonicOrder::verticalOrder.
Referenced by initialize(), and csl::AmbisonicDecoder::initialize().
void AmbisonicUnitGenerator::invChannelIndexer (unsigned * indexArray) protected inherited
Calculates a lookup table to map actually used UnitGenerator channel to Ambisonic channel index.
Definition at line 146 of file Ambisonic.cpp.
References csl::AmbisonicOrder::horizontalOrder, csl::AmbisonicUnitGenerator::mOrder, csl::AmbisonicUnitGenerator::orderToChannels(), and csl::AmbisonicOrder::verticalOrder.
Referenced by csl::AmbisonicDecoder::initialize().
unsigned csl::UnitGenerator::frameRate () inline inherited
Definition at line 249 of file CSL_Core.h.
References csl::UnitGenerator::mFrameRate.
Referenced by csl::CASoundFile::dump(), csl::Abst_SoundFile::dump(), and csl::SoundCue::dump().
void csl::UnitGenerator::setFrameRate (unsigned rate) inline inherited
get/set the receiver's frame rate
Definition at line 250 of file CSL_Core.h.
References csl::UnitGenerator::mFrameRate.
virtual unsigned csl::UnitGenerator::numChannels () inline virtual inherited
Reimplemented in csl::Splitter, and csl::Stereoverb.
Definition at line 252 of file CSL_Core.h.
References csl::UnitGenerator::mNumChannels.
Referenced by csl::AmbisonicMixer::addInput(), csl::BlockResizer::BlockResizer(), csl::Port::checkBuffer(), csl::Effect::Effect(), initialize(), csl::AmbisonicDecoder::initialize(), csl::Mixer::nextBuffer(), csl::Convolver2::setIRFile(), csl::Convolver::setIRFile(), and csl::SpatialSource::SpatialSource().
void csl::UnitGenerator::setNumChannels (unsigned ch) inline inherited
get/set the receiver's number of outputs
Definition at line 253 of file CSL_Core.h.
References csl::UnitGenerator::mNumChannels.
Referenced by csl::BinauralPanner::BinauralPanner(), csl::Spatializer::Spatializer(), csl::VBAP::speakerLayoutChanged(), and csl::VBAP::VBAP().
BufferCopyPolicy csl::UnitGenerator::copyPolicy () inline inherited
Definition at line 255 of file CSL_Core.h.
References csl::UnitGenerator::mCopyPolicy.
void csl::UnitGenerator::setCopyPolicy (BufferCopyPolicy ch) inline inherited
get/set the receiver's buffer copy policy
Definition at line 256 of file CSL_Core.h.
References csl::UnitGenerator::mCopyPolicy.
Referenced by csl::AmbisonicPanner::AmbisonicPanner(), csl::BinauralPanner::BinauralPanner(), csl::AmbisonicUnitGenerator::initOrder(), csl::Noise::Noise(), csl::PinkNoise::PinkNoise(), csl::Spatializer::Spatializer(), and csl::VBAP::VBAP().
void UnitGenerator::nextBuffer (Buffer & outputBuffer) throw (CException) virtual inherited
get a buffer of Frames – this is the core CSL "pull" function; the given buffer can be written into, and a changed() message is sent.
Reimplemented in csl::Joiner, csl::Splitter, csl::FanOut, csl::SoundCue, csl::Stereoverb, csl::StereoWidth, csl::Abst_SoundFile, csl::NtoMPanner, csl::RemoteStream, csl::BufferStream, csl::LSoundFile, csl::GrainPlayer, csl::Panner, csl::RingBuffer, csl::Instrument, csl::VBAP, csl::IFFT, csl::SpatialSource, csl::BinauralPanner, csl::InOut, csl::Spatializer, csl::Mixer, csl::SpatialPanner, csl::RingBufferTap, csl::Convolver, csl::Convolver, csl::AmbisonicPanner, csl::Convolver2, csl::BlockResizer, csl::FFT, csl::DelayLine, csl::SimplePanner, csl::SimplePanner, and csl::Microphone.
Definition at line 726 of file CSL_Core.cpp.
References csl::kCopy, csl::kExpand, csl::kIgnore, and csl::logMsg().
Referenced by csl::DistanceSimulator::nextBuffer(), csl::RingBufferTap::nextBuffer(), csl::Mixer::nextBuffer(), csl::AmbisonicMixer::nextBuffer(), csl::SpatialSource::nextBuffer(), csl::BufferStream::nextBuffer(), csl::Controllable::pullInput(), csl::PAIO::test(), and csl::FileIO::writeNextBuffer().
virtual bool csl::UnitGenerator::isFixed () inline virtual inherited
query whether I'm fixed (StaticVariable overrides this)
Reimplemented in csl::StaticVariable, and csl::BinaryOp.
Definition at line 271 of file CSL_Core.h.
virtual bool csl::UnitGenerator::isActive () inline virtual inherited
query whether I'm currently active (Envelopes can go inactive)
Reimplemented in csl::Joiner, csl::Effect, csl::RandEnvelope, csl::SoundCue, csl::Abst_SoundFile, csl::Stereoverb, csl::Envelope, csl::Instrument, csl::Mixer, and csl::KarplusString.
Definition at line 273 of file CSL_Core.h.
Referenced by csl::Instrument::isActive(), csl::Port::isActive(), csl::Mixer::nextBuffer(), csl::BinauralPanner::nextBuffer(), csl::AmbisonicMixer::nextBuffer(), and csl::VBAP::nextBuffer().
void UnitGenerator::addOutput (UnitGenerator * ugen) inherited
add to or return the UGen vector of outputs
Definition at line 670 of file CSL_Core.cpp.
References csl::Buffer::allocateBuffers(), csl::CGestalt::blockSize(), csl::UnitGenerator::mNumOutputs, csl::UnitGenerator::mOutputCache, and csl::UnitGenerator::mOutputs.
Referenced by csl::Mixer::addInput(), csl::Controllable::addInput(), initialize(), csl::AmbisonicDecoder::initialize(), csl::AmbisonicEncoder::setInput(), and csl::IO::setRoot().
void UnitGenerator::removeOutput (UnitGenerator * ugen) inherited
Definition at line 680 of file CSL_Core.cpp.
References csl::UnitGenerator::mNumOutputs, and csl::UnitGenerator::mOutputs.
Referenced by csl::IO::clearRoot(), csl::AmbisonicEncoder::setInput(), csl::AmbisonicDecoder::~AmbisonicDecoder(), and ~AmbisonicRotator().
UGenVector csl::UnitGenerator::outputs () inline inherited
Definition at line 277 of file CSL_Core.h.
References csl::UnitGenerator::mOutputs.
virtual unsigned csl::UnitGenerator::numOutputs () inline virtual inherited
Definition at line 278 of file CSL_Core.h.
References csl::UnitGenerator::mNumOutputs.
bool UnitGenerator::checkFanOut (Buffer & outputBuffer) throw (CException) inherited
check for fan-out and copy previous buffer; return true if fanning out
Definition at line 699 of file CSL_Core.cpp.
void UnitGenerator::handleFanOut (Buffer & outputBuffer) throw (CException) inherited
Definition at line 713 of file CSL_Core.cpp.
References csl_max.
virtual void csl::UnitGenerator::setValue (sample theValue) inline virtual inherited
set/get the value (not allowed in the abstract, useful for static values)
Reimplemented in csl::DynamicVariable, and csl::StaticVariable.
Definition at line 284 of file CSL_Core.h.
virtual sample csl::UnitGenerator::value () inline virtual inherited
Reimplemented in csl::StaticVariable.
Definition at line 285 of file CSL_Core.h.
void UnitGenerator::dump (void) virtual inherited
pretty-print the receiver
Reimplemented in csl::RandEnvelope, csl::SumOfSines, csl::SoundCue, csl::Abst_SoundFile, csl::Filter, csl::Envelope, csl::BufferStream, csl::VBAP, csl::SineAsScaled, csl::LineSegment, csl::SpatialSource, csl::SineAsPhased, csl::Mixer, csl::Window, csl::KarplusString, csl::Oscillator, csl::AmbisonicPanner, csl::BinaryOp, csl::Lorenz, csl::Clipper, csl::Noise, and csl::CASoundFile.
Definition at line 693 of file CSL_Core.cpp.
References csl::logMsg(), and csl::UnitGenerator::mOutputs.
Referenced by csl::Noise::dump(), csl::Clipper::dump(), csl::Filter::dump(), csl::Port::dump(), dumpTest(), and testSimpleSines().
virtual void csl::UnitGenerator::trigger (void) inline virtual inherited
Reimplemented in csl::Joiner, csl::Effect, csl::RandEnvelope, csl::SoundCue, csl::Abst_SoundFile, csl::Envelope, csl::LineSegment, and csl::KarplusString.
Definition at line 288 of file CSL_Core.h.
Referenced by csl::Instrument::play(), csl::Instrument::release(), and csl::Port::trigger().
void UnitGenerator::zeroBuffer (Buffer & outputBuffer, unsigned outBufNum) protected inherited
utility method to zero out an outputBuffer
Definition at line 663 of file CSL_Core.cpp.
References csl::Buffer::buffer(), and csl::Buffer::mMonoBufferByteSize.
void Model::attachObserver (Observer * o) inherited
(possibly notify obersvers on my death)
register/remove observers
Definition at line 502 of file CGestalt.cpp.
References csl::logMsg(), csl::Observer::mKey, and csl::Observer::mPeriod.
Referenced by csl::SpatialPanner::setSpeakerLayout().
void Model::detachObserver (Observer * o) inherited
Definition at line 518 of file CGestalt.cpp.
References csl::logMsg().
Referenced by csl::SpatialPanner::setSpeakerLayout(), and csl::SpatialPanner::~SpatialPanner().
void Model::changed (void * argument) inherited
this is what I send to myself to notify my observers; It's not overridden in general. It results in the observers receiving update() calls < override evaluate to filter updates to the observer map
Definition at line 540 of file CGestalt.cpp.
References csl::logMsg().
Referenced by csl::SpeakerLayout::addSpeaker(), csl::MIDIIn::handleIncomingMidiMessage(), and csl::SpeakerLayout::setDefaultSpeakerLayout().
virtual int csl::Model::evaluate (void * argument) inline virtual inherited
Reimplemented in csl::MIDIIn.
Definition at line 270 of file CGestalt.h.
Friends And Related Function Documentation
void singularValueDecomposition (sample ** a, int m, int n, sample * w, sample ** v) related
Given a matrix a[m][n], this routine computes its singular value decomposition, A = U*W*V^{T}. The matrix U replaces a on output. The diagonal matrix of singular values W is output as a vector w[n]. The matrix V (not the transpose V^{T}) is output as v[n][n]. m must be greater or equal to n; if it is smaller, then a should be filled up to square with zero rows.
Definition at line 630 of file AmbisonicUtilities.cpp.
References MAX, PYTHAG, and SIGN.
Referenced by csl::AmbisonicDecoder::asPseudoInverse().
void fumaEncodingWeights (SampleBuffer weights, const AmbisonicOrder & order, float azimuth, float elevation) related
Definition at line 868 of file AmbisonicUtilities.cpp.
References csl::AmbisonicOrder::horizontalOrder, and csl::AmbisonicOrder::verticalOrder.
Referenced by csl::AmbisonicDecoder::makeTransposedReEncodingMatrix().
void fumaIndexedEncodingWeights (SampleBuffer weights, const AmbisonicOrder & order, sample & azimuth, sample & elevation) related
Definition at line 933 of file AmbisonicUtilities.cpp.
References csl::AmbisonicOrder::horizontalOrder, and csl::AmbisonicOrder::verticalOrder.
Member Data Documentation
unsigned csl::AmbisonicRotator::mNumFrames protected
Definition at line 107 of file AmbisonicUtilities.h.
Referenced by rotateFirstOrderHorizontal(), rotateSecondOrderHorizontal(), rotateSecondOrderVertical(), rotateThirdOrderHorizontal(), rotateThirdOrderVertical(), tiltFirstOrder(), tiltSecondOrder(), tiltThirdOrder(), tumbleFirstOrder(), tumbleSecondOrder(), and tumbleThirdOrder().
unsigned csl::AmbisonicRotator::mGreaterOrder protected
Definition at line 108 of file AmbisonicUtilities.h.
Referenced by initialize(), tiltSecondOrder(), and tumbleSecondOrder().
unsigned csl::AmbisonicRotator::mNumChannelsGreaterOrder protected
Definition at line 109 of file AmbisonicUtilities.h.
Referenced by initialize().
unsigned* csl::AmbisonicRotator::mChannelIndex protected
Definition at line 110 of file AmbisonicUtilities.h.
Referenced by initialize(), and ~AmbisonicRotator().
unsigned* csl::AmbisonicRotator::mInputChannelIndex protected
Definition at line 111 of file AmbisonicUtilities.h.
Referenced by initialize(), and ~AmbisonicRotator().
bool csl::AmbisonicRotator::mShouldRotate protected
Definition at line 112 of file AmbisonicUtilities.h.
Referenced by initialize(), and setRotate().
bool csl::AmbisonicRotator::mShouldTurn protected
Definition at line 112 of file AmbisonicUtilities.h.
Referenced by initialize(), and setTumble().
bool csl::AmbisonicRotator::mShouldTilt protected
Definition at line 112 of file AmbisonicUtilities.h.
Referenced by initialize(), and setTilt().
Port* csl::AmbisonicRotator::mInputPort private
Definition at line 115 of file AmbisonicUtilities.h.
Referenced by initialize(), and ~AmbisonicRotator().
sample csl::AmbisonicRotator::mRotate private
Definition at line 117 of file AmbisonicUtilities.h.
Referenced by setRotate().
sample csl::AmbisonicRotator::mTumble private
Definition at line 117 of file AmbisonicUtilities.h.
Referenced by setTumble().
sample csl::AmbisonicRotator::mTilt private
Definition at line 117 of file AmbisonicUtilities.h.
Referenced by setTilt().
SampleBuffer csl::AmbisonicRotator::mSinAngle private
Definition at line 118 of file AmbisonicUtilities.h.
Referenced by initialize(), rotateFirstOrderHorizontal(), rotateSecondOrderHorizontal(), rotateSecondOrderVertical(), rotateThirdOrderHorizontal(), rotateThirdOrderVertical(), tiltFirstOrder(), tiltSecondOrder(), tiltThirdOrder(), tumbleFirstOrder(), tumbleSecondOrder(), tumbleThirdOrder(), and ~AmbisonicRotator().
SampleBuffer csl::AmbisonicRotator::mCosAngle private
Definition at line 118 of file AmbisonicUtilities.h.
Referenced by initialize(), rotateFirstOrderHorizontal(), rotateSecondOrderHorizontal(), rotateSecondOrderVertical(), rotateThirdOrderHorizontal(), rotateThirdOrderVertical(), tiltFirstOrder(), tiltSecondOrder(), tiltThirdOrder(), tumbleFirstOrder(), tumbleSecondOrder(), tumbleThirdOrder(), and ~AmbisonicRotator().
SampleBufferVector csl::AmbisonicRotator::mOutPtr private
Definition at line 119 of file AmbisonicUtilities.h.
Referenced by initialize(), rotateFirstOrderHorizontal(), rotateSecondOrderHorizontal(), rotateSecondOrderVertical(), rotateThirdOrderHorizontal(), rotateThirdOrderVertical(), tiltFirstOrder(), tiltSecondOrder(), tiltThirdOrder(), tumbleFirstOrder(), tumbleSecondOrder(), tumbleThirdOrder(), and ~AmbisonicRotator().
SampleBufferVector csl::AmbisonicRotator::mInPtr private
Definition at line 119 of file AmbisonicUtilities.h.
Referenced by initialize(), and ~AmbisonicRotator().
AmbisonicOrder csl::AmbisonicUnitGenerator::mOrder protected inherited
the order of the Unit Generator
Definition at line 83 of file Ambisonic.h.
Referenced by csl::AmbisonicMixer::addInput(), csl::AmbisonicUnitGenerator::AmbisonicUnitGenerator(), csl::AmbisonicUnitGenerator::channelIndexer(), csl::AmbisonicMixer::initialize(), initialize(), csl::AmbisonicDecoder::initialize(), csl::AmbisonicUnitGenerator::initOrder(), csl::AmbisonicUnitGenerator::invChannelIndexer(), csl::AmbisonicDecoder::makeTransposedReEncodingMatrix(), csl::AmbisonicUnitGenerator::order(), rotateFirstOrderHorizontal(), rotateSecondOrderHorizontal(), rotateSecondOrderVertical(), csl::AmbisonicUnitGenerator::setOrder(), setTilt(), and setTumble().
unsigned csl::UnitGenerator::mFrameRate protected inherited
trigger ignored here
the frame rate – initialized to be the default by the constructor
Definition at line 288 of file CSL_Core.h.
Referenced by csl::Abst_SoundFile::convertRate(), csl::Lorenz::dump(), csl::Abst_SoundFile::durationInSecs(), csl::UnitGenerator::frameRate(), csl::Filter::init(), csl::CASoundFile::initFromSndfile(), csl::JSoundFile::initFromSndfile(), csl::LSoundFile::initFromSndfile(), csl::RandEnvelope::nextSegment(), csl::SquareBL::nextWaveInto(), csl::SumOfSines::nextWaveInto(), csl::DelayLine::setDelayTime(), csl::UnitGenerator::setFrameRate(), csl::Abst_SoundFile::setStartSec(), csl::Abst_SoundFile::setStopSec(), csl::Butter::setupCoeffs(), csl::Formant::setupCoeffs(), csl::Notch::setupCoeffs(), and csl::Moog::setupCoeffs().
unsigned csl::UnitGenerator::mNumChannels protected inherited
my "expected" number of output channels
Definition at line 292 of file CSL_Core.h.
Referenced by csl::AmbisonicMixer::addInput(), csl::Mixer::allocateOpBuffer(), csl::AmbisonicDecoder::asProjection(), csl::AmbisonicDecoder::asPseudoInverse(), csl::BlockResizer::BlockResizer(), csl::Abst_SoundFile::channels(), csl::Abst_SoundFile::checkBuffer(), csl::FMInstrument::FMInstrument(), csl::GrainPlayer::GrainPlayer(), csl::AdditiveInstrument::init(), csl::JSoundFile::initFromSndfile(), csl::LSoundFile::initFromSndfile(), csl::AmbisonicMixer::initialize(), csl::SndFileInstrument::initialize(), initialize(), csl::AmbisonicEncoder::initialize(), csl::AmbisonicDecoder::initialize(), csl::AmbisonicUnitGenerator::initOrder(), csl::RemoteStream::initPacket(), csl::Joiner::isActive(), csl::Joiner::Joiner(), csl::AmbisonicDecoder::makeInPhase(), csl::AmbisonicDecoder::makeMaxRE(), csl::Abst_SoundFile::mergeToMono(), csl::Mixer::Mixer(), csl::UnitGenerator::numChannels(), csl::Panner::Panner(), csl::CASoundFile::readBufferFromFile(), csl::JSoundFile::readBufferFromFile(), csl::LSoundFile::readBufferFromFile(), csl::RemoteStream::RemoteStream(), csl::UnitGenerator::setNumChannels(), csl::WavetableOscillator::setWaveform(), csl::Joiner::trigger(), and ~AmbisonicRotator().
BufferCopyPolicy csl::UnitGenerator::mCopyPolicy protected inherited
the policy I use if asked for more or fewer channels
Definition at line 293 of file CSL_Core.h.
Referenced by csl::UnitGenerator::copyPolicy(), and csl::UnitGenerator::setCopyPolicy().
UGenVector csl::UnitGenerator::mOutputs protected inherited
the vector of my output UGens
Definition at line 294 of file CSL_Core.h.
Referenced by csl::UnitGenerator::addOutput(), csl::UnitGenerator::dump(), csl::UnitGenerator::outputs(), and csl::UnitGenerator::removeOutput().
unsigned csl::UnitGenerator::mNumOutputs protected inherited
the number of outputs
Definition at line 295 of file CSL_Core.h.
Referenced by csl::UnitGenerator::addOutput(), csl::UnitGenerator::numOutputs(), and csl::UnitGenerator::removeOutput().
Buffer* csl::UnitGenerator::mOutputCache protected inherited
my past output ring buffer (only used in case of fan-out)
Definition at line 296 of file CSL_Core.h.
Referenced by csl::UnitGenerator::addOutput().
unsigned csl::UnitGenerator::mSequence protected inherited
the highest-seen buffer seq number
Definition at line 297 of file CSL_Core.h.
The documentation for this class was generated from the following files:
/Content/Code/CSL/CSL/Spatializers/Ambisonic/AmbisonicUtilities.h
/Content/Code/CSL/CSL/Spatializers/Ambisonic/AmbisonicUtilities.cpp