CSL: csl::StereoPanner Class Reference
csl::StereoPanner Class Reference
Simple Stereo Panner.
#include <VBAP.h>
Public Member Functions
StereoPanner ()
virtual ~StereoPanner ()
void addInput (UnitGenerator &input, float panPosition)
void nextBuffer (Buffer &outputBuffer) throw (CException)
Just as any Effect in CSL, this method gets called at runtime by the audio driver. Here is where the actual processing happens.
void nextBuffer (Buffer &outputBuffer, unsigned outBufNum) throw (CException)
really compute the next buffer given an offset base channel; this is called by nextBuffer, possibly multiple times
void dump ()
pretty-print the receiver
void setSpeakerLayout (SpeakerLayout *aLayout)
Set the speaker layout to be used by this panner. The panner will request the default layout if not set.
unsigned numSources ()
virtual void addSource (SpatialSource &s)
number of active inputs.
virtual void removeSource (SpatialSource &s)
Remove a Sound Source.
virtual void update (void *arg)
Called when the speaker layout changes.
unsigned frameRate ()
void setFrameRate (unsigned rate)
get/set the receiver's frame rate
virtual unsigned numChannels ()
void setNumChannels (unsigned ch)
get/set the receiver's number of outputs
BufferCopyPolicy copyPolicy ()
void setCopyPolicy (BufferCopyPolicy ch)
get/set the receiver's buffer copy policy
virtual bool isFixed ()
query whether I'm fixed (StaticVariable overrides this)
virtual bool isActive ()
query whether I'm currently active (Envelopes can go inactive)
void addOutput (UnitGenerator *ugen)
add to or return the UGen vector of outputs
void removeOutput (UnitGenerator *ugen)
UGenVector outputs ()
virtual unsigned numOutputs ()
bool checkFanOut (Buffer &outputBuffer) throw (CException)
check for fan-out and copy previous buffer; return true if fanning out
void handleFanOut (Buffer &outputBuffer) throw (CException)
virtual void setValue (sample theValue)
set/get the value (not allowed in the abstract, useful for static values)
virtual sample value ()
virtual void trigger ()
void attachObserver (Observer *)
(possibly notify obersvers on my death)
void detachObserver (Observer *)
void changed (void *argument)
this is what I send to myself to notify my observers; It's not overridden in general. It results in the observers receiving update() calls < override evaluate to filter updates to the observer map
virtual int evaluate (void *argument)
Public Attributes
float mPeriod
virtual destructor (don't notify or delete observers in this version)
int mKey
key selector (e.g., MIDI chan) I receive update() mesages from my model;
Protected Member Functions
virtual void * cache ()
Returns an instance of it's cache data per sound source.
virtual void speakerLayoutChanged ()
called when the speaker layout changes, so panners update precalculated data
void zeroBuffer (Buffer &outputBuffer, unsigned outBufNum)
utility method to zero out an outputBuffer
Protected Attributes
VBAPMode mMode
Prints useful information about this VBAP instance.
SpeakerSetLayout * mSpeakerSetLayout
A reference to the layout that contains the speaker pairs or triplets.
UGenVector mSources
SpatialSource... refers to its input UGen, but with the knowledge of its position within a space.
vector< void * > mCache
Vector of pointers to the prior I/O data.
SpeakerLayout * mSpeakerLayout
If null, it will use the default layout by calling SpeakerLayout::defaultSpeakerLayout();.
Buffer mTempBuffer
Buffer used to temporarily hold input source data.
unsigned mFrameRate
trigger ignored here
unsigned mNumChannels
my "expected" number of output channels
BufferCopyPolicy mCopyPolicy
the policy I use if asked for more or fewer channels
UGenVector mOutputs
the vector of my output UGens
unsigned mNumOutputs
the number of outputs
Buffer * mOutputCache
my past output ring buffer (only used in case of fan-out)
unsigned mSequence
the highest-seen buffer seq number
Detailed Description
Simple Stereo Panner.
Todo:
Add method for setting the pan value from 0 to 1.
Definition at line 86 of file VBAP.h.
Constructor & Destructor Documentation
StereoPanner::StereoPanner ()
Definition at line 465 of file VBAP.cpp.
StereoPanner::~StereoPanner () virtual
Definition at line 467 of file VBAP.cpp.
References csl::SpatialPanner::mSpeakerLayout.
Member Function Documentation
void csl::StereoPanner::addInput (UnitGenerator & input, float panPosition)
void VBAP::nextBuffer (Buffer & outputBuffer) throw (CException) virtual inherited
Just as any Effect in CSL, this method gets called at runtime by the audio driver. Here is where the actual processing happens.
Implements csl::SpatialPanner.
Definition at line 390 of file VBAP.cpp.
void VBAP::nextBuffer (Buffer & outputBuffer, unsigned outBufNum) throw (CException) virtual inherited
really compute the next buffer given an offset base channel; this is called by nextBuffer, possibly multiple times
Reimplemented from csl::SpatialPanner.
Definition at line 394 of file VBAP.cpp.
References csl::VBAPSourceCache::gains, csl::UnitGenerator::isActive(), csl::CPoint::len(), csl::logMsg(), csl::SpatialSource::nextBuffer(), csl::SpeakerSet::nodes, csl::CPoint::normalize(), csl::SpatialSource::position(), csl::SpatialSource::positionChanged(), csl::VBAPSourceCache::tripletIndex, vectorMultiply(), csl::CPoint::x, csl::CPoint::y, and csl::CPoint::z.
void csl::VBAP::dump (void) inline virtual inherited
pretty-print the receiver
Reimplemented from csl::UnitGenerator.
Definition at line 73 of file VBAP.h.
void * VBAP::cache () protected virtual inherited
Returns an instance of it's cache data per sound source.
Reimplemented from csl::SpatialPanner.
Definition at line 386 of file VBAP.cpp.
void VBAP::speakerLayoutChanged () protected virtual inherited
called when the speaker layout changes, so panners update precalculated data
Reimplemented from csl::SpatialPanner.
Definition at line 378 of file VBAP.cpp.
References csl::SpatialPanner::mSpeakerLayout, csl::VBAP::mSpeakerSetLayout, csl::SpeakerLayout::numSpeakers(), and csl::UnitGenerator::setNumChannels().
void SpatialPanner::setSpeakerLayout (SpeakerLayout * aLayout) inherited
Set the speaker layout to be used by this panner. The panner will request the default layout if not set.
Definition at line 25 of file SpatialPanner.cpp.
References csl::Model::attachObserver(), csl::Model::detachObserver(), csl::SpatialPanner::mSpeakerLayout, and csl::SpatialPanner::speakerLayoutChanged().
Referenced by csl::SpatialPanner::SpatialPanner(), and csl::SpatialPanner::update().
unsigned csl::SpatialPanner::numSources () inline inherited
Definition at line 32 of file SpatialPanner.h.
References csl::SpatialPanner::mSources.
Referenced by csl::Spatializer::numSources().
void SpatialPanner::addSource (SpatialSource & s) virtual inherited
number of active inputs.
Add a souce to the list of inputs to be processed and create a cache object
Reimplemented in csl::AmbisonicPanner, csl::SimplePanner, and csl::SimplePanner.
Definition at line 41 of file SpatialPanner.cpp.
References csl::SpatialPanner::cache(), csl::SpatialPanner::mCache, and csl::SpatialPanner::mSources.
Referenced by csl::Spatializer::addSource(), main(), and csl::Spatializer::setPanningMode().
void SpatialPanner::removeSource (SpatialSource & s) virtual inherited
Remove a Sound Source.
Reimplemented in csl::AmbisonicPanner, csl::SimplePanner, and csl::SimplePanner.
Definition at line 56 of file SpatialPanner.cpp.
References csl::logMsg(), csl::SpatialPanner::mCache, and csl::SpatialPanner::mSources.
Referenced by csl::Spatializer::removeSource().
void SpatialPanner::update (void * arg) virtual inherited
Called when the speaker layout changes.
Called when the speaker layout changes, so panners update their data. This method is implemented only by the Panner class, and depending on the message sent, it calls the appropriate method implemented by subclasses. For example, when the speaker layout changes, the method calls "speakerLayoutChanged()", which should be implemented by subclasses interested to react to such change.
Implements csl::Observer.
Definition at line 83 of file SpatialPanner.cpp.
References csl::SpeakerLayout::defaultSpeakerLayout(), csl::SpatialPanner::mSpeakerLayout, csl::SpatialPanner::setSpeakerLayout(), and csl::SpatialPanner::speakerLayoutChanged().
unsigned csl::UnitGenerator::frameRate () inline inherited
Definition at line 249 of file CSL_Core.h.
References csl::UnitGenerator::mFrameRate.
Referenced by csl::CASoundFile::dump(), csl::Abst_SoundFile::dump(), and csl::SoundCue::dump().
void csl::UnitGenerator::setFrameRate (unsigned rate) inline inherited
get/set the receiver's frame rate
Definition at line 250 of file CSL_Core.h.
References csl::UnitGenerator::mFrameRate.
virtual unsigned csl::UnitGenerator::numChannels () inline virtual inherited
Reimplemented in csl::Splitter, and csl::Stereoverb.
Definition at line 252 of file CSL_Core.h.
References csl::UnitGenerator::mNumChannels.
Referenced by csl::AmbisonicMixer::addInput(), csl::BlockResizer::BlockResizer(), csl::Port::checkBuffer(), csl::Effect::Effect(), csl::AmbisonicRotator::initialize(), csl::AmbisonicDecoder::initialize(), csl::Mixer::nextBuffer(), csl::Convolver2::setIRFile(), csl::Convolver::setIRFile(), and csl::SpatialSource::SpatialSource().
void csl::UnitGenerator::setNumChannels (unsigned ch) inline inherited
get/set the receiver's number of outputs
Definition at line 253 of file CSL_Core.h.
References csl::UnitGenerator::mNumChannels.
Referenced by csl::BinauralPanner::BinauralPanner(), csl::Spatializer::Spatializer(), csl::VBAP::speakerLayoutChanged(), and csl::VBAP::VBAP().
BufferCopyPolicy csl::UnitGenerator::copyPolicy () inline inherited
Definition at line 255 of file CSL_Core.h.
References csl::UnitGenerator::mCopyPolicy.
void csl::UnitGenerator::setCopyPolicy (BufferCopyPolicy ch) inline inherited
get/set the receiver's buffer copy policy
Definition at line 256 of file CSL_Core.h.
References csl::UnitGenerator::mCopyPolicy.
Referenced by csl::AmbisonicPanner::AmbisonicPanner(), csl::BinauralPanner::BinauralPanner(), csl::AmbisonicUnitGenerator::initOrder(), csl::Noise::Noise(), csl::PinkNoise::PinkNoise(), csl::Spatializer::Spatializer(), and csl::VBAP::VBAP().
virtual bool csl::UnitGenerator::isFixed () inline virtual inherited
query whether I'm fixed (StaticVariable overrides this)
Reimplemented in csl::StaticVariable, and csl::BinaryOp.
Definition at line 271 of file CSL_Core.h.
virtual bool csl::UnitGenerator::isActive () inline virtual inherited
query whether I'm currently active (Envelopes can go inactive)
Reimplemented in csl::Joiner, csl::Effect, csl::RandEnvelope, csl::SoundCue, csl::Abst_SoundFile, csl::Stereoverb, csl::Envelope, csl::Instrument, csl::Mixer, and csl::KarplusString.
Definition at line 273 of file CSL_Core.h.
Referenced by csl::Instrument::isActive(), csl::Port::isActive(), csl::Mixer::nextBuffer(), csl::BinauralPanner::nextBuffer(), csl::AmbisonicMixer::nextBuffer(), and csl::VBAP::nextBuffer().
void UnitGenerator::addOutput (UnitGenerator * ugen) inherited
add to or return the UGen vector of outputs
Definition at line 670 of file CSL_Core.cpp.
References csl::Buffer::allocateBuffers(), csl::CGestalt::blockSize(), csl::UnitGenerator::mNumOutputs, csl::UnitGenerator::mOutputCache, and csl::UnitGenerator::mOutputs.
Referenced by csl::Mixer::addInput(), csl::Controllable::addInput(), csl::AmbisonicRotator::initialize(), csl::AmbisonicDecoder::initialize(), csl::AmbisonicEncoder::setInput(), and csl::IO::setRoot().
void UnitGenerator::removeOutput (UnitGenerator * ugen) inherited
Definition at line 680 of file CSL_Core.cpp.
References csl::UnitGenerator::mNumOutputs, and csl::UnitGenerator::mOutputs.
Referenced by csl::IO::clearRoot(), csl::AmbisonicEncoder::setInput(), csl::AmbisonicDecoder::~AmbisonicDecoder(), and csl::AmbisonicRotator::~AmbisonicRotator().
UGenVector csl::UnitGenerator::outputs () inline inherited
Definition at line 277 of file CSL_Core.h.
References csl::UnitGenerator::mOutputs.
virtual unsigned csl::UnitGenerator::numOutputs () inline virtual inherited
Definition at line 278 of file CSL_Core.h.
References csl::UnitGenerator::mNumOutputs.
bool UnitGenerator::checkFanOut (Buffer & outputBuffer) throw (CException) inherited
check for fan-out and copy previous buffer; return true if fanning out
Definition at line 699 of file CSL_Core.cpp.
void UnitGenerator::handleFanOut (Buffer & outputBuffer) throw (CException) inherited
Definition at line 713 of file CSL_Core.cpp.
References csl_max.
virtual void csl::UnitGenerator::setValue (sample theValue) inline virtual inherited
set/get the value (not allowed in the abstract, useful for static values)
Reimplemented in csl::DynamicVariable, and csl::StaticVariable.
Definition at line 284 of file CSL_Core.h.
virtual sample csl::UnitGenerator::value () inline virtual inherited
Reimplemented in csl::StaticVariable.
Definition at line 285 of file CSL_Core.h.
virtual void csl::UnitGenerator::trigger (void) inline virtual inherited
Reimplemented in csl::Joiner, csl::Effect, csl::RandEnvelope, csl::SoundCue, csl::Abst_SoundFile, csl::Envelope, csl::LineSegment, and csl::KarplusString.
Definition at line 288 of file CSL_Core.h.
Referenced by csl::Instrument::play(), csl::Instrument::release(), and csl::Port::trigger().
void UnitGenerator::zeroBuffer (Buffer & outputBuffer, unsigned outBufNum) protected inherited
utility method to zero out an outputBuffer
Definition at line 663 of file CSL_Core.cpp.
References csl::Buffer::buffer(), and csl::Buffer::mMonoBufferByteSize.
void Model::attachObserver (Observer * o) inherited
(possibly notify obersvers on my death)
register/remove observers
Definition at line 502 of file CGestalt.cpp.
References csl::logMsg(), csl::Observer::mKey, and csl::Observer::mPeriod.
Referenced by csl::SpatialPanner::setSpeakerLayout().
void Model::detachObserver (Observer * o) inherited
Definition at line 518 of file CGestalt.cpp.
References csl::logMsg().
Referenced by csl::SpatialPanner::setSpeakerLayout(), and csl::SpatialPanner::~SpatialPanner().
void Model::changed (void * argument) inherited
this is what I send to myself to notify my observers; It's not overridden in general. It results in the observers receiving update() calls < override evaluate to filter updates to the observer map
Definition at line 540 of file CGestalt.cpp.
References csl::logMsg().
Referenced by csl::SpeakerLayout::addSpeaker(), csl::MIDIIn::handleIncomingMidiMessage(), and csl::SpeakerLayout::setDefaultSpeakerLayout().
virtual int csl::Model::evaluate (void * argument) inline virtual inherited
Reimplemented in csl::MIDIIn.
Definition at line 270 of file CGestalt.h.
Member Data Documentation
VBAPMode csl::VBAP::mMode protected inherited
Prints useful information about this VBAP instance.
Represents the dimensionality of the panner, either 2 or 3. 2D meaning horizontal panning only.
Definition at line 73 of file VBAP.h.
Referenced by csl::VBAP::VBAP().
SpeakerSetLayout* csl::VBAP::mSpeakerSetLayout protected inherited
A reference to the layout that contains the speaker pairs or triplets.
Definition at line 77 of file VBAP.h.
Referenced by csl::VBAP::speakerLayoutChanged(), csl::VBAP::VBAP(), and csl::VBAP::~VBAP().
UGenVector csl::SpatialPanner::mSources protected inherited
SpatialSource... refers to its input UGen, but with the knowledge of its position within a space.
Vector of pointers to the inputs
Definition at line 49 of file SpatialPanner.h.
Referenced by csl::SimplePanner::addSource(), csl::SpatialPanner::addSource(), csl::SpatialPanner::numSources(), csl::SimplePanner::removeSource(), and csl::SpatialPanner::removeSource().
vector<void *> csl::SpatialPanner::mCache protected inherited
Vector of pointers to the prior I/O data.
Definition at line 50 of file SpatialPanner.h.
Referenced by csl::SpatialPanner::addSource(), and csl::SpatialPanner::removeSource().
SpeakerLayout* csl::SpatialPanner::mSpeakerLayout protected inherited
If null, it will use the default layout by calling SpeakerLayout::defaultSpeakerLayout();.
Definition at line 52 of file SpatialPanner.h.
Referenced by csl::SpatialPanner::setSpeakerLayout(), csl::VBAP::speakerLayoutChanged(), csl::SpatialPanner::update(), csl::VBAP::VBAP(), csl::SpatialPanner::~SpatialPanner(), ~StereoPanner(), and csl::SurroundPanner::~SurroundPanner().
Buffer csl::SpatialPanner::mTempBuffer protected inherited
Buffer used to temporarily hold input source data.
Definition at line 54 of file SpatialPanner.h.
Referenced by csl::SpatialPanner::SpatialPanner(), and csl::SpatialPanner::~SpatialPanner().
unsigned csl::UnitGenerator::mFrameRate protected inherited
trigger ignored here
the frame rate – initialized to be the default by the constructor
Definition at line 288 of file CSL_Core.h.
Referenced by csl::Abst_SoundFile::convertRate(), csl::Lorenz::dump(), csl::Abst_SoundFile::durationInSecs(), csl::UnitGenerator::frameRate(), csl::Filter::init(), csl::CASoundFile::initFromSndfile(), csl::JSoundFile::initFromSndfile(), csl::LSoundFile::initFromSndfile(), csl::RandEnvelope::nextSegment(), csl::SquareBL::nextWaveInto(), csl::SumOfSines::nextWaveInto(), csl::DelayLine::setDelayTime(), csl::UnitGenerator::setFrameRate(), csl::Abst_SoundFile::setStartSec(), csl::Abst_SoundFile::setStopSec(), csl::Butter::setupCoeffs(), csl::Formant::setupCoeffs(), csl::Notch::setupCoeffs(), and csl::Moog::setupCoeffs().
unsigned csl::UnitGenerator::mNumChannels protected inherited
my "expected" number of output channels
Definition at line 292 of file CSL_Core.h.
Referenced by csl::AmbisonicMixer::addInput(), csl::Mixer::allocateOpBuffer(), csl::AmbisonicDecoder::asProjection(), csl::AmbisonicDecoder::asPseudoInverse(), csl::BlockResizer::BlockResizer(), csl::Abst_SoundFile::channels(), csl::Abst_SoundFile::checkBuffer(), csl::FMInstrument::FMInstrument(), csl::GrainPlayer::GrainPlayer(), csl::AdditiveInstrument::init(), csl::JSoundFile::initFromSndfile(), csl::LSoundFile::initFromSndfile(), csl::AmbisonicMixer::initialize(), csl::SndFileInstrument::initialize(), csl::AmbisonicRotator::initialize(), csl::AmbisonicEncoder::initialize(), csl::AmbisonicDecoder::initialize(), csl::AmbisonicUnitGenerator::initOrder(), csl::RemoteStream::initPacket(), csl::Joiner::isActive(), csl::Joiner::Joiner(), csl::AmbisonicDecoder::makeInPhase(), csl::AmbisonicDecoder::makeMaxRE(), csl::Abst_SoundFile::mergeToMono(), csl::Mixer::Mixer(), csl::UnitGenerator::numChannels(), csl::Panner::Panner(), csl::CASoundFile::readBufferFromFile(), csl::JSoundFile::readBufferFromFile(), csl::LSoundFile::readBufferFromFile(), csl::RemoteStream::RemoteStream(), csl::UnitGenerator::setNumChannels(), csl::WavetableOscillator::setWaveform(), csl::Joiner::trigger(), and csl::AmbisonicRotator::~AmbisonicRotator().
BufferCopyPolicy csl::UnitGenerator::mCopyPolicy protected inherited
the policy I use if asked for more or fewer channels
Definition at line 293 of file CSL_Core.h.
Referenced by csl::UnitGenerator::copyPolicy(), and csl::UnitGenerator::setCopyPolicy().
UGenVector csl::UnitGenerator::mOutputs protected inherited
the vector of my output UGens
Definition at line 294 of file CSL_Core.h.
Referenced by csl::UnitGenerator::addOutput(), csl::UnitGenerator::dump(), csl::UnitGenerator::outputs(), and csl::UnitGenerator::removeOutput().
unsigned csl::UnitGenerator::mNumOutputs protected inherited
the number of outputs
Definition at line 295 of file CSL_Core.h.
Referenced by csl::UnitGenerator::addOutput(), csl::UnitGenerator::numOutputs(), and csl::UnitGenerator::removeOutput().
Buffer* csl::UnitGenerator::mOutputCache protected inherited
my past output ring buffer (only used in case of fan-out)
Definition at line 296 of file CSL_Core.h.
Referenced by csl::UnitGenerator::addOutput().
unsigned csl::UnitGenerator::mSequence protected inherited
the highest-seen buffer seq number
Definition at line 297 of file CSL_Core.h.
float csl::Observer::mPeriod inherited
virtual destructor (don't notify or delete observers in this version)
max update rate
Definition at line 299 of file CGestalt.h.
Referenced by csl::Model::attachObserver(), and csl::Observer::Observer().
int csl::Observer::mKey inherited
key selector (e.g., MIDI chan) I receive update() mesages from my model;
Definition at line 302 of file CGestalt.h.
Referenced by csl::Model::attachObserver(), and csl::Observer::Observer().
The documentation for this class was generated from the following files:
/Content/Code/CSL/CSL/Spatializers/VBAP/VBAP.h
/Content/Code/CSL/CSL/Spatializers/VBAP/VBAP.cpp