CSL: csl::SynchPthread Class Reference
csl::SynchPthread Class Reference
PThread version of Sync.
#include <ThreadUtilities.h>
Public Member Functions
SynchPthread ()
~SynchPthread ()
int lock ()
int unlock ()
int condWait ()
int condSignal ()
Static Public Member Functions
static Synch * MakeSynch ()
Factory method Utilities.
Public Attributes
pthread_mutex_t mMutex
pthread_cond_t mCond
Detailed Description
PThread version of Sync.
Definition at line 76 of file ThreadUtilities.h.
Constructor & Destructor Documentation
SynchPthread::SynchPthread ()
Definition at line 60 of file ThreadUtilities.cpp.
References mCond, and mMutex.
SynchPthread::~SynchPthread ()
Definition at line 65 of file ThreadUtilities.cpp.
References mCond, and mMutex.
Member Function Documentation
int SynchPthread::lock () virtual
Implements csl::Synch.
Definition at line 72 of file ThreadUtilities.cpp.
References mMutex.
Referenced by Controller::get_data(), Controller::get_position(), and Controller::set_data().
int SynchPthread::unlock () virtual
Implements csl::Synch.
Definition at line 74 of file ThreadUtilities.cpp.
References mMutex.
Referenced by Controller::get_data(), Controller::get_position(), and Controller::set_data().
int SynchPthread::condWait () virtual
Implements csl::Synch.
Definition at line 76 of file ThreadUtilities.cpp.
References mCond, and mMutex.
int SynchPthread::condSignal () virtual
Implements csl::Synch.
Definition at line 78 of file ThreadUtilities.cpp.
References mCond.
Synch * Synch::MakeSynch () static inherited
Factory method Utilities.
Definition at line 54 of file ThreadUtilities.cpp.
Referenced by csl::NullIO::NullIO(), and csl::StdIO::StdIO().
Member Data Documentation
pthread_mutex_t csl::SynchPthread::mMutex
Definition at line 81 of file ThreadUtilities.h.
Referenced by condWait(), lock(), SynchPthread(), unlock(), and ~SynchPthread().
pthread_cond_t csl::SynchPthread::mCond
Definition at line 82 of file ThreadUtilities.h.
Referenced by condSignal(), condWait(), SynchPthread(), and ~SynchPthread().
The documentation for this class was generated from the following files:
/Content/Code/CSL/CSL/Utilities/ThreadUtilities.h
/Content/Code/CSL/CSL/Utilities/ThreadUtilities.cpp