CSL: csl::CASoundFile Class Reference
csl::CASoundFile Class Reference abstract
CoreAudio sound file.
#include <SoundFileCA.h>
Public Member Functions
CASoundFile (CFURLRef path, bool load=true)
CASoundFile (string path, int start=-1, int stop=-1, bool load=true)
CASoundFile (CASoundFile &otherSndFile)
Copy constructor – shares sample buffer.
~CASoundFile ()
SoundFileFormat format ()
get format
void dump ()
log snd file props < open file and get stats; read it if "load"
void openForRead (bool load=true) throw (CException)
void openForWrite (SoundFileFormat format=kSoundFileFormatAIFF, unsigned channels=1, unsigned rate=44100, unsigned bitDepth=16) throw (CException)
Open a file for write. Default values are some common format.
void openForReadWrite () throw (CException)
open r/w
void close ()
close file seek to some position
unsigned seekTo (int position, SeekPosition whence) throw (CException)
seek to some position relative to "whence"
void readBufferFromFile (unsigned numFrames)
read a buffer from the file (possibly all of it)
void writeBuffer (Buffer &inputBuffer) throw (CException)
write a buffer of data into the file
unsigned seekTo (int position) throw (CException)
read a buffer from the file (possibly all of it)
virtual void nextBuffer (Buffer &outB) throw (CException)
UGen operations are implemented here copy next buffer from file cache.
virtual void nextBuffer (Buffer &outputBuffer, unsigned outBufNum) throw (CException)
really compute the next buffer given an offset base channel; this is called by nextBuffer, possibly multiple times
virtual void writeBuffer (Buffer &inB, unsigned fromFrame, unsigned toFrame)=0 throw (CException)
virtual SampleBuffer buffer (unsigned bufNum)
unsigned channels () const
accessors
unsigned duration ()
float durationInSecs ()
number of frames in the sound file
unsigned sampleSize ()
get the bytes-per-sample
SoundFileMode mode ()
r/w mode
unsigned cacheSize ()
size in frames of cached portion
void mergeToMono ()
average all the channels to mono
virtual void setToEnd ()
set to end position
virtual void trigger ()
reset to start
virtual void freeBuffer ()
free the file cache
void convertRate (int fromRate, int toRate)
perform sample-rate conversion
bool isValid ()
answer if a valid file/buffer
bool isActive ()
answer if currently active
virtual bool isCached ()
answer if file is loaded into RAM
virtual bool isCached (unsigned samps)
answer if file has X samples in RAM
virtual void setPath (string path)
set file name path string
string path ()
file name
int startFrame ()
get/set start frame
void setStart (int val)
void setStartSec (float val)
void setStartRatio (float val)
int stopFrame ()
get/set stop frame
void setStop (int val)
void setStopSec (float val)
void setStopRatio (float val)
void setBase (int val)
unsigned int base ()
double playbackRate ()
playback rate (pitch ratio)
void setRate (UnitGenerator &frequency)
set the receiver's playback rate (pitch ratio)
void setRate (float frequency)
bool isLooping ()
get/set looping state
void setIsLooping (bool tLooping)
void setWaveform (Buffer &wave, bool freeBufs=true)
plug in waveforms set the interpolation flag
void setInterpolate (InterpolationPolicy whether)
unsigned frameRate ()
void setFrameRate (unsigned rate)
get/set the receiver's frame rate
virtual unsigned numChannels ()
void setNumChannels (unsigned ch)
get/set the receiver's number of outputs
BufferCopyPolicy copyPolicy ()
void setCopyPolicy (BufferCopyPolicy ch)
get/set the receiver's buffer copy policy
virtual bool isFixed ()
query whether I'm fixed (StaticVariable overrides this)
void addOutput (UnitGenerator *ugen)
add to or return the UGen vector of outputs
void removeOutput (UnitGenerator *ugen)
UGenVector outputs ()
virtual unsigned numOutputs ()
bool checkFanOut (Buffer &outputBuffer) throw (CException)
check for fan-out and copy previous buffer; return true if fanning out
void handleFanOut (Buffer &outputBuffer) throw (CException)
virtual void setValue (sample theValue)
set/get the value (not allowed in the abstract, useful for static values)
virtual sample value ()
void attachObserver (Observer *)
(possibly notify obersvers on my death)
void detachObserver (Observer *)
void changed (void *argument)
this is what I send to myself to notify my observers; It's not overridden in general. It results in the observers receiving update() calls < override evaluate to filter updates to the observer map
virtual int evaluate (void *argument)
void setFrequency (UnitGenerator &frequency)
Setter accessors.
void setFrequency (float frequency)
set frequency
void setPhase (float phase)
Port * getPort (CSL_MAP_KEY name)
void setScale (UnitGenerator &scale)
set the receiver's scale member to a UGen or a float
void setScale (float scale)
void setOffset (UnitGenerator &offset)
set the receiver's offset member to a UGen or a float
void setOffset (float offset)
void isScaled ()
answer whether scale = 1 & offset = 0
virtual void reset () throw (CException)
reset-to-zero
Static Public Member Functions
static bool isSndfileName (const char *path)
Answer whether the given name looks like a snd file.
static SoundFileFormat sndfileNameType (const char *path)
Answer the snd file type.
static const char * mimeType (const char *path)
Answer the MIME type based on the file name.
Public Attributes
SoundFileMetadata * mProperties
the ID3 tags properties
InterpolationPolicy mInterpolate
whether/how I should interpolate between samples
Buffer mWavetable
the stored wave form
unsigned mCurrentFrame
where I currently am in the buffer
double mActualFrame
where I actually am in the buffer
Protected Member Functions
void initFromSndfile ()
read SF header
virtual void writeBuffer (Buffer &inputBuffer, unsigned bufNum) throw (CException)
write to the receiver
void checkBuffer (unsigned numFrames)
allocate buffer lazily
void checkBuffer (unsigned numChans, unsigned numFrames)
bool readTags () throw (CException)
read the ID3 or other tags. Returns true if able to read them.
void fillSine ()
fill the shared wavetable with 1 cycle of a sine wave
void zeroBuffer (Buffer &outputBuffer, unsigned outBufNum)
utility method to zero out an outputBuffer
void addInput (CSL_MAP_KEY name, UnitGenerator &ugen)
Plug in a unit generator to the named input slot.
void addInput (CSL_MAP_KEY name, float value)
Plug in a float to the named input slot.
void pullInput (Port *thePort, unsigned numFrames) throw (CException)
method to read the control values (in case they're dynamic). this sends nextBuffer() to the input.
void pullInput (Port *thePort, Buffer &theBuffer) throw (CException)
Protected Attributes
CFURLRef mURL
the full URL of the file
AudioFileID mSoundID
the CS audio file ID
bool mBigEndian
flag for endian-ness of sound file (varies byformat)
string mPath
file name
SoundFileMode mMode
r/w mode
SoundFileFormat mFormat
sf format
bool mIsValid
is my file valid?
bool mIsLooping
am i looping start-stop?
int mStart
int mStop
starting/ending frames (or -1 if not used)
double mRate
sample rate ratio
unsigned mNumFrames
sample frames
unsigned mBytesPerSample
the # of bytes per sample
unsigned mBase
starting frame in file of buffer
unsigned mFrameRate
trigger ignored here
unsigned mNumChannels
my "expected" number of output channels
BufferCopyPolicy mCopyPolicy
the policy I use if asked for more or fewer channels
UGenVector mOutputs
the vector of my output UGens
unsigned mNumOutputs
the number of outputs
Buffer * mOutputCache
my past output ring buffer (only used in case of fan-out)
unsigned mSequence
the highest-seen buffer seq number
sample mPhase
set phase
PortMap mInputs
the map of my inputs or controls (used by the mix-in classes)
Detailed Description
CoreAudio sound file.
Definition at line 20 of file SoundFileCA.h.
Constructor & Destructor Documentation
CASoundFile::CASoundFile (CFURLRef path, bool load = true)
Definition at line 64 of file SoundFileCA.cpp.
References CSL_NAME_LEN, csl::Abst_SoundFile::mPath, openForRead(), and csl::Abst_SoundFile::setToEnd().
CASoundFile::CASoundFile (string path, int start = -1, int stop = -1, bool load = true)
Definition at line 41 of file SoundFileCA.cpp.
References mURL, openForRead(), and csl::Abst_SoundFile::setToEnd().
CASoundFile::CASoundFile (CASoundFile & otherSndFile)
Copy constructor – shares sample buffer.
Definition at line 60 of file SoundFileCA.cpp.
CASoundFile::~CASoundFile ()
Definition at line 81 of file SoundFileCA.cpp.
Member Function Documentation
SoundFileFormat CASoundFile::format ()
get format
Definition at line 85 of file SoundFileCA.cpp.
References kSoundFileFormatAIFF.
void CASoundFile::dump (void) virtual
log snd file props < open file and get stats; read it if "load"
Reimplemented from csl::Abst_SoundFile.
Definition at line 323 of file SoundFileCA.cpp.
References csl::Abst_SoundFile::channels(), csl::Abst_SoundFile::durationInSecs(), csl::UnitGenerator::frameRate(), csl::logMsg(), mBigEndian, and csl::Abst_SoundFile::path().
void CASoundFile::openForRead (bool load = true) throw (CException) virtual
Implements csl::Abst_SoundFile.
Definition at line 107 of file SoundFileCA.cpp.
References csl::kLogError, kSoundFileRead, csl::logMsg(), csl::CGestalt::maxSndFileFrames(), and mFrameRate.
Referenced by CASoundFile().
void CASoundFile::openForWrite (SoundFileFormat format = kSoundFileFormatAIFF, unsigned channels = 1, unsigned rate = 44100, unsigned bitDepth = 16) throw (CException) virtual
Open a file for write. Default values are some common format.
Implements csl::Abst_SoundFile.
Definition at line 167 of file SoundFileCA.cpp.
References csl::logMsg().
void csl::CASoundFile::openForReadWrite () throw (CException)
open r/w
void CASoundFile::close () virtual
close file seek to some position
Implements csl::Abst_SoundFile.
Definition at line 173 of file SoundFileCA.cpp.
References csl::Abst_SoundFile::freeBuffer().
unsigned CASoundFile::seekTo (int position, SeekPosition whence) throw (CException) virtual
seek to some position relative to "whence"
Implements csl::Abst_SoundFile.
Definition at line 293 of file SoundFileCA.cpp.
References csl::kPositionCurrent, csl::kPositionEnd, csl::kPositionStart, and csl::logMsg().
Referenced by initFromSndfile(), and readBufferFromFile().
void CASoundFile::readBufferFromFile (unsigned numFrames) virtual
read a buffer from the file (possibly all of it)
Implements csl::Abst_SoundFile.
Definition at line 179 of file SoundFileCA.cpp.
References csl::Buffer::buffer(), csl::Abst_SoundFile::checkBuffer(), CONVERT_16_BIT, CONVERT_24_BIT, csl::Interleaver::deinterleave(), csl::kPositionStart, mBigEndian, csl::Abst_SoundFile::mBytesPerSample, csl::Seekable::mCurrentFrame, csl::Abst_SoundFile::mIsLooping, csl::UnitGenerator::mNumChannels, csl::Abst_SoundFile::mPath, mSoundID, csl::Abst_SoundFile::mStop, csl::WavetableOscillator::mWavetable, and seekTo().
void CASoundFile::writeBuffer (Buffer & inputBuffer) throw (CException) virtual
write a buffer of data into the file
Implements csl::Abst_SoundFile.
Definition at line 316 of file SoundFileCA.cpp.
References csl::logMsg().
void CASoundFile::initFromSndfile () protected virtual
read SF header
Implements csl::Abst_SoundFile.
Definition at line 91 of file SoundFileCA.cpp.
References csl::kPositionStart, csl::UnitGenerator::mFrameRate, csl::Abst_SoundFile::mIsValid, csl::Abst_SoundFile::mNumFrames, csl::Abst_SoundFile::mStart, csl::Abst_SoundFile::mStop, and seekTo().
bool Abst_SoundFile::isSndfileName (const char * path) static inherited
Answer whether the given name looks like a snd file.
Answer the snd file type.
Definition at line 44 of file SoundFile.cpp.
References gSndFileExts.
SoundFileFormat Abst_SoundFile::sndfileNameType (const char * path) static inherited
Answer the snd file type.
Definition at line 60 of file SoundFile.cpp.
References kSoundFileFormatAIFF, kSoundFileFormatOther, kSoundFileFormatSND, and kSoundFileFormatWAV.
Referenced by csl::Abst_SoundFile::mimeType().
const char * Abst_SoundFile::mimeType (const char * path) static inherited
Answer the MIME type based on the file name.
open file and get stats; read it if "load"
Definition at line 98 of file SoundFile.cpp.
References kSoundFileFormatAIFF, kSoundFileFormatWAV, and csl::Abst_SoundFile::sndfileNameType().
unsigned csl::Abst_SoundFile::seekTo (int position) throw (CException) inline inherited
read a buffer from the file (possibly all of it)
Definition at line 122 of file SoundFile.h.
References csl::kPositionStart, and csl::Abst_SoundFile::seekTo().
Referenced by csl::Abst_SoundFile::seekTo().
void Abst_SoundFile::nextBuffer (Buffer & outB) throw (CException) virtual inherited
UGen operations are implemented here copy next buffer from file cache.
Reimplemented from csl::UnitGenerator.
Reimplemented in csl::LSoundFile.
Definition at line 382 of file SoundFile.cpp.
References csl_min, DECLARE_SCALABLE_CONTROLS, LOAD_SCALABLE_CONTROLS, csl::WavetableOscillator::nextBuffer(), and UPDATE_SCALABLE_CONTROLS.
void WavetableOscillator::nextBuffer (Buffer & outputBuffer, unsigned outBufNum) throw (CException) virtual inherited
really compute the next buffer given an offset base channel; this is called by nextBuffer, possibly multiple times
Reimplemented from csl::UnitGenerator.
Reimplemented in csl::CompOrCacheOscillator.
Definition at line 129 of file Oscillator.cpp.
References DECLARE_PHASED_CONTROLS, DECLARE_SCALABLE_CONTROLS, csl::kLinear, csl::kTruncate, LOAD_PHASED_CONTROLS, LOAD_SCALABLE_CONTROLS, csl::logMsg(), mFrameRate, UPDATE_PHASED_CONTROLS, and UPDATE_SCALABLE_CONTROLS.
Referenced by csl::LSoundFile::nextBuffer(), csl::CompOrCacheOscillator::nextBuffer(), and csl::Abst_SoundFile::nextBuffer().
virtual void csl::Abst_SoundFile::writeBuffer (Buffer & inB, unsigned fromFrame, unsigned toFrame) throw (CException) pure virtual inherited
Implemented in csl::LSoundFile, and csl::JSoundFile.
void Writeable::writeBuffer (Buffer & inputBuffer, unsigned bufNum) throw (CException) protected virtual inherited
write to the receiver
Reimplemented in csl::BufferStream, and csl::RingBuffer.
Definition at line 1265 of file CSL_Core.cpp.
virtual SampleBuffer csl::Abst_SoundFile::buffer (unsigned bufNum) inline virtual inherited
Definition at line 134 of file SoundFile.h.
References csl::Buffer::buffer(), and csl::WavetableOscillator::mWavetable.
Referenced by load_filter_data(), csl::Convolver2::setIRFile(), and csl::Convolver::setIRFile().
unsigned Abst_SoundFile::channels () const inherited
accessors
chans
Definition at line 157 of file SoundFile.cpp.
References csl::Abst_SoundFile::mIsValid, and csl::UnitGenerator::mNumChannels.
Referenced by csl::SoundCue::channels(), dump(), csl::Abst_SoundFile::dump(), and csl::SoundCue::dump().
unsigned csl::Abst_SoundFile::duration () inline virtual inherited
Reimplemented from csl::Seekable.
Definition at line 138 of file SoundFile.h.
References csl::Abst_SoundFile::mNumFrames.
Referenced by csl::Abst_SoundFile::isCached(), csl::Abst_SoundFile::setStart(), csl::Abst_SoundFile::setStartRatio(), csl::Abst_SoundFile::setStop(), and csl::Abst_SoundFile::setStopRatio().
float Abst_SoundFile::durationInSecs () inherited
number of frames in the sound file
actual duration of the selected portion in sec
Definition at line 161 of file SoundFile.cpp.
References csl::UnitGenerator::mFrameRate, csl::Abst_SoundFile::mIsValid, csl::Abst_SoundFile::mStart, and csl::Abst_SoundFile::mStop.
Referenced by dump(), and csl::Abst_SoundFile::dump().
unsigned csl::Abst_SoundFile::sampleSize () inline inherited
get the bytes-per-sample
Definition at line 141 of file SoundFile.h.
References csl::Abst_SoundFile::mBytesPerSample.
SoundFileMode csl::Abst_SoundFile::mode () inline inherited
r/w mode
Definition at line 142 of file SoundFile.h.
References csl::Abst_SoundFile::mMode.
unsigned csl::Abst_SoundFile::cacheSize () inline inherited
size in frames of cached portion
Definition at line 143 of file SoundFile.h.
References csl::Buffer::mNumAlloc, and csl::WavetableOscillator::mWavetable.
void Abst_SoundFile::mergeToMono () inherited
average all the channels to mono
Definition at line 208 of file SoundFile.cpp.
References csl::Buffer::allocateBuffers(), csl::Buffer::buffer(), csl::Buffer::copyFrom(), csl::logMsg(), csl::Buffer::mAreBuffersAllocated, csl::Buffer::mDidIAllocateBuffers, csl::UnitGenerator::mNumChannels, csl::Buffer::mNumFrames, csl::WavetableOscillator::mWavetable, and csl::Buffer::setBuffer().
void Abst_SoundFile::setToEnd () virtual inherited
set to end position
Definition at line 334 of file SoundFile.cpp.
References csl::Seekable::mCurrentFrame, and csl::Abst_SoundFile::mStop.
Referenced by CASoundFile(), and csl::JSoundFile::JSoundFile().
void Abst_SoundFile::trigger (void) virtual inherited
reset to start
Reimplemented from csl::UnitGenerator.
Definition at line 322 of file SoundFile.cpp.
References csl::Seekable::mCurrentFrame, csl::Abst_SoundFile::mStart, and csl::Abst_SoundFile::seekTo().
Referenced by test_convolution().
void Abst_SoundFile::freeBuffer () virtual inherited
free the file cache
Definition at line 165 of file SoundFile.cpp.
References csl::Buffer::freeBuffers(), csl::Buffer::mAreBuffersAllocated, and csl::WavetableOscillator::mWavetable.
Referenced by close(), csl::JSoundFile::close(), csl::LSoundFile::close(), and csl::LSoundFile::~LSoundFile().
void Abst_SoundFile::convertRate (int fromRate, int toRate) inherited
perform sample-rate conversion
Definition at line 236 of file SoundFile.cpp.
References csl::Buffer::convertRate(), csl::UnitGenerator::mFrameRate, csl::Buffer::mNumFrames, csl::Abst_SoundFile::mNumFrames, and csl::WavetableOscillator::mWavetable.
bool csl::Abst_SoundFile::isValid () inline inherited
answer if a valid file/buffer
Definition at line 152 of file SoundFile.h.
References csl::Abst_SoundFile::mIsValid.
bool Abst_SoundFile::isActive () virtual inherited
answer if currently active
Reimplemented from csl::UnitGenerator.
Definition at line 303 of file SoundFile.cpp.
References csl::Seekable::mCurrentFrame, csl::Abst_SoundFile::mIsValid, and csl::Abst_SoundFile::mStop.
bool Abst_SoundFile::isCached () virtual inherited
answer if file is loaded into RAM
answer if file has X samples in RAM
Reimplemented in csl::LSoundFile.
Definition at line 309 of file SoundFile.cpp.
References csl::Abst_SoundFile::duration(), csl::Buffer::mNumFrames, and csl::WavetableOscillator::mWavetable.
Referenced by csl::Abst_SoundFile::Abst_SoundFile().
bool Abst_SoundFile::isCached (unsigned samps) virtual inherited
answer if file has X samples in RAM
Reimplemented in csl::LSoundFile.
Definition at line 315 of file SoundFile.cpp.
References csl::Seekable::mCurrentFrame, csl::Buffer::mNumFrames, and csl::WavetableOscillator::mWavetable.
void Abst_SoundFile::setPath (string path) virtual inherited
set file name path string
Definition at line 153 of file SoundFile.cpp.
References csl::Abst_SoundFile::mPath.
Referenced by csl::Abst_SoundFile::Abst_SoundFile().
string csl::Abst_SoundFile::path () inline inherited
file name
Definition at line 158 of file SoundFile.h.
References csl::Abst_SoundFile::mPath.
Referenced by csl::Abst_SoundFile::Abst_SoundFile(), dump(), and csl::Abst_SoundFile::dump().
int csl::Abst_SoundFile::startFrame () inline inherited
get/set start frame
Definition at line 161 of file SoundFile.h.
References csl::Abst_SoundFile::mStart.
void Abst_SoundFile::setStart (int val) inherited
Definition at line 248 of file SoundFile.cpp.
References csl::Abst_SoundFile::duration(), csl::Abst_SoundFile::mIsValid, csl::Abst_SoundFile::mStart, and csl::Abst_SoundFile::seekTo().
Referenced by csl::Abst_SoundFile::setStartRatio(), and csl::Abst_SoundFile::setStartSec().
void Abst_SoundFile::setStartSec (float val) inherited
Definition at line 258 of file SoundFile.cpp.
References csl::UnitGenerator::mFrameRate, and csl::Abst_SoundFile::setStart().
void Abst_SoundFile::setStartRatio (float val) inherited
Definition at line 262 of file SoundFile.cpp.
References csl::Abst_SoundFile::duration(), and csl::Abst_SoundFile::setStart().
int csl::Abst_SoundFile::stopFrame () inline inherited
get/set stop frame
Definition at line 165 of file SoundFile.h.
References csl::Abst_SoundFile::mStop.
void Abst_SoundFile::setStop (int val) inherited
Definition at line 266 of file SoundFile.cpp.
References csl::Abst_SoundFile::duration(), and csl::Abst_SoundFile::mStop.
Referenced by csl::Abst_SoundFile::setStopRatio(), and csl::Abst_SoundFile::setStopSec().
void Abst_SoundFile::setStopSec (float val) inherited
Definition at line 275 of file SoundFile.cpp.
References csl::UnitGenerator::mFrameRate, and csl::Abst_SoundFile::setStop().
void Abst_SoundFile::setStopRatio (float val) inherited
Definition at line 279 of file SoundFile.cpp.
References csl::Abst_SoundFile::duration(), and csl::Abst_SoundFile::setStop().
void Abst_SoundFile::setBase (int val) inherited
Definition at line 283 of file SoundFile.cpp.
References csl::Abst_SoundFile::mBase.
unsigned int csl::Abst_SoundFile::base () inline inherited
Definition at line 170 of file SoundFile.h.
References csl::Abst_SoundFile::mBase.
double csl::Abst_SoundFile::playbackRate () inline inherited
playback rate (pitch ratio)
Definition at line 172 of file SoundFile.h.
References csl::Abst_SoundFile::mRate.
void Abst_SoundFile::setRate (UnitGenerator & frequency) inherited
set the receiver's playback rate (pitch ratio)
Definition at line 289 of file SoundFile.cpp.
References csl::Controllable::addInput(), CSL_RATE, and csl::Controllable::mInputs.
void Abst_SoundFile::setRate (float frequency) inherited
Definition at line 296 of file SoundFile.cpp.
References csl::logMsg(), and csl::Abst_SoundFile::mRate.
bool csl::Abst_SoundFile::isLooping () inline inherited
get/set looping state
Definition at line 176 of file SoundFile.h.
References csl::Abst_SoundFile::mIsLooping.
void csl::Abst_SoundFile::setIsLooping (bool tLooping) inline inherited
Definition at line 177 of file SoundFile.h.
References csl::Abst_SoundFile::mIsLooping.
void Abst_SoundFile::checkBuffer (unsigned numFrames) protected inherited
allocate buffer lazily
Definition at line 172 of file SoundFile.cpp.
References csl::Buffer::allocateBuffers(), csl::Buffer::freeBuffers(), csl::logMsg(), csl::Buffer::mAreBuffersAllocated, csl::UnitGenerator::mNumChannels, csl::Buffer::mNumFrames, csl::WavetableOscillator::mWavetable, and csl::Buffer::setSize().
Referenced by readBufferFromFile(), csl::JSoundFile::readBufferFromFile(), and csl::LSoundFile::readBufferFromFile().
void Abst_SoundFile::checkBuffer (unsigned numChans, unsigned numFrames) protected inherited
Definition at line 191 of file SoundFile.cpp.
References csl::Buffer::allocateBuffers(), csl::Buffer::freeBuffers(), csl::logMsg(), csl::Buffer::mAreBuffersAllocated, csl::UnitGenerator::mNumChannels, csl::Buffer::mNumFrames, csl::WavetableOscillator::mWavetable, and csl::Buffer::setSize().
bool Abst_SoundFile::readTags () throw (CException) protected inherited
read the ID3 or other tags. Returns true if able to read them.
Definition at line 340 of file SoundFile.cpp.
References csl::SoundFileMetadata::mAlbum, csl::SoundFileMetadata::mArtist, csl::SoundFileMetadata::mBitRate, csl::SoundFileMetadata::mChannels, csl::SoundFileMetadata::mComment, csl::SoundFileMetadata::mGenre, csl::SoundFileMetadata::mLength, csl::Abst_SoundFile::mPath, csl::Abst_SoundFile::mProperties, csl::SoundFileMetadata::mSampleRate, csl::SoundFileMetadata::mTitle, csl::SoundFileMetadata::mTrack, and csl::SoundFileMetadata::mYear.
void WavetableOscillator::setWaveform (Buffer & wave, bool freeBufs = true) inherited
plug in waveforms set the interpolation flag
Definition at line 76 of file Oscillator.cpp.
References csl::Buffer::buffer(), csl::Buffer::buffers(), csl::Buffer::freeBuffers(), csl::Buffer::mAreBuffersAllocated, csl::Buffer::mAreBuffersZero, csl::Buffer::mDidIAllocateBuffers, csl::Buffer::mIsPopulated, csl::Buffer::mMonoBufferByteSize, csl::Buffer::mNumChannels, csl::UnitGenerator::mNumChannels, csl::Buffer::mNumFrames, csl::WavetableOscillator::mWavetable, csl::Buffer::setBuffer(), and csl::Buffer::setBuffers().
Referenced by csl::Abst_SoundFile::Abst_SoundFile(), and csl::WavetableOscillator::WavetableOscillator().
void csl::WavetableOscillator::setInterpolate (InterpolationPolicy whether) inline inherited
Definition at line 79 of file Oscillator.h.
References csl::WavetableOscillator::mInterpolate.
void WavetableOscillator::fillSine () protected inherited
fill the shared wavetable with 1 cycle of a sine wave
Definition at line 109 of file Oscillator.cpp.
References csl::Buffer::allocateBuffers(), csl::Buffer::buffer(), CSL_TWOPI, DEFAULT_WTABLE_SIZE, csl::Buffer::mAreBuffersAllocated, csl::Buffer::mDidIAllocateBuffers, csl::WavetableOscillator::mWavetable, csl::Buffer::setBuffer(), and csl::Buffer::setSize().
unsigned csl::UnitGenerator::frameRate () inline inherited
Definition at line 249 of file CSL_Core.h.
References csl::UnitGenerator::mFrameRate.
Referenced by dump(), csl::Abst_SoundFile::dump(), and csl::SoundCue::dump().
void csl::UnitGenerator::setFrameRate (unsigned rate) inline inherited
get/set the receiver's frame rate
Definition at line 250 of file CSL_Core.h.
References csl::UnitGenerator::mFrameRate.
virtual unsigned csl::UnitGenerator::numChannels () inline virtual inherited
Reimplemented in csl::Splitter, and csl::Stereoverb.
Definition at line 252 of file CSL_Core.h.
References csl::UnitGenerator::mNumChannels.
Referenced by csl::AmbisonicMixer::addInput(), csl::BlockResizer::BlockResizer(), csl::Port::checkBuffer(), csl::Effect::Effect(), csl::AmbisonicRotator::initialize(), csl::AmbisonicDecoder::initialize(), csl::Mixer::nextBuffer(), csl::Convolver2::setIRFile(), csl::Convolver::setIRFile(), and csl::SpatialSource::SpatialSource().
void csl::UnitGenerator::setNumChannels (unsigned ch) inline inherited
get/set the receiver's number of outputs
Definition at line 253 of file CSL_Core.h.
References csl::UnitGenerator::mNumChannels.
Referenced by csl::BinauralPanner::BinauralPanner(), csl::Spatializer::Spatializer(), csl::VBAP::speakerLayoutChanged(), and csl::VBAP::VBAP().
BufferCopyPolicy csl::UnitGenerator::copyPolicy () inline inherited
Definition at line 255 of file CSL_Core.h.
References csl::UnitGenerator::mCopyPolicy.
void csl::UnitGenerator::setCopyPolicy (BufferCopyPolicy ch) inline inherited
get/set the receiver's buffer copy policy
Definition at line 256 of file CSL_Core.h.
References csl::UnitGenerator::mCopyPolicy.
Referenced by csl::AmbisonicPanner::AmbisonicPanner(), csl::BinauralPanner::BinauralPanner(), csl::AmbisonicUnitGenerator::initOrder(), csl::Noise::Noise(), csl::PinkNoise::PinkNoise(), csl::Spatializer::Spatializer(), and csl::VBAP::VBAP().
virtual bool csl::UnitGenerator::isFixed () inline virtual inherited
query whether I'm fixed (StaticVariable overrides this)
Reimplemented in csl::StaticVariable, and csl::BinaryOp.
Definition at line 271 of file CSL_Core.h.
void UnitGenerator::addOutput (UnitGenerator * ugen) inherited
add to or return the UGen vector of outputs
Definition at line 670 of file CSL_Core.cpp.
References csl::Buffer::allocateBuffers(), csl::CGestalt::blockSize(), csl::UnitGenerator::mNumOutputs, csl::UnitGenerator::mOutputCache, and csl::UnitGenerator::mOutputs.
Referenced by csl::Mixer::addInput(), csl::Controllable::addInput(), csl::AmbisonicRotator::initialize(), csl::AmbisonicDecoder::initialize(), csl::AmbisonicEncoder::setInput(), and csl::IO::setRoot().
void UnitGenerator::removeOutput (UnitGenerator * ugen) inherited
Definition at line 680 of file CSL_Core.cpp.
References csl::UnitGenerator::mNumOutputs, and csl::UnitGenerator::mOutputs.
Referenced by csl::IO::clearRoot(), csl::AmbisonicEncoder::setInput(), csl::AmbisonicDecoder::~AmbisonicDecoder(), and csl::AmbisonicRotator::~AmbisonicRotator().
UGenVector csl::UnitGenerator::outputs () inline inherited
Definition at line 277 of file CSL_Core.h.
References csl::UnitGenerator::mOutputs.
virtual unsigned csl::UnitGenerator::numOutputs () inline virtual inherited
Definition at line 278 of file CSL_Core.h.
References csl::UnitGenerator::mNumOutputs.
bool UnitGenerator::checkFanOut (Buffer & outputBuffer) throw (CException) inherited
check for fan-out and copy previous buffer; return true if fanning out
Definition at line 699 of file CSL_Core.cpp.
void UnitGenerator::handleFanOut (Buffer & outputBuffer) throw (CException) inherited
Definition at line 713 of file CSL_Core.cpp.
References csl_max.
virtual void csl::UnitGenerator::setValue (sample theValue) inline virtual inherited
set/get the value (not allowed in the abstract, useful for static values)
Reimplemented in csl::DynamicVariable, and csl::StaticVariable.
Definition at line 284 of file CSL_Core.h.
virtual sample csl::UnitGenerator::value () inline virtual inherited
Reimplemented in csl::StaticVariable.
Definition at line 285 of file CSL_Core.h.
void UnitGenerator::zeroBuffer (Buffer & outputBuffer, unsigned outBufNum) protected inherited
utility method to zero out an outputBuffer
Definition at line 663 of file CSL_Core.cpp.
References csl::Buffer::buffer(), and csl::Buffer::mMonoBufferByteSize.
void Model::attachObserver (Observer * o) inherited
(possibly notify obersvers on my death)
register/remove observers
Definition at line 502 of file CGestalt.cpp.
References csl::logMsg(), csl::Observer::mKey, and csl::Observer::mPeriod.
Referenced by csl::SpatialPanner::setSpeakerLayout().
void Model::detachObserver (Observer * o) inherited
Definition at line 518 of file CGestalt.cpp.
References csl::logMsg().
Referenced by csl::SpatialPanner::setSpeakerLayout(), and csl::SpatialPanner::~SpatialPanner().
void Model::changed (void * argument) inherited
this is what I send to myself to notify my observers; It's not overridden in general. It results in the observers receiving update() calls < override evaluate to filter updates to the observer map
Definition at line 540 of file CGestalt.cpp.
References csl::logMsg().
Referenced by csl::SpeakerLayout::addSpeaker(), csl::MIDIIn::handleIncomingMidiMessage(), and csl::SpeakerLayout::setDefaultSpeakerLayout().
virtual int csl::Model::evaluate (void * argument) inline virtual inherited
Reimplemented in csl::MIDIIn.
Definition at line 270 of file CGestalt.h.
void Phased::setFrequency (UnitGenerator & frequency) inherited
Setter accessors.
set frequency
Definition at line 981 of file CSL_Core.cpp.
References csl::Controllable::addInput(), and CSL_FREQUENCY.
Referenced by csl::AdditiveInstrument::playMIDI(), csl::AdditiveInstrument::playNote(), csl::AdditiveInstrument::playOSC(), csl::KarplusString::setFrequency(), csl::AdditiveInstrument::setParameter(), csl::SquareBL::SquareBL(), test_SHARC(), test_SHARC2(), testRandFreqEnv(), testSplitJoin1(), testSplitJoin2(), testSumOfSines1F(), testSumOfSinesCached(), testSumOfSinesNonCached(), and testSumOfSinesSteps().
void Phased::setFrequency (float frequency) inherited
set frequency
Definition at line 985 of file CSL_Core.cpp.
References csl::Controllable::addInput(), and CSL_FREQUENCY.
void csl::Phased::setPhase (float phase) inline inherited
Definition at line 507 of file CSL_Core.h.
References csl::Phased::mPhase.
Port * Controllable::getPort (CSL_MAP_KEY name) inherited
Definition at line 920 of file CSL_Core.cpp.
References csl::Controllable::mInputs.
Referenced by csl::FrequencyAmount::getFrequency(), and csl::VSTIO::getParameter().
void Controllable::addInput (CSL_MAP_KEY name, UnitGenerator & ugen) protected inherited
Plug in a unit generator to the named input slot.
Definition at line 894 of file CSL_Core.cpp.
References csl::UnitGenerator::addOutput(), csl::logMsg(), and csl::Controllable::mInputs.
Referenced by csl::Joiner::addInput(), csl::BinaryOp::BinaryOp(), csl::DistanceSimulator::DistanceSimulator(), csl::Effect::Effect(), csl::InOut::InOut(), csl::Joiner::Joiner(), csl::NtoMPanner::NtoMPanner(), csl::Panner::Panner(), csl::Phased::Phased(), csl::Scalable::Scalable(), csl::FrequencyAmount::setAmount(), csl::FrequencyAmount::setFrequency(), csl::Phased::setFrequency(), csl::Effect::setInput(), csl::Scalable::setOffset(), csl::Panner::setPosition(), csl::Abst_SoundFile::setRate(), csl::Scalable::setScale(), csl::NtoMPanner::setX(), csl::NtoMPanner::setY(), and csl::SpatialSource::SpatialSource().
void Controllable::addInput (CSL_MAP_KEY name, float value) protected inherited
Plug in a float to the named input slot.
Definition at line 906 of file CSL_Core.cpp.
References csl::logMsg(), csl::Controllable::mInputs, and csl::Port::mValue.
void Controllable::pullInput (Port * thePort, unsigned numFrames) throw (CException) protected inherited
method to read the control values (in case they're dynamic). this sends nextBuffer() to the input.
Definition at line 847 of file CSL_Core.cpp.
References csl::kSamples, csl::logMsg(), csl::Buffer::mIsPopulated, csl::Buffer::mNumFrames, csl::Buffer::mType, csl::UnitGenerator::nextBuffer(), and csl::Buffer::zeroBuffers().
Referenced by csl::Panner::nextBuffer(), csl::NtoMPanner::nextBuffer(), and csl::Effect::pullInput().
void Controllable::pullInput (Port * thePort, Buffer & theBuffer) throw (CException) protected inherited
Definition at line 879 of file CSL_Core.cpp.
References csl::UnitGenerator::nextBuffer().
void Scalable::setScale (UnitGenerator & scale) inherited
set the receiver's scale member to a UGen or a float
Definition at line 1039 of file CSL_Core.cpp.
References csl::Controllable::addInput(), CSL_SCALE, and csl::logMsg().
Referenced by createRandFreqEnvPatch(), csl::FancyFMInstrument::FancyFMInstrument(), csl::AdditiveInstrument::init(), csl::SndFileInstrument::initialize(), main(), csl::FMInstrument::parseArgs(), csl::SndFileInstrument::playNote(), csl::SndFileInstrument::playOSC(), csl::AdditiveInstrument::setParameter(), csl::SndFileInstrument::setParameter(), csl::FancyFMInstrument::setParameter(), sosNote(), test_SHARC(), test_SHARC2(), testADSR_FM(), testARSin2(), testComplexEnvelope(), testEnvScale(), testFancy_FM(), testFanMix1(), testFanMix2(), testMultiTap(), testRandFreqEnv(), testReverb(), testSplitJoin1(), testSplitJoin2(), testStereoverb(), testString(), testStringChorus(), testSumOfSines1F(), testSumOfSinesCached(), testSumOfSinesNonCached(), testSumOfSinesSteps(), and testWaveShaper().
void Scalable::setScale (float scale) inherited
Definition at line 1046 of file CSL_Core.cpp.
References csl::Controllable::addInput(), CSL_SCALE, and csl::logMsg().
void Scalable::setOffset (UnitGenerator & offset) inherited
set the receiver's offset member to a UGen or a float
Definition at line 1053 of file CSL_Core.cpp.
References csl::Controllable::addInput(), CSL_OFFSET, and csl::logMsg().
void Scalable::setOffset (float offset) inherited
Definition at line 1060 of file CSL_Core.cpp.
References csl::Controllable::addInput(), CSL_OFFSET, and csl::logMsg().
void csl::Scalable::isScaled () inherited
answer whether scale = 1 & offset = 0
void Seekable::reset () throw (CException) virtual inherited
reset-to-zero
Definition at line 1277 of file CSL_Core.cpp.
References csl::kPositionStart, and csl::Seekable::seekTo().
Member Data Documentation
CFURLRef csl::CASoundFile::mURL protected
the full URL of the file
Definition at line 49 of file SoundFileCA.h.
Referenced by CASoundFile().
AudioFileID csl::CASoundFile::mSoundID protected
the CS audio file ID
Definition at line 50 of file SoundFileCA.h.
Referenced by readBufferFromFile().
bool csl::CASoundFile::mBigEndian protected
flag for endian-ness of sound file (varies byformat)
Definition at line 51 of file SoundFileCA.h.
Referenced by dump(), and readBufferFromFile().
SoundFileMetadata* csl::Abst_SoundFile::mProperties inherited
the ID3 tags properties
Definition at line 179 of file SoundFile.h.
Referenced by csl::Abst_SoundFile::readTags(), and csl::Abst_SoundFile::~Abst_SoundFile().
string csl::Abst_SoundFile::mPath protected inherited
file name
Definition at line 182 of file SoundFile.h.
Referenced by csl::Abst_SoundFile::Abst_SoundFile(), CASoundFile(), csl::LSoundFile::LSoundFile(), csl::LSoundFile::openForReadWrite(), csl::Abst_SoundFile::path(), readBufferFromFile(), csl::Abst_SoundFile::readTags(), and csl::Abst_SoundFile::setPath().
SoundFileMode csl::Abst_SoundFile::mMode protected inherited
r/w mode
Definition at line 183 of file SoundFile.h.
Referenced by csl::JSoundFile::close(), csl::LSoundFile::initFromSndfile(), csl::Abst_SoundFile::mode(), and csl::LSoundFile::openForReadWrite().
SoundFileFormat csl::Abst_SoundFile::mFormat protected inherited
sf format
Definition at line 184 of file SoundFile.h.
bool csl::Abst_SoundFile::mIsValid protected inherited
is my file valid?
Definition at line 185 of file SoundFile.h.
Referenced by csl::Abst_SoundFile::channels(), csl::Abst_SoundFile::durationInSecs(), initFromSndfile(), csl::JSoundFile::initFromSndfile(), csl::LSoundFile::initFromSndfile(), csl::Abst_SoundFile::isActive(), csl::Abst_SoundFile::isValid(), and csl::Abst_SoundFile::setStart().
bool csl::Abst_SoundFile::mIsLooping protected inherited
am i looping start-stop?
Definition at line 186 of file SoundFile.h.
Referenced by csl::Abst_SoundFile::isLooping(), readBufferFromFile(), csl::JSoundFile::readBufferFromFile(), csl::LSoundFile::readBufferFromFile(), and csl::Abst_SoundFile::setIsLooping().
int csl::Abst_SoundFile::mStart protected inherited
Definition at line 187 of file SoundFile.h.
Referenced by csl::SoundCue::duration(), csl::Abst_SoundFile::durationInSecs(), initFromSndfile(), csl::JSoundFile::initFromSndfile(), csl::LSoundFile::initFromSndfile(), csl::LSoundFile::readBufferFromFile(), csl::Abst_SoundFile::setStart(), csl::Abst_SoundFile::startFrame(), and csl::Abst_SoundFile::trigger().
int csl::Abst_SoundFile::mStop protected inherited
starting/ending frames (or -1 if not used)
Definition at line 187 of file SoundFile.h.
Referenced by csl::Abst_SoundFile::durationInSecs(), initFromSndfile(), csl::JSoundFile::initFromSndfile(), csl::LSoundFile::initFromSndfile(), csl::Abst_SoundFile::isActive(), readBufferFromFile(), csl::JSoundFile::readBufferFromFile(), csl::LSoundFile::readBufferFromFile(), csl::Abst_SoundFile::setStop(), csl::Abst_SoundFile::setToEnd(), and csl::Abst_SoundFile::stopFrame().
double csl::Abst_SoundFile::mRate protected inherited
sample rate ratio
Definition at line 188 of file SoundFile.h.
Referenced by csl::Abst_SoundFile::playbackRate(), and csl::Abst_SoundFile::setRate().
unsigned csl::Abst_SoundFile::mNumFrames protected inherited
sample frames
Definition at line 189 of file SoundFile.h.
Referenced by csl::Abst_SoundFile::convertRate(), csl::Abst_SoundFile::duration(), initFromSndfile(), csl::JSoundFile::initFromSndfile(), csl::LSoundFile::initFromSndfile(), and csl::LSoundFile::isCached().
unsigned csl::Abst_SoundFile::mBytesPerSample protected inherited
the # of bytes per sample
Definition at line 190 of file SoundFile.h.
Referenced by csl::JSoundFile::initFromSndfile(), csl::LSoundFile::initFromSndfile(), readBufferFromFile(), and csl::Abst_SoundFile::sampleSize().
unsigned csl::Abst_SoundFile::mBase protected inherited
starting frame in file of buffer
Definition at line 191 of file SoundFile.h.
Referenced by csl::Abst_SoundFile::base(), csl::LSoundFile::initFromSndfile(), csl::LSoundFile::readBufferFromFile(), and csl::Abst_SoundFile::setBase().
InterpolationPolicy csl::WavetableOscillator::mInterpolate inherited
whether/how I should interpolate between samples
Definition at line 83 of file Oscillator.h.
Referenced by csl::WavetableOscillator::setInterpolate(), and csl::WavetableOscillator::WavetableOscillator().
Buffer csl::WavetableOscillator::mWavetable inherited
the stored wave form
Definition at line 84 of file Oscillator.h.
Referenced by csl::Abst_SoundFile::Abst_SoundFile(), csl::Abst_SoundFile::buffer(), csl::Abst_SoundFile::cacheSize(), csl::Abst_SoundFile::checkBuffer(), csl::Abst_SoundFile::convertRate(), csl::CompOrCacheOscillator::createCache(), csl::WavetableOscillator::fillSine(), csl::Abst_SoundFile::freeBuffer(), csl::LSoundFile::isCached(), csl::Abst_SoundFile::isCached(), load_filter_data(), csl::Abst_SoundFile::mergeToMono(), readBufferFromFile(), csl::JSoundFile::readBufferFromFile(), csl::LSoundFile::readBufferFromFile(), csl::WavetableOscillator::setWaveform(), csl::WavetableOscillator::WavetableOscillator(), and csl::WavetableOscillator::~WavetableOscillator().
unsigned csl::UnitGenerator::mFrameRate protected inherited
trigger ignored here
the frame rate – initialized to be the default by the constructor
Definition at line 288 of file CSL_Core.h.
Referenced by csl::Abst_SoundFile::convertRate(), csl::Lorenz::dump(), csl::Abst_SoundFile::durationInSecs(), csl::UnitGenerator::frameRate(), csl::Filter::init(), initFromSndfile(), csl::JSoundFile::initFromSndfile(), csl::LSoundFile::initFromSndfile(), csl::RandEnvelope::nextSegment(), csl::SquareBL::nextWaveInto(), csl::SumOfSines::nextWaveInto(), csl::DelayLine::setDelayTime(), csl::UnitGenerator::setFrameRate(), csl::Abst_SoundFile::setStartSec(), csl::Abst_SoundFile::setStopSec(), csl::Butter::setupCoeffs(), csl::Formant::setupCoeffs(), csl::Notch::setupCoeffs(), and csl::Moog::setupCoeffs().
unsigned csl::UnitGenerator::mNumChannels protected inherited
my "expected" number of output channels
Definition at line 292 of file CSL_Core.h.
Referenced by csl::AmbisonicMixer::addInput(), csl::Mixer::allocateOpBuffer(), csl::AmbisonicDecoder::asProjection(), csl::AmbisonicDecoder::asPseudoInverse(), csl::BlockResizer::BlockResizer(), csl::Abst_SoundFile::channels(), csl::Abst_SoundFile::checkBuffer(), csl::FMInstrument::FMInstrument(), csl::GrainPlayer::GrainPlayer(), csl::AdditiveInstrument::init(), csl::JSoundFile::initFromSndfile(), csl::LSoundFile::initFromSndfile(), csl::AmbisonicMixer::initialize(), csl::SndFileInstrument::initialize(), csl::AmbisonicRotator::initialize(), csl::AmbisonicEncoder::initialize(), csl::AmbisonicDecoder::initialize(), csl::AmbisonicUnitGenerator::initOrder(), csl::RemoteStream::initPacket(), csl::Joiner::isActive(), csl::Joiner::Joiner(), csl::AmbisonicDecoder::makeInPhase(), csl::AmbisonicDecoder::makeMaxRE(), csl::Abst_SoundFile::mergeToMono(), csl::Mixer::Mixer(), csl::UnitGenerator::numChannels(), csl::Panner::Panner(), readBufferFromFile(), csl::JSoundFile::readBufferFromFile(), csl::LSoundFile::readBufferFromFile(), csl::RemoteStream::RemoteStream(), csl::UnitGenerator::setNumChannels(), csl::WavetableOscillator::setWaveform(), csl::Joiner::trigger(), and csl::AmbisonicRotator::~AmbisonicRotator().
BufferCopyPolicy csl::UnitGenerator::mCopyPolicy protected inherited
the policy I use if asked for more or fewer channels
Definition at line 293 of file CSL_Core.h.
Referenced by csl::UnitGenerator::copyPolicy(), and csl::UnitGenerator::setCopyPolicy().
UGenVector csl::UnitGenerator::mOutputs protected inherited
the vector of my output UGens
Definition at line 294 of file CSL_Core.h.
Referenced by csl::UnitGenerator::addOutput(), csl::UnitGenerator::dump(), csl::UnitGenerator::outputs(), and csl::UnitGenerator::removeOutput().
unsigned csl::UnitGenerator::mNumOutputs protected inherited
the number of outputs
Definition at line 295 of file CSL_Core.h.
Referenced by csl::UnitGenerator::addOutput(), csl::UnitGenerator::numOutputs(), and csl::UnitGenerator::removeOutput().
Buffer* csl::UnitGenerator::mOutputCache protected inherited
my past output ring buffer (only used in case of fan-out)
Definition at line 296 of file CSL_Core.h.
Referenced by csl::UnitGenerator::addOutput().
unsigned csl::UnitGenerator::mSequence protected inherited
the highest-seen buffer seq number
Definition at line 297 of file CSL_Core.h.
sample csl::Phased::mPhase protected inherited
set phase
the actual phase accumulator
Definition at line 507 of file CSL_Core.h.
Referenced by csl::Phased::setPhase().
PortMap csl::Controllable::mInputs protected inherited
the map of my inputs or controls (used by the mix-in classes)
Definition at line 378 of file CSL_Core.h.
Referenced by csl::Controllable::addInput(), csl::BinaryOp::dump(), csl::Controllable::dump(), csl::Controllable::getPort(), csl::Biquad::incrBoost(), csl::Biquad::incrFrq(), csl::Effect::isActive(), csl::Joiner::isActive(), csl::SquareBL::nextWaveInto(), csl::BinaryOp::operandIsFixed(), csl::Phased::Phased(), csl::DistanceSimulator::positionChanged(), csl::Scalable::Scalable(), csl::Biquad::setBoost(), csl::Biquad::setFrq(), csl::BinaryOp::setOperand(), csl::Abst_SoundFile::setRate(), csl::Butter::setupCoeffs(), csl::Formant::setupCoeffs(), csl::Notch::setupCoeffs(), csl::Allpass::setupCoeffs(), csl::Moog::setupCoeffs(), csl::Scalable::trigger(), csl::Effect::trigger(), csl::Joiner::trigger(), and csl::Controllable::~Controllable().
unsigned csl::Seekable::mCurrentFrame inherited
where I currently am in the buffer
Definition at line 580 of file CSL_Core.h.
Referenced by csl::Abst_SoundFile::Abst_SoundFile(), csl::DelayLine::delayLength(), csl::Abst_SoundFile::isActive(), csl::LSoundFile::isCached(), csl::Abst_SoundFile::isCached(), readBufferFromFile(), csl::JSoundFile::readBufferFromFile(), csl::LSoundFile::readBufferFromFile(), csl::RingBufferTap::setOffset(), csl::Abst_SoundFile::setToEnd(), and csl::Abst_SoundFile::trigger().
double csl::Seekable::mActualFrame inherited
where I actually am in the buffer
Definition at line 583 of file CSL_Core.h.
The documentation for this class was generated from the following files:
/Content/Code/CSL/CSL/IO/SoundFileCA.h
/Content/Code/CSL/CSL/IO/SoundFileCA.cpp