CSL: csl::ThreadPthread Class Reference
csl::ThreadPthread Class Reference
PThread version of Thread.
#include <ThreadUtilities.h>
Public Member Functions
ThreadPthread ()
~ThreadPthread ()
int createThread (VoidFcnPtr *func, void *args)
void stopThread (int timeOutMilliseconds)
Static Public Member Functions
static CThread * MakeThread ()
factory method
Public Attributes
pthread_t mThread
pthread_attr_t mAttributes
Detailed Description
PThread version of Thread.
Definition at line 92 of file ThreadUtilities.h.
Constructor & Destructor Documentation
ThreadPthread::ThreadPthread ()
Definition at line 98 of file ThreadUtilities.cpp.
References csl::CThread::mAttributes.
ThreadPthread::~ThreadPthread ()
Definition at line 102 of file ThreadUtilities.cpp.
References csl::CThread::mAttributes, and csl::CThread::mThread.
Member Function Documentation
int ThreadPthread::createThread (VoidFcnPtr * func, void * args) virtual
Implements csl::CThread.
Definition at line 110 of file ThreadUtilities.cpp.
References csl::CThread::mAttributes, and csl::CThread::mThread.
Referenced by PME::start_management_thread().
CThread * CThread::MakeThread () static inherited
factory method
Definition at line 46 of file ThreadUtilities.cpp.
Referenced by csl::GrainCloud::GrainCloud(), and csl::FileIO::open().
void CThread::stopThread (int timeOutMilliseconds) inherited
Definition at line 50 of file ThreadUtilities.cpp.
References csl::CThread::mThread.
Referenced by csl::GrainCloud::~GrainCloud().
Member Data Documentation
pthread_t csl::CThread::mThread inherited
Definition at line 53 of file ThreadUtilities.h.
Referenced by createThread(), csl::CThread::stopThread(), csl::CThread::~CThread(), and ~ThreadPthread().
pthread_attr_t csl::CThread::mAttributes inherited
Definition at line 54 of file ThreadUtilities.h.
Referenced by createThread(), ThreadPthread(), and ~ThreadPthread().
The documentation for this class was generated from the following files:
/Content/Code/CSL/CSL/Utilities/ThreadUtilities.h
/Content/Code/CSL/CSL/Utilities/ThreadUtilities.cpp