CSL: csl::CGestalt Class Reference
csl::CGestalt Class Reference
The CSL system defaults class.
#include <CGestalt.h>
Static Public Member Functions
static unsigned frameRate ()
default frame rate
static float frameRateF ()
default frame rate as a float
static void setFrameRate (unsigned frameRate)
static sample framePeriod ()
default frame rate
static unsigned numInChannels ()
default number of input channels
static void setNumInChannels (unsigned numChannels)
static unsigned numOutChannels ()
default number of output channels
static void setNumOutChannels (unsigned numChannels)
static unsigned blockSize ()
the default block size
static void setBlockSize (unsigned blockSize)
static unsigned maxBufferFrames ()
the max num frames that can be requested
static void setMaxBufferFrames (unsigned numFrames)
static unsigned maxSndFileFrames ()
the max num frames that can be cached
static void setMaxSndFileFrames (unsigned numFrames)
static unsigned sndFileFrames ()
the default num frames that are cached
static void setSndFileFrames (unsigned numFrames)
static unsigned verbosity ()
the default logging verbosity
static void setVerbosity (unsigned verbosity)
static unsigned loggingPeriod ()
the default logging period
static void setLoggingPeriod (unsigned loggingPeriod)
static unsigned outPort ()
the default RemoteIO output port
static void setOutPort (unsigned outPort)
static std::string dataFolder ()
the default directory for test data
static void setDataFolder (std::string dFolder)
typ. "~/Code/CSL/CSL_Data/"
static bool stopNow ()
flag to stop threads and timers
static void setStopNow ()
static void clearStopNow ()
static std::string initFileText (char key)
read/write the init file (typ. ~/.cslrc)
static void storeToInitFile (char key, std::string data)
static std::string sndFileName ()
pick a new sound file name to use based on OUT_SFILE_NAME
static unsigned screenWidth ()
current screen width
static void setScreenWidth (unsigned numPixels)
static unsigned screenHeight ()
current screen height
static void setScreenHeight (unsigned numPixels)
Detailed Description
The CSL system defaults class.
Definition at line 39 of file CGestalt.h.
Member Function Documentation
unsigned CGestalt::frameRate () static
default frame rate
CGestalt Accessors for system constants.
Definition at line 51 of file CGestalt.cpp.
References mFrameRate.
Referenced by csl::AirAbsorptionCue::compute(), createEffectInstance(), createGrains(), csl::Filter::init(), csl::PAIO::initialize(), csl::KarplusString::KarplusString(), csl::FileIO::open(), csl::PAIO::open(), csl::iPhoneIO::open(), csl::KarplusString::setFrequency(), csl::FileIO::start(), and csl::GrainCloud::startThreads().
float CGestalt::frameRateF () static
default frame rate as a float
Definition at line 52 of file CGestalt.cpp.
References mFrameRateF.
Referenced by csl::Biquad::Biquad(), csl::IO::capture_on(), csl::Buffer::duration(), csl::Buffer::normalize(), csl::FilterSpecification::planFilter(), and csl::IO::printTimeStatistics().
void CGestalt::setFrameRate (unsigned frameRate) static
Definition at line 81 of file CGestalt.cpp.
References mFramePeriod, mFrameRate, and mFrameRateF.
Referenced by csl::PAIO::initialize().
csl::sample CGestalt::framePeriod () static
default frame rate
Definition at line 53 of file CGestalt.cpp.
References mFramePeriod.
unsigned CGestalt::numInChannels () static
default number of input channels
Definition at line 58 of file CGestalt.cpp.
References mNumInChannels.
Referenced by createEffectInstance(), and csl::PAIO::initialize().
void CGestalt::setNumInChannels (unsigned numChannels) static
Definition at line 93 of file CGestalt.cpp.
References mNumInChannels.
Referenced by csl::PAIO::initialize().
unsigned CGestalt::numOutChannels () static
default number of output channels
Definition at line 59 of file CGestalt.cpp.
References mNumOutChannels.
Referenced by createEffectInstance(), csl::DelayLine::DelayLine(), csl::PAIO::initialize(), csl::FileIO::open(), and csl::PAIO::test().
void CGestalt::setNumOutChannels (unsigned numChannels) static
Definition at line 94 of file CGestalt.cpp.
References mNumOutChannels.
Referenced by csl::PAIO::initialize().
unsigned CGestalt::blockSize () static
the default block size
Definition at line 57 of file CGestalt.cpp.
References mBlockSize.
Referenced by csl::UnitGenerator::addOutput(), csl::Mixer::allocateOpBuffer(), csl::Port::checkBuffer(), createEffectInstance(), csl::PAIO::initialize(), csl::AmbisonicMixer::initialize(), csl::FileIO::open(), csl::PAIO::open(), csl::iPhoneIO::open(), csl::IO::printTimeStatistics(), csl::SpatialPanner::SpatialPanner(), csl::PAIO::test(), and csl::Window::Window().
void CGestalt::setBlockSize (unsigned blockSize) static
Definition at line 92 of file CGestalt.cpp.
References mBlockSize.
Referenced by csl::PAIO::initialize().
unsigned CGestalt::maxBufferFrames () static
the max num frames that can be requested
Definition at line 54 of file CGestalt.cpp.
References mMaxBufferFrames.
Referenced by csl::DelayLine::DelayLine().
void CGestalt::setMaxBufferFrames (unsigned numFrames) static
Definition at line 89 of file CGestalt.cpp.
References mMaxBufferFrames.
unsigned CGestalt::maxSndFileFrames () static
the max num frames that can be cached
Definition at line 56 of file CGestalt.cpp.
References mMaxSndFileFrames.
Referenced by csl::CASoundFile::openForRead(), csl::JSoundFile::openForRead(), and csl::LSoundFile::openForRead().
void CGestalt::setMaxSndFileFrames (unsigned numFrames) static
Definition at line 90 of file CGestalt.cpp.
References mMaxSndFileFrames.
unsigned CGestalt::sndFileFrames () static
the default num frames that are cached
Definition at line 55 of file CGestalt.cpp.
References mSndFileFrames.
void CGestalt::setSndFileFrames (unsigned numFrames) static
Definition at line 91 of file CGestalt.cpp.
References mSndFileFrames.
unsigned CGestalt::verbosity () static
the default logging verbosity
Definition at line 60 of file CGestalt.cpp.
References mVerbosity.
void CGestalt::setVerbosity (unsigned verbosity) static
Definition at line 95 of file CGestalt.cpp.
References mVerbosity.
unsigned CGestalt::loggingPeriod () static
the default logging period
Definition at line 61 of file CGestalt.cpp.
References mLoggingPeriod.
void CGestalt::setLoggingPeriod (unsigned loggingPeriod) static
Definition at line 96 of file CGestalt.cpp.
References mLoggingPeriod.
unsigned CGestalt::outPort () static
the default RemoteIO output port
Definition at line 62 of file CGestalt.cpp.
References mOutPort.
Referenced by main().
void CGestalt::setOutPort (unsigned outPort) static
Definition at line 97 of file CGestalt.cpp.
References mOutPort.
string CGestalt::dataFolder () static
the default directory for test data
Definition at line 71 of file CGestalt.cpp.
References mDataFolder.
Referenced by csl::HRTFDatabase::convertDB(), csl::HRTFDatabase::Database(), csl::SHARCLibrary::loadDefault(), sndFileName(), testDynamicVoice(), and testSAFilter().
void CGestalt::setDataFolder (std::string dFolder) static
typ. "~/Code/CSL/CSL_Data/"
Definition at line 98 of file CGestalt.cpp.
References mDataFolder.
bool CGestalt::stopNow () static
flag to stop threads and timers
Definition at line 64 of file CGestalt.cpp.
References mStopNow.
Referenced by csl::sleepUsec().
void CGestalt::setStopNow () static
Definition at line 100 of file CGestalt.cpp.
References mStopNow.
void CGestalt::clearStopNow () static
Definition at line 101 of file CGestalt.cpp.
References mStopNow.
string CGestalt::initFileText (char key) static
read/write the init file (typ. ~/.cslrc)
Definition at line 126 of file CGestalt.cpp.
References CSL_LINE_LEN, and initFileName().
void CGestalt::storeToInitFile (char key, std::string data) static
Definition at line 145 of file CGestalt.cpp.
References CSL_STR_LEN, initFileName(), and len.
string CGestalt::sndFileName () static
pick a new sound file name to use based on OUT_SFILE_NAME
Definition at line 186 of file CGestalt.cpp.
References cheapPrintf, CSL_NAME_LEN, dataFolder(), csl::logMsg(), and OUT_SFILE_NAME.
Referenced by csl::FileIO::FileIO().
unsigned CGestalt::screenWidth () static
current screen width
Definition at line 66 of file CGestalt.cpp.
References sScreenWidth.
void CGestalt::setScreenWidth (unsigned numPixels) static
Definition at line 103 of file CGestalt.cpp.
References sScreenWidth.
unsigned CGestalt::screenHeight () static
current screen height
Definition at line 67 of file CGestalt.cpp.
References sScreenHeight.
void CGestalt::setScreenHeight (unsigned numPixels) static
Definition at line 104 of file CGestalt.cpp.
References sScreenHeight.
The documentation for this class was generated from the following files:
/Content/Code/CSL/CSL/Kernel/CGestalt.h
/Content/Code/CSL/CSL/Kernel/CGestalt.cpp