CSL: csl::NtoMPanner Class Reference
csl::NtoMPanner Class Reference
#include <Mixer.h>
Public Member Functions
NtoMPanner ()
NtoMPanner (UnitGenerator &i, float a, unsigned in_c, unsigned out_c)
NtoMPanner (UnitGenerator &i, UnitGenerator &pX, UnitGenerator &pY, UnitGenerator &a, unsigned in_c, unsigned out_c)
NtoMPanner (UnitGenerator &i, UnitGenerator &pX, UnitGenerator &pY, UnitGenerator &a, unsigned in_c, unsigned out_c, float spr)
NtoMPanner (UnitGenerator &i, UnitGenerator &pX, UnitGenerator &pY, float a, unsigned in_c, unsigned out_c, float spr)
~NtoMPanner ()
void init_stereo (float dist)
void init_quad (float dist)
void init_5point1 (float dist)
void init_6ch (float x, float y)
void setX (float x)
void setY (float y)
virtual void nextBuffer (Buffer &outputBuffer) throw (CException)
I'm stereo!
void setPosition (UnitGenerator &pan)
Operations.
void setPosition (float pan)
set the position to a float
virtual unsigned numChannels () const
virtual unsigned numChannels ()
virtual void nextBuffer (Buffer &outputBuffer, unsigned outBufNum) throw (CException)
really compute the next buffer given an offset base channel; this is called by nextBuffer, possibly multiple times
virtual bool isActive ()
am I active?
void setInput (UnitGenerator &inp)
set the receiver's input generator
void setInline ()
set the Effect to be inline
virtual void trigger ()
trigger passed on here
unsigned frameRate ()
void setFrameRate (unsigned rate)
get/set the receiver's frame rate
void setNumChannels (unsigned ch)
get/set the receiver's number of outputs
BufferCopyPolicy copyPolicy ()
void setCopyPolicy (BufferCopyPolicy ch)
get/set the receiver's buffer copy policy
virtual bool isFixed ()
query whether I'm fixed (StaticVariable overrides this)
void addOutput (UnitGenerator *ugen)
add to or return the UGen vector of outputs
void removeOutput (UnitGenerator *ugen)
UGenVector outputs ()
virtual unsigned numOutputs ()
bool checkFanOut (Buffer &outputBuffer) throw (CException)
check for fan-out and copy previous buffer; return true if fanning out
void handleFanOut (Buffer &outputBuffer) throw (CException)
virtual void setValue (sample theValue)
set/get the value (not allowed in the abstract, useful for static values)
virtual sample value ()
virtual void dump ()
pretty-print the receiver
void attachObserver (Observer *)
(possibly notify obersvers on my death)
void detachObserver (Observer *)
void changed (void *argument)
this is what I send to myself to notify my observers; It's not overridden in general. It results in the observers receiving update() calls < override evaluate to filter updates to the observer map
virtual int evaluate (void *argument)
Port * getPort (CSL_MAP_KEY name)
void setScale (UnitGenerator &scale)
set the receiver's scale member to a UGen or a float
void setScale (float scale)
void setOffset (UnitGenerator &offset)
set the receiver's offset member to a UGen or a float
void setOffset (float offset)
void isScaled ()
answer whether scale = 1 & offset = 0
Public Attributes
bool isInline
whether to use input or buffer as source
Protected Member Functions
void initSpeakers (void)
void pullInput (Buffer &outputBuffer) throw (CException)
void pullInput (unsigned numFrames) throw (CException)
trigger passed on here
void pullInput (Port *thePort, unsigned numFrames) throw (CException)
method to read the control values (in case they're dynamic). this sends nextBuffer() to the input.
void pullInput (Port *thePort, Buffer &theBuffer) throw (CException)
virtual void trigger ()
trigger passed on here get the input port
Port * inPort ()
virtual void dump ()
pretty-print the receiver's input/controls map
void zeroBuffer (Buffer &outputBuffer, unsigned outBufNum)
utility method to zero out an outputBuffer
void addInput (CSL_MAP_KEY name, UnitGenerator &ugen)
Plug in a unit generator to the named input slot.
void addInput (CSL_MAP_KEY name, float value)
Plug in a float to the named input slot.
Protected Attributes
unsigned mInCh
unsigned mOutCh
CPoint ** mSpeakers
float mSpread
Buffer mOpBuffer
SampleBuffer mInputPtr
A pointer to my input's data. method to read the input value.
unsigned mFrameRate
trigger ignored here
unsigned mNumChannels
my "expected" number of output channels
BufferCopyPolicy mCopyPolicy
the policy I use if asked for more or fewer channels
UGenVector mOutputs
the vector of my output UGens
unsigned mNumOutputs
the number of outputs
Buffer * mOutputCache
my past output ring buffer (only used in case of fan-out)
unsigned mSequence
the highest-seen buffer seq number
PortMap mInputs
the map of my inputs or controls (used by the mix-in classes)
Detailed Description
Definition at line 92 of file Mixer.h.
Constructor & Destructor Documentation
csl::NtoMPanner::NtoMPanner () inline
Definition at line 103 of file Mixer.h.
NtoMPanner::NtoMPanner (UnitGenerator & i, float a, unsigned in_c, unsigned out_c)
Definition at line 321 of file Mixer.cpp.
References csl::Controllable::addInput(), CSL_PI, CSL_POSITIONX, CSL_POSITIONY, initSpeakers(), mInCh, mOutCh, and mSpread.
NtoMPanner::NtoMPanner (UnitGenerator & i, UnitGenerator & pX, UnitGenerator & pY, UnitGenerator & a, unsigned in_c, unsigned out_c)
Definition at line 330 of file Mixer.cpp.
References csl::Controllable::addInput(), CSL_PI, CSL_POSITIONX, CSL_POSITIONY, initSpeakers(), mInCh, mOutCh, and mSpread.
NtoMPanner::NtoMPanner (UnitGenerator & i, UnitGenerator & pX, UnitGenerator & pY, UnitGenerator & a, unsigned in_c, unsigned out_c, float spr)
Definition at line 341 of file Mixer.cpp.
References csl::Controllable::addInput(), CSL_POSITIONX, CSL_POSITIONY, initSpeakers(), mInCh, mOutCh, and mSpread.
NtoMPanner::NtoMPanner (UnitGenerator & i, UnitGenerator & pX, UnitGenerator & pY, float a, unsigned in_c, unsigned out_c, float spr)
Definition at line 352 of file Mixer.cpp.
References csl::Controllable::addInput(), CSL_POSITIONX, CSL_POSITIONY, initSpeakers(), mInCh, mOutCh, and mSpread.
NtoMPanner::~NtoMPanner ()
Definition at line 363 of file Mixer.cpp.
Member Function Documentation
void NtoMPanner::initSpeakers (void) protected
Definition at line 443 of file Mixer.cpp.
References init_5point1(), init_6ch(), init_quad(), init_stereo(), and mOutCh.
Referenced by NtoMPanner().
void NtoMPanner::init_stereo (float dist)
Definition at line 460 of file Mixer.cpp.
References mSpeakers.
Referenced by initSpeakers().
void NtoMPanner::init_quad (float dist)
Definition at line 469 of file Mixer.cpp.
References mSpeakers.
Referenced by initSpeakers().
void NtoMPanner::init_5point1 (float dist)
Definition at line 480 of file Mixer.cpp.
References CSL_PI, kPolar, and mSpeakers.
Referenced by initSpeakers().
void NtoMPanner::init_6ch (float x, float y)
Definition at line 491 of file Mixer.cpp.
References mSpeakers.
Referenced by initSpeakers().
void NtoMPanner::setX (float x)
Definition at line 365 of file Mixer.cpp.
References csl::Controllable::addInput(), and CSL_POSITIONX.
void NtoMPanner::setY (float y)
Definition at line 369 of file Mixer.cpp.
References csl::Controllable::addInput(), and CSL_POSITIONY.
void NtoMPanner::nextBuffer (Buffer & outputBuffer) throw (CException) virtual
I'm stereo!
Reimplemented from csl::Panner.
Definition at line 375 of file Mixer.cpp.
References CSL_INPUT, CSL_POSITIONX, CSL_POSITIONY, DECLARE_SCALABLE_CONTROLS, LOAD_SCALABLE_CONTROLS, MAX_OUTPUTS, csl::Port::nextValue(), csl::Controllable::pullInput(), csl::Effect::pullInput(), csl::CPoint::rotateBy(), and csl::CPoint::set().
void Panner::setPosition (UnitGenerator & pan) inherited
Operations.
set the position to a UGen
Definition at line 279 of file Mixer.cpp.
References csl::Controllable::addInput(), and CSL_POSITION.
Referenced by csl::FMInstrument::parseArgs(), csl::AdditiveInstrument::playNote(), csl::SndFileInstrument::playNote(), csl::FMInstrument::playNote(), csl::AdditiveInstrument::playOSC(), csl::SndFileInstrument::playOSC(), csl::AdditiveInstrument::setParameter(), csl::FMInstrument::setParameter(), csl::SndFileInstrument::setParameter(), and testStereoverb().
void Panner::setPosition (float pan) inherited
set the position to a float
Definition at line 283 of file Mixer.cpp.
References csl::Controllable::addInput(), and CSL_POSITION.
virtual unsigned csl::Panner::numChannels () const inline virtual inherited
Definition at line 81 of file Mixer.h.
virtual unsigned csl::UnitGenerator::numChannels () inline virtual inherited
Reimplemented in csl::Splitter, and csl::Stereoverb.
Definition at line 252 of file CSL_Core.h.
References csl::UnitGenerator::mNumChannels.
Referenced by csl::AmbisonicMixer::addInput(), csl::BlockResizer::BlockResizer(), csl::Port::checkBuffer(), csl::Effect::Effect(), csl::AmbisonicRotator::initialize(), csl::AmbisonicDecoder::initialize(), csl::Mixer::nextBuffer(), csl::Convolver2::setIRFile(), csl::Convolver::setIRFile(), and csl::SpatialSource::SpatialSource().
void UnitGenerator::nextBuffer (Buffer & outputBuffer, unsigned outBufNum) throw (CException) virtual inherited
really compute the next buffer given an offset base channel; this is called by nextBuffer, possibly multiple times
Reimplemented in csl::Joiner, csl::Splitter, csl::FanOut, SAFliter, csl::RandEnvelope, csl::Moog, csl::AmbisonicDecoder, csl::Biquad, csl::Impulse, csl::Square, csl::AmbisonicEncoder, csl::Sawtooth, csl::FSine, csl::MulOp, csl::Envelope, csl::Filter, csl::Sine, csl::DynamicVariable, csl::AmbisonicRotator, csl::BufferStream, csl::CompOrCacheOscillator, csl::AddOp, csl::FIR, csl::WavetableOscillator, csl::PinkNoise, csl::VBAP, csl::SineAsScaled, csl::SpatialSource, csl::LineSegment, csl::StaticVariable, csl::AmbisonicMixer, csl::WhiteNoise, csl::SineAsPhased, csl::SpatialPanner, csl::Window, csl::RingBufferTap, csl::BinaryOp, csl::Freeverb, csl::KarplusString, csl::Clipper, csl::Lorenz, csl::SimpleSine, csl::DistanceSimulator, and csl::WaveShaper.
Definition at line 755 of file CSL_Core.cpp.
bool Effect::isActive () virtual inherited
am I active?
Reimplemented from csl::UnitGenerator.
Reimplemented in csl::Joiner, and csl::Stereoverb.
Definition at line 1105 of file CSL_Core.cpp.
References CSL_INPUT, csl::Port::isActive(), and csl::Controllable::mInputs.
Referenced by csl::Stereoverb::isActive().
void Effect::setInput (UnitGenerator & inp) inherited
set the receiver's input generator
Definition at line 1112 of file CSL_Core.cpp.
References csl::Controllable::addInput(), CSL_INPUT, csl::Effect::isInline, and csl::logMsg().
void csl::Effect::setInline () inline inherited
set the Effect to be inline
Definition at line 476 of file CSL_Core.h.
void Effect::pullInput (Buffer & outputBuffer) throw (CException) protected inherited
Definition at line 1122 of file CSL_Core.cpp.
References CSL_INPUT, csl::logMsg(), and csl::Controllable::pullInput().
Referenced by csl::Convolver2::nextBuffer(), csl::Convolver::nextBuffer(), csl::InOut::nextBuffer(), csl::RingBuffer::nextBuffer(), csl::Panner::nextBuffer(), csl::FIR::nextBuffer(), csl::DynamicVariable::nextBuffer(), csl::Filter::nextBuffer(), nextBuffer(), csl::StereoWidth::nextBuffer(), csl::Biquad::nextBuffer(), and SAFliter::nextBuffer().
void Effect::pullInput (unsigned numFrames) throw (CException) protected inherited
trigger passed on here
Definition at line 1137 of file CSL_Core.cpp.
References csl::Buffer::buffer(), CSL_INPUT, csl::logMsg(), csl::Port::mBuffer, and csl::Controllable::pullInput().
void Controllable::pullInput (Port * thePort, unsigned numFrames) throw (CException) protected inherited
method to read the control values (in case they're dynamic). this sends nextBuffer() to the input.
Definition at line 847 of file CSL_Core.cpp.
References csl::kSamples, csl::logMsg(), csl::Buffer::mIsPopulated, csl::Buffer::mNumFrames, csl::Buffer::mType, csl::UnitGenerator::nextBuffer(), and csl::Buffer::zeroBuffers().
Referenced by csl::Panner::nextBuffer(), nextBuffer(), and csl::Effect::pullInput().
void Controllable::pullInput (Port * thePort, Buffer & theBuffer) throw (CException) protected inherited
Definition at line 879 of file CSL_Core.cpp.
References csl::UnitGenerator::nextBuffer().
void Effect::trigger (void) protected virtual inherited
trigger passed on here get the input port
Reimplemented from csl::UnitGenerator.
Reimplemented in csl::Joiner.
Definition at line 1148 of file CSL_Core.cpp.
References CSL_INPUT, and csl::Controllable::mInputs.
void Scalable::trigger (void) virtual inherited
trigger passed on here
Reimplemented in csl::RandEnvelope, csl::Abst_SoundFile, csl::Envelope, and csl::KarplusString.
Definition at line 1069 of file CSL_Core.cpp.
References CSL_OFFSET, CSL_SCALE, and csl::Controllable::mInputs.
Port* csl::Effect::inPort () inline protected inherited
Definition at line 485 of file CSL_Core.h.
References CSL_INPUT.
Referenced by csl::BinaryOp::dump(), and csl::BinaryOp::inputIsFixed().
unsigned csl::UnitGenerator::frameRate () inline inherited
Definition at line 249 of file CSL_Core.h.
References csl::UnitGenerator::mFrameRate.
Referenced by csl::CASoundFile::dump(), csl::Abst_SoundFile::dump(), and csl::SoundCue::dump().
void csl::UnitGenerator::setFrameRate (unsigned rate) inline inherited
get/set the receiver's frame rate
Definition at line 250 of file CSL_Core.h.
References csl::UnitGenerator::mFrameRate.
void csl::UnitGenerator::setNumChannels (unsigned ch) inline inherited
get/set the receiver's number of outputs
Definition at line 253 of file CSL_Core.h.
References csl::UnitGenerator::mNumChannels.
Referenced by csl::BinauralPanner::BinauralPanner(), csl::Spatializer::Spatializer(), csl::VBAP::speakerLayoutChanged(), and csl::VBAP::VBAP().
BufferCopyPolicy csl::UnitGenerator::copyPolicy () inline inherited
Definition at line 255 of file CSL_Core.h.
References csl::UnitGenerator::mCopyPolicy.
void csl::UnitGenerator::setCopyPolicy (BufferCopyPolicy ch) inline inherited
get/set the receiver's buffer copy policy
Definition at line 256 of file CSL_Core.h.
References csl::UnitGenerator::mCopyPolicy.
Referenced by csl::AmbisonicPanner::AmbisonicPanner(), csl::BinauralPanner::BinauralPanner(), csl::AmbisonicUnitGenerator::initOrder(), csl::Noise::Noise(), csl::PinkNoise::PinkNoise(), csl::Spatializer::Spatializer(), and csl::VBAP::VBAP().
virtual bool csl::UnitGenerator::isFixed () inline virtual inherited
query whether I'm fixed (StaticVariable overrides this)
Reimplemented in csl::StaticVariable, and csl::BinaryOp.
Definition at line 271 of file CSL_Core.h.
void UnitGenerator::addOutput (UnitGenerator * ugen) inherited
add to or return the UGen vector of outputs
Definition at line 670 of file CSL_Core.cpp.
References csl::Buffer::allocateBuffers(), csl::CGestalt::blockSize(), csl::UnitGenerator::mNumOutputs, csl::UnitGenerator::mOutputCache, and csl::UnitGenerator::mOutputs.
Referenced by csl::Mixer::addInput(), csl::Controllable::addInput(), csl::AmbisonicRotator::initialize(), csl::AmbisonicDecoder::initialize(), csl::AmbisonicEncoder::setInput(), and csl::IO::setRoot().
void UnitGenerator::removeOutput (UnitGenerator * ugen) inherited
Definition at line 680 of file CSL_Core.cpp.
References csl::UnitGenerator::mNumOutputs, and csl::UnitGenerator::mOutputs.
Referenced by csl::IO::clearRoot(), csl::AmbisonicEncoder::setInput(), csl::AmbisonicDecoder::~AmbisonicDecoder(), and csl::AmbisonicRotator::~AmbisonicRotator().
UGenVector csl::UnitGenerator::outputs () inline inherited
Definition at line 277 of file CSL_Core.h.
References csl::UnitGenerator::mOutputs.
virtual unsigned csl::UnitGenerator::numOutputs () inline virtual inherited
Definition at line 278 of file CSL_Core.h.
References csl::UnitGenerator::mNumOutputs.
bool UnitGenerator::checkFanOut (Buffer & outputBuffer) throw (CException) inherited
check for fan-out and copy previous buffer; return true if fanning out
Definition at line 699 of file CSL_Core.cpp.
void UnitGenerator::handleFanOut (Buffer & outputBuffer) throw (CException) inherited
Definition at line 713 of file CSL_Core.cpp.
References csl_max.
virtual void csl::UnitGenerator::setValue (sample theValue) inline virtual inherited
set/get the value (not allowed in the abstract, useful for static values)
Reimplemented in csl::DynamicVariable, and csl::StaticVariable.
Definition at line 284 of file CSL_Core.h.
virtual sample csl::UnitGenerator::value () inline virtual inherited
Reimplemented in csl::StaticVariable.
Definition at line 285 of file CSL_Core.h.
void UnitGenerator::dump (void) virtual inherited
pretty-print the receiver
Reimplemented in csl::RandEnvelope, csl::SumOfSines, csl::SoundCue, csl::Abst_SoundFile, csl::Filter, csl::Envelope, csl::BufferStream, csl::VBAP, csl::SineAsScaled, csl::LineSegment, csl::SpatialSource, csl::SineAsPhased, csl::Mixer, csl::Window, csl::KarplusString, csl::Oscillator, csl::AmbisonicPanner, csl::BinaryOp, csl::Lorenz, csl::Clipper, csl::Noise, and csl::CASoundFile.
Definition at line 693 of file CSL_Core.cpp.
References csl::logMsg(), and csl::UnitGenerator::mOutputs.
Referenced by csl::Noise::dump(), csl::Clipper::dump(), csl::Filter::dump(), csl::Port::dump(), dumpTest(), and testSimpleSines().
void Controllable::dump (void) protected virtual inherited
pretty-print the receiver's input/controls map
Reimplemented in csl::RandEnvelope, csl::SumOfSines, csl::Abst_SoundFile, csl::Filter, csl::Envelope, csl::SineAsScaled, csl::SpatialSource, csl::SineAsPhased, csl::Mixer, csl::KarplusString, csl::Oscillator, csl::BinaryOp, csl::Clipper, csl::Noise, and csl::CASoundFile.
Definition at line 926 of file CSL_Core.cpp.
References CSL_FREQUENCY, CSL_INPUT, CSL_OFFSET, CSL_SCALE, csl::logMsg(), and csl::Controllable::mInputs.
Referenced by csl::Noise::dump(), csl::KarplusString::dump(), csl::Oscillator::dump(), csl::SineAsPhased::dump(), csl::SineAsScaled::dump(), csl::Envelope::dump(), csl::Filter::dump(), and csl::SumOfSines::dump().
void UnitGenerator::zeroBuffer (Buffer & outputBuffer, unsigned outBufNum) protected inherited
utility method to zero out an outputBuffer
Definition at line 663 of file CSL_Core.cpp.
References csl::Buffer::buffer(), and csl::Buffer::mMonoBufferByteSize.
void Model::attachObserver (Observer * o) inherited
(possibly notify obersvers on my death)
register/remove observers
Definition at line 502 of file CGestalt.cpp.
References csl::logMsg(), csl::Observer::mKey, and csl::Observer::mPeriod.
Referenced by csl::SpatialPanner::setSpeakerLayout().
void Model::detachObserver (Observer * o) inherited
Definition at line 518 of file CGestalt.cpp.
References csl::logMsg().
Referenced by csl::SpatialPanner::setSpeakerLayout(), and csl::SpatialPanner::~SpatialPanner().
void Model::changed (void * argument) inherited
this is what I send to myself to notify my observers; It's not overridden in general. It results in the observers receiving update() calls < override evaluate to filter updates to the observer map
Definition at line 540 of file CGestalt.cpp.
References csl::logMsg().
Referenced by csl::SpeakerLayout::addSpeaker(), csl::MIDIIn::handleIncomingMidiMessage(), and csl::SpeakerLayout::setDefaultSpeakerLayout().
virtual int csl::Model::evaluate (void * argument) inline virtual inherited
Reimplemented in csl::MIDIIn.
Definition at line 270 of file CGestalt.h.
Port * Controllable::getPort (CSL_MAP_KEY name) inherited
Definition at line 920 of file CSL_Core.cpp.
References csl::Controllable::mInputs.
Referenced by csl::FrequencyAmount::getFrequency(), and csl::VSTIO::getParameter().
void Controllable::addInput (CSL_MAP_KEY name, UnitGenerator & ugen) protected inherited
Plug in a unit generator to the named input slot.
Definition at line 894 of file CSL_Core.cpp.
References csl::UnitGenerator::addOutput(), csl::logMsg(), and csl::Controllable::mInputs.
Referenced by csl::Joiner::addInput(), csl::BinaryOp::BinaryOp(), csl::DistanceSimulator::DistanceSimulator(), csl::Effect::Effect(), csl::InOut::InOut(), csl::Joiner::Joiner(), NtoMPanner(), csl::Panner::Panner(), csl::Phased::Phased(), csl::Scalable::Scalable(), csl::FrequencyAmount::setAmount(), csl::FrequencyAmount::setFrequency(), csl::Phased::setFrequency(), csl::Effect::setInput(), csl::Scalable::setOffset(), csl::Panner::setPosition(), csl::Abst_SoundFile::setRate(), csl::Scalable::setScale(), setX(), setY(), and csl::SpatialSource::SpatialSource().
void Controllable::addInput (CSL_MAP_KEY name, float value) protected inherited
Plug in a float to the named input slot.
Definition at line 906 of file CSL_Core.cpp.
References csl::logMsg(), csl::Controllable::mInputs, and csl::Port::mValue.
void Scalable::setScale (UnitGenerator & scale) inherited
set the receiver's scale member to a UGen or a float
Definition at line 1039 of file CSL_Core.cpp.
References csl::Controllable::addInput(), CSL_SCALE, and csl::logMsg().
Referenced by createRandFreqEnvPatch(), csl::FancyFMInstrument::FancyFMInstrument(), csl::AdditiveInstrument::init(), csl::SndFileInstrument::initialize(), main(), csl::FMInstrument::parseArgs(), csl::SndFileInstrument::playNote(), csl::SndFileInstrument::playOSC(), csl::AdditiveInstrument::setParameter(), csl::SndFileInstrument::setParameter(), csl::FancyFMInstrument::setParameter(), sosNote(), test_SHARC(), test_SHARC2(), testADSR_FM(), testARSin2(), testComplexEnvelope(), testEnvScale(), testFancy_FM(), testFanMix1(), testFanMix2(), testMultiTap(), testRandFreqEnv(), testReverb(), testSplitJoin1(), testSplitJoin2(), testStereoverb(), testString(), testStringChorus(), testSumOfSines1F(), testSumOfSinesCached(), testSumOfSinesNonCached(), testSumOfSinesSteps(), and testWaveShaper().
void Scalable::setScale (float scale) inherited
Definition at line 1046 of file CSL_Core.cpp.
References csl::Controllable::addInput(), CSL_SCALE, and csl::logMsg().
void Scalable::setOffset (UnitGenerator & offset) inherited
set the receiver's offset member to a UGen or a float
Definition at line 1053 of file CSL_Core.cpp.
References csl::Controllable::addInput(), CSL_OFFSET, and csl::logMsg().
void Scalable::setOffset (float offset) inherited
Definition at line 1060 of file CSL_Core.cpp.
References csl::Controllable::addInput(), CSL_OFFSET, and csl::logMsg().
void csl::Scalable::isScaled () inherited
answer whether scale = 1 & offset = 0
Member Data Documentation
unsigned csl::NtoMPanner::mInCh protected
Definition at line 95 of file Mixer.h.
Referenced by NtoMPanner().
unsigned csl::NtoMPanner::mOutCh protected
Definition at line 95 of file Mixer.h.
Referenced by initSpeakers(), and NtoMPanner().
CPoint** csl::NtoMPanner::mSpeakers protected
Definition at line 96 of file Mixer.h.
Referenced by init_5point1(), init_6ch(), init_quad(), and init_stereo().
float csl::NtoMPanner::mSpread protected
Definition at line 97 of file Mixer.h.
Referenced by NtoMPanner().
Buffer csl::NtoMPanner::mOpBuffer protected
Definition at line 98 of file Mixer.h.
bool csl::Effect::isInline inherited
whether to use input or buffer as source
Definition at line 475 of file CSL_Core.h.
Referenced by csl::Effect::Effect(), and csl::Effect::setInput().
SampleBuffer csl::Effect::mInputPtr protected inherited
A pointer to my input's data. method to read the input value.
Definition at line 479 of file CSL_Core.h.
unsigned csl::UnitGenerator::mFrameRate protected inherited
trigger ignored here
the frame rate – initialized to be the default by the constructor
Definition at line 288 of file CSL_Core.h.
Referenced by csl::Abst_SoundFile::convertRate(), csl::Lorenz::dump(), csl::Abst_SoundFile::durationInSecs(), csl::UnitGenerator::frameRate(), csl::Filter::init(), csl::CASoundFile::initFromSndfile(), csl::JSoundFile::initFromSndfile(), csl::LSoundFile::initFromSndfile(), csl::RandEnvelope::nextSegment(), csl::SquareBL::nextWaveInto(), csl::SumOfSines::nextWaveInto(), csl::DelayLine::setDelayTime(), csl::UnitGenerator::setFrameRate(), csl::Abst_SoundFile::setStartSec(), csl::Abst_SoundFile::setStopSec(), csl::Butter::setupCoeffs(), csl::Formant::setupCoeffs(), csl::Notch::setupCoeffs(), and csl::Moog::setupCoeffs().
unsigned csl::UnitGenerator::mNumChannels protected inherited
my "expected" number of output channels
Definition at line 292 of file CSL_Core.h.
Referenced by csl::AmbisonicMixer::addInput(), csl::Mixer::allocateOpBuffer(), csl::AmbisonicDecoder::asProjection(), csl::AmbisonicDecoder::asPseudoInverse(), csl::BlockResizer::BlockResizer(), csl::Abst_SoundFile::channels(), csl::Abst_SoundFile::checkBuffer(), csl::FMInstrument::FMInstrument(), csl::GrainPlayer::GrainPlayer(), csl::AdditiveInstrument::init(), csl::JSoundFile::initFromSndfile(), csl::LSoundFile::initFromSndfile(), csl::AmbisonicMixer::initialize(), csl::SndFileInstrument::initialize(), csl::AmbisonicRotator::initialize(), csl::AmbisonicEncoder::initialize(), csl::AmbisonicDecoder::initialize(), csl::AmbisonicUnitGenerator::initOrder(), csl::RemoteStream::initPacket(), csl::Joiner::isActive(), csl::Joiner::Joiner(), csl::AmbisonicDecoder::makeInPhase(), csl::AmbisonicDecoder::makeMaxRE(), csl::Abst_SoundFile::mergeToMono(), csl::Mixer::Mixer(), csl::UnitGenerator::numChannels(), csl::Panner::Panner(), csl::CASoundFile::readBufferFromFile(), csl::JSoundFile::readBufferFromFile(), csl::LSoundFile::readBufferFromFile(), csl::RemoteStream::RemoteStream(), csl::UnitGenerator::setNumChannels(), csl::WavetableOscillator::setWaveform(), csl::Joiner::trigger(), and csl::AmbisonicRotator::~AmbisonicRotator().
BufferCopyPolicy csl::UnitGenerator::mCopyPolicy protected inherited
the policy I use if asked for more or fewer channels
Definition at line 293 of file CSL_Core.h.
Referenced by csl::UnitGenerator::copyPolicy(), and csl::UnitGenerator::setCopyPolicy().
UGenVector csl::UnitGenerator::mOutputs protected inherited
the vector of my output UGens
Definition at line 294 of file CSL_Core.h.
Referenced by csl::UnitGenerator::addOutput(), csl::UnitGenerator::dump(), csl::UnitGenerator::outputs(), and csl::UnitGenerator::removeOutput().
unsigned csl::UnitGenerator::mNumOutputs protected inherited
the number of outputs
Definition at line 295 of file CSL_Core.h.
Referenced by csl::UnitGenerator::addOutput(), csl::UnitGenerator::numOutputs(), and csl::UnitGenerator::removeOutput().
Buffer* csl::UnitGenerator::mOutputCache protected inherited
my past output ring buffer (only used in case of fan-out)
Definition at line 296 of file CSL_Core.h.
Referenced by csl::UnitGenerator::addOutput().
unsigned csl::UnitGenerator::mSequence protected inherited
the highest-seen buffer seq number
Definition at line 297 of file CSL_Core.h.
PortMap csl::Controllable::mInputs protected inherited
the map of my inputs or controls (used by the mix-in classes)
Definition at line 378 of file CSL_Core.h.
Referenced by csl::Controllable::addInput(), csl::BinaryOp::dump(), csl::Controllable::dump(), csl::Controllable::getPort(), csl::Biquad::incrBoost(), csl::Biquad::incrFrq(), csl::Effect::isActive(), csl::Joiner::isActive(), csl::SquareBL::nextWaveInto(), csl::BinaryOp::operandIsFixed(), csl::Phased::Phased(), csl::DistanceSimulator::positionChanged(), csl::Scalable::Scalable(), csl::Biquad::setBoost(), csl::Biquad::setFrq(), csl::BinaryOp::setOperand(), csl::Abst_SoundFile::setRate(), csl::Butter::setupCoeffs(), csl::Formant::setupCoeffs(), csl::Notch::setupCoeffs(), csl::Allpass::setupCoeffs(), csl::Moog::setupCoeffs(), csl::Scalable::trigger(), csl::Effect::trigger(), csl::Joiner::trigger(), and csl::Controllable::~Controllable().
The documentation for this class was generated from the following files:
/Content/Code/CSL/CSL/Processors/Mixer.h
/Content/Code/CSL/CSL/Processors/Mixer.cpp