CSL: csl::Synch Class Reference
csl::Synch Class Reference abstract
Sync is a cross-thread synchronization object.
#include <ThreadUtilities.h>
Public Member Functions
Synch ()
Constructor.
virtual ~Synch ()
Destructor.
virtual int lock ()=0
virtual int unlock ()=0
virtual int condWait ()=0
virtual int condSignal ()=0
Static Public Member Functions
static Synch * MakeSynch ()
Factory method Utilities.
Detailed Description
Sync is a cross-thread synchronization object.
Definition at line 60 of file ThreadUtilities.h.
Constructor & Destructor Documentation
csl::Synch::Synch () inline
Constructor.
Definition at line 62 of file ThreadUtilities.h.
virtual csl::Synch::~Synch () inline virtual
Destructor.
Definition at line 63 of file ThreadUtilities.h.
Member Function Documentation
Synch * Synch::MakeSynch () static
Factory method Utilities.
Definition at line 54 of file ThreadUtilities.cpp.
Referenced by csl::NullIO::NullIO(), and csl::StdIO::StdIO().
virtual int csl::Synch::lock () pure virtual
Implemented in csl::SynchPthread.
Referenced by csl::NullIO::FeederFunction(), and csl::StdIO::FeederFunction().
virtual int csl::Synch::unlock () pure virtual
Implemented in csl::SynchPthread.
Referenced by csl::NullIO::FeederFunction(), and csl::StdIO::FeederFunction().
virtual int csl::Synch::condWait () pure virtual
Implemented in csl::SynchPthread.
Referenced by csl::NullIO::FeederFunction(), and csl::StdIO::FeederFunction().
virtual int csl::Synch::condSignal () pure virtual
Implemented in csl::SynchPthread.
Referenced by csl::NullIO::stop().
The documentation for this class was generated from the following files:
/Content/Code/CSL/CSL/Utilities/ThreadUtilities.h
/Content/Code/CSL/CSL/Utilities/ThreadUtilities.cpp