CSL: csl::BinauralPanner Class Reference
csl::BinauralPanner Class Reference
forward declaration
#include <Binaural.h>
Public Member Functions
BinauralPanner (unsigned blockSize=HRTF_BLOCK_SIZE)
~BinauralPanner ()
void nextBuffer (Buffer &outputBuffer) throw (CException)
work-horse method reads & transforms input, sums previous data, and takes the IFFT for each of multiple sources
void setSpeakerLayout (SpeakerLayout *aLayout)
Set the speaker layout to be used by this panner. The panner will request the default layout if not set.
unsigned numSources ()
virtual void addSource (SpatialSource &s)
number of active inputs.
virtual void removeSource (SpatialSource &s)
Remove a Sound Source.
virtual void update (void *arg)
Called when the speaker layout changes.
virtual void nextBuffer (Buffer &outputBuffer, unsigned outBufNum) throw (CException)
really compute the next buffer given an offset base channel; this is called by nextBuffer, possibly multiple times
unsigned frameRate ()
void setFrameRate (unsigned rate)
get/set the receiver's frame rate
virtual unsigned numChannels ()
void setNumChannels (unsigned ch)
get/set the receiver's number of outputs
BufferCopyPolicy copyPolicy ()
void setCopyPolicy (BufferCopyPolicy ch)
get/set the receiver's buffer copy policy
virtual bool isFixed ()
query whether I'm fixed (StaticVariable overrides this)
virtual bool isActive ()
query whether I'm currently active (Envelopes can go inactive)
void addOutput (UnitGenerator *ugen)
add to or return the UGen vector of outputs
void removeOutput (UnitGenerator *ugen)
UGenVector outputs ()
virtual unsigned numOutputs ()
bool checkFanOut (Buffer &outputBuffer) throw (CException)
check for fan-out and copy previous buffer; return true if fanning out
void handleFanOut (Buffer &outputBuffer) throw (CException)
virtual void setValue (sample theValue)
set/get the value (not allowed in the abstract, useful for static values)
virtual sample value ()
virtual void dump ()
pretty-print the receiver
virtual void trigger ()
void attachObserver (Observer *)
(possibly notify obersvers on my death)
void detachObserver (Observer *)
void changed (void *argument)
this is what I send to myself to notify my observers; It's not overridden in general. It results in the observers receiving update() calls < override evaluate to filter updates to the observer map
virtual int evaluate (void *argument)
Public Attributes
unsigned mNumBlocks
blocks per HRTF
unsigned mNumBlocksToSum
blocks to include in sum per HRTF
unsigned mFramesPerBlock
frames per block
float mPeriod
virtual destructor (don't notify or delete observers in this version)
int mKey
key selector (e.g., MIDI chan) I receive update() mesages from my model;
Protected Member Functions
void * cache ()
Returns an instance of its cache data per sound source.
virtual void speakerLayoutChanged ()
void zeroBuffer (Buffer &outputBuffer, unsigned outBufNum)
utility method to zero out an outputBuffer
Protected Attributes
FFT_Wrapper mInFFT
FFT Wrappers for in and out processing.
FFT_Wrapper mOutFFT
Buffer mInBuf
Buffer mTmpBuf
Buffer mOutBuf
temp buffers for input and FFT wrappers
SampleComplexVector mHOutL
SampleComplexVector mHOutR
buffers for the mixed HRTF & input data pre-IFFT
SampleBuffer mIFFTOutL
SampleBuffer mIFFTOutR
outputs of the IFFT
unsigned mBlockInd
block index
UGenVector mSources
SpatialSource... refers to its input UGen, but with the knowledge of its position within a space.
vector< void * > mCache
Vector of pointers to the prior I/O data.
SpeakerLayout * mSpeakerLayout
If null, it will use the default layout by calling SpeakerLayout::defaultSpeakerLayout();.
Buffer mTempBuffer
Buffer used to temporarily hold input source data.
unsigned mFrameRate
trigger ignored here
unsigned mNumChannels
my "expected" number of output channels
BufferCopyPolicy mCopyPolicy
the policy I use if asked for more or fewer channels
UGenVector mOutputs
the vector of my output UGens
unsigned mNumOutputs
the number of outputs
Buffer * mOutputCache
my past output ring buffer (only used in case of fan-out)
unsigned mSequence
the highest-seen buffer seq number
Detailed Description
forward declaration
BinauralPanner: place sources in 3D using block-wise convolution with an HRTF. The HRIRs (Head Related Impulse Responses) are loaded by the HRTFDatabase. The binaural panner uses these HRTFs and processes the incoming audio by frequency domain convolution in blocks of 512 samples.
Definition at line 49 of file Binaural.h.
Constructor & Destructor Documentation
BinauralPanner::BinauralPanner (unsigned blockSize = HRTF_BLOCK_SIZE)
Definition at line 23 of file Binaural.cpp.
References csl::Buffer::allocateBuffers(), csl::HRTFDatabase::Database(), csl::HRTFDatabase::hrtfLength(), csl::kIgnore, csl::kSpectra, mFramesPerBlock, mHOutL, mHOutR, mIFFTOutL, mIFFTOutR, mInBuf, mNumBlocks, mNumBlocksToSum, mTmpBuf, csl::Buffer::mType, csl::HRTFDatabase::numBlocks(), SAFE_MALLOC, csl::UnitGenerator::setCopyPolicy(), csl::UnitGenerator::setNumChannels(), SUM_DOWNS, and csl::HRTFDatabase::windowSize().
BinauralPanner::~BinauralPanner ()
Definition at line 56 of file Binaural.cpp.
References mHOutL, mHOutR, mIFFTOutL, mIFFTOutR, and SAFE_FREE.
Member Function Documentation
void BinauralPanner::nextBuffer (Buffer & outputBuffer) throw (CException) virtual
work-horse method reads & transforms input, sums previous data, and takes the IFFT for each of multiple sources
Implements csl::SpatialPanner.
Definition at line 73 of file Binaural.cpp.
References cmac, ComplexPtr, csl::HRTFDatabase::Database(), csl::HRTFDatabase::hrtfAt(), csl::HRTFDatabase::hrtfLength(), csl::UnitGenerator::isActive(), csl::kLogError, LEN_DOWNS, csl::logMsg(), csl::BinauralSourceCache::mHRTF, csl::HRTF::mHrtfL, csl::HRTF::mHrtfR, csl::BinauralSourceCache::mInSpect, csl::BinauralSourceCache::mPrevOutL, csl::BinauralSourceCache::mPrevOutR, csl::SpatialSource::nextBuffer(), csl::SpatialSource::position(), csl::SpatialSource::positionChanged(), and csl::HRTFDatabase::windowSize().
void * BinauralPanner::cache () protected virtual
Returns an instance of its cache data per sound source.
Reimplemented from csl::SpatialPanner.
Definition at line 65 of file Binaural.cpp.
void SpatialPanner::setSpeakerLayout (SpeakerLayout * aLayout) inherited
Set the speaker layout to be used by this panner. The panner will request the default layout if not set.
Definition at line 25 of file SpatialPanner.cpp.
References csl::Model::attachObserver(), csl::Model::detachObserver(), csl::SpatialPanner::mSpeakerLayout, and csl::SpatialPanner::speakerLayoutChanged().
Referenced by csl::SpatialPanner::SpatialPanner(), and csl::SpatialPanner::update().
unsigned csl::SpatialPanner::numSources () inline inherited
Definition at line 32 of file SpatialPanner.h.
References csl::SpatialPanner::mSources.
Referenced by csl::Spatializer::numSources().
void SpatialPanner::addSource (SpatialSource & s) virtual inherited
number of active inputs.
Add a souce to the list of inputs to be processed and create a cache object
Reimplemented in csl::AmbisonicPanner, csl::SimplePanner, and csl::SimplePanner.
Definition at line 41 of file SpatialPanner.cpp.
References csl::SpatialPanner::cache(), csl::SpatialPanner::mCache, and csl::SpatialPanner::mSources.
Referenced by csl::Spatializer::addSource(), main(), and csl::Spatializer::setPanningMode().
void SpatialPanner::removeSource (SpatialSource & s) virtual inherited
Remove a Sound Source.
Reimplemented in csl::AmbisonicPanner, csl::SimplePanner, and csl::SimplePanner.
Definition at line 56 of file SpatialPanner.cpp.
References csl::logMsg(), csl::SpatialPanner::mCache, and csl::SpatialPanner::mSources.
Referenced by csl::Spatializer::removeSource().
void SpatialPanner::update (void * arg) virtual inherited
Called when the speaker layout changes.
Called when the speaker layout changes, so panners update their data. This method is implemented only by the Panner class, and depending on the message sent, it calls the appropriate method implemented by subclasses. For example, when the speaker layout changes, the method calls "speakerLayoutChanged()", which should be implemented by subclasses interested to react to such change.
Implements csl::Observer.
Definition at line 83 of file SpatialPanner.cpp.
References csl::SpeakerLayout::defaultSpeakerLayout(), csl::SpatialPanner::mSpeakerLayout, csl::SpatialPanner::setSpeakerLayout(), and csl::SpatialPanner::speakerLayoutChanged().
virtual void csl::SpatialPanner::nextBuffer (Buffer & outputBuffer, unsigned outBufNum) throw (CException) inline virtual inherited
really compute the next buffer given an offset base channel; this is called by nextBuffer, possibly multiple times
Reimplemented from csl::UnitGenerator.
Reimplemented in csl::VBAP.
Definition at line 42 of file SpatialPanner.h.
virtual void csl::SpatialPanner::speakerLayoutChanged () inline protected virtual inherited
Reimplemented in csl::VBAP.
Definition at line 57 of file SpatialPanner.h.
Referenced by csl::SpatialPanner::setSpeakerLayout(), and csl::SpatialPanner::update().
unsigned csl::UnitGenerator::frameRate () inline inherited
Definition at line 249 of file CSL_Core.h.
References csl::UnitGenerator::mFrameRate.
Referenced by csl::CASoundFile::dump(), csl::Abst_SoundFile::dump(), and csl::SoundCue::dump().
void csl::UnitGenerator::setFrameRate (unsigned rate) inline inherited
get/set the receiver's frame rate
Definition at line 250 of file CSL_Core.h.
References csl::UnitGenerator::mFrameRate.
virtual unsigned csl::UnitGenerator::numChannels () inline virtual inherited
Reimplemented in csl::Splitter, and csl::Stereoverb.
Definition at line 252 of file CSL_Core.h.
References csl::UnitGenerator::mNumChannels.
Referenced by csl::AmbisonicMixer::addInput(), csl::BlockResizer::BlockResizer(), csl::Port::checkBuffer(), csl::Effect::Effect(), csl::AmbisonicRotator::initialize(), csl::AmbisonicDecoder::initialize(), csl::Mixer::nextBuffer(), csl::Convolver2::setIRFile(), csl::Convolver::setIRFile(), and csl::SpatialSource::SpatialSource().
void csl::UnitGenerator::setNumChannels (unsigned ch) inline inherited
get/set the receiver's number of outputs
Definition at line 253 of file CSL_Core.h.
References csl::UnitGenerator::mNumChannels.
Referenced by BinauralPanner(), csl::Spatializer::Spatializer(), csl::VBAP::speakerLayoutChanged(), and csl::VBAP::VBAP().
BufferCopyPolicy csl::UnitGenerator::copyPolicy () inline inherited
Definition at line 255 of file CSL_Core.h.
References csl::UnitGenerator::mCopyPolicy.
void csl::UnitGenerator::setCopyPolicy (BufferCopyPolicy ch) inline inherited
get/set the receiver's buffer copy policy
Definition at line 256 of file CSL_Core.h.
References csl::UnitGenerator::mCopyPolicy.
Referenced by csl::AmbisonicPanner::AmbisonicPanner(), BinauralPanner(), csl::AmbisonicUnitGenerator::initOrder(), csl::Noise::Noise(), csl::PinkNoise::PinkNoise(), csl::Spatializer::Spatializer(), and csl::VBAP::VBAP().
virtual bool csl::UnitGenerator::isFixed () inline virtual inherited
query whether I'm fixed (StaticVariable overrides this)
Reimplemented in csl::StaticVariable, and csl::BinaryOp.
Definition at line 271 of file CSL_Core.h.
virtual bool csl::UnitGenerator::isActive () inline virtual inherited
query whether I'm currently active (Envelopes can go inactive)
Reimplemented in csl::Joiner, csl::Effect, csl::RandEnvelope, csl::SoundCue, csl::Abst_SoundFile, csl::Stereoverb, csl::Envelope, csl::Instrument, csl::Mixer, and csl::KarplusString.
Definition at line 273 of file CSL_Core.h.
Referenced by csl::Instrument::isActive(), csl::Port::isActive(), csl::Mixer::nextBuffer(), nextBuffer(), csl::AmbisonicMixer::nextBuffer(), and csl::VBAP::nextBuffer().
void UnitGenerator::addOutput (UnitGenerator * ugen) inherited
add to or return the UGen vector of outputs
Definition at line 670 of file CSL_Core.cpp.
References csl::Buffer::allocateBuffers(), csl::CGestalt::blockSize(), csl::UnitGenerator::mNumOutputs, csl::UnitGenerator::mOutputCache, and csl::UnitGenerator::mOutputs.
Referenced by csl::Mixer::addInput(), csl::Controllable::addInput(), csl::AmbisonicRotator::initialize(), csl::AmbisonicDecoder::initialize(), csl::AmbisonicEncoder::setInput(), and csl::IO::setRoot().
void UnitGenerator::removeOutput (UnitGenerator * ugen) inherited
Definition at line 680 of file CSL_Core.cpp.
References csl::UnitGenerator::mNumOutputs, and csl::UnitGenerator::mOutputs.
Referenced by csl::IO::clearRoot(), csl::AmbisonicEncoder::setInput(), csl::AmbisonicDecoder::~AmbisonicDecoder(), and csl::AmbisonicRotator::~AmbisonicRotator().
UGenVector csl::UnitGenerator::outputs () inline inherited
Definition at line 277 of file CSL_Core.h.
References csl::UnitGenerator::mOutputs.
virtual unsigned csl::UnitGenerator::numOutputs () inline virtual inherited
Definition at line 278 of file CSL_Core.h.
References csl::UnitGenerator::mNumOutputs.
bool UnitGenerator::checkFanOut (Buffer & outputBuffer) throw (CException) inherited
check for fan-out and copy previous buffer; return true if fanning out
Definition at line 699 of file CSL_Core.cpp.
void UnitGenerator::handleFanOut (Buffer & outputBuffer) throw (CException) inherited
Definition at line 713 of file CSL_Core.cpp.
References csl_max.
virtual void csl::UnitGenerator::setValue (sample theValue) inline virtual inherited
set/get the value (not allowed in the abstract, useful for static values)
Reimplemented in csl::DynamicVariable, and csl::StaticVariable.
Definition at line 284 of file CSL_Core.h.
virtual sample csl::UnitGenerator::value () inline virtual inherited
Reimplemented in csl::StaticVariable.
Definition at line 285 of file CSL_Core.h.
void UnitGenerator::dump (void) virtual inherited
pretty-print the receiver
Reimplemented in csl::RandEnvelope, csl::SumOfSines, csl::SoundCue, csl::Abst_SoundFile, csl::Filter, csl::Envelope, csl::BufferStream, csl::VBAP, csl::SineAsScaled, csl::LineSegment, csl::SpatialSource, csl::SineAsPhased, csl::Mixer, csl::Window, csl::KarplusString, csl::Oscillator, csl::AmbisonicPanner, csl::BinaryOp, csl::Lorenz, csl::Clipper, csl::Noise, and csl::CASoundFile.
Definition at line 693 of file CSL_Core.cpp.
References csl::logMsg(), and csl::UnitGenerator::mOutputs.
Referenced by csl::Noise::dump(), csl::Clipper::dump(), csl::Filter::dump(), csl::Port::dump(), dumpTest(), and testSimpleSines().
virtual void csl::UnitGenerator::trigger (void) inline virtual inherited
Reimplemented in csl::Joiner, csl::Effect, csl::RandEnvelope, csl::SoundCue, csl::Abst_SoundFile, csl::Envelope, csl::LineSegment, and csl::KarplusString.
Definition at line 288 of file CSL_Core.h.
Referenced by csl::Instrument::play(), csl::Instrument::release(), and csl::Port::trigger().
void UnitGenerator::zeroBuffer (Buffer & outputBuffer, unsigned outBufNum) protected inherited
utility method to zero out an outputBuffer
Definition at line 663 of file CSL_Core.cpp.
References csl::Buffer::buffer(), and csl::Buffer::mMonoBufferByteSize.
void Model::attachObserver (Observer * o) inherited
(possibly notify obersvers on my death)
register/remove observers
Definition at line 502 of file CGestalt.cpp.
References csl::logMsg(), csl::Observer::mKey, and csl::Observer::mPeriod.
Referenced by csl::SpatialPanner::setSpeakerLayout().
void Model::detachObserver (Observer * o) inherited
Definition at line 518 of file CGestalt.cpp.
References csl::logMsg().
Referenced by csl::SpatialPanner::setSpeakerLayout(), and csl::SpatialPanner::~SpatialPanner().
void Model::changed (void * argument) inherited
this is what I send to myself to notify my observers; It's not overridden in general. It results in the observers receiving update() calls < override evaluate to filter updates to the observer map
Definition at line 540 of file CGestalt.cpp.
References csl::logMsg().
Referenced by csl::SpeakerLayout::addSpeaker(), csl::MIDIIn::handleIncomingMidiMessage(), and csl::SpeakerLayout::setDefaultSpeakerLayout().
virtual int csl::Model::evaluate (void * argument) inline virtual inherited
Reimplemented in csl::MIDIIn.
Definition at line 270 of file CGestalt.h.
Member Data Documentation
unsigned csl::BinauralPanner::mNumBlocks
blocks per HRTF
Definition at line 59 of file Binaural.h.
Referenced by BinauralPanner(), and csl::BinauralSourceCache::BinauralSourceCache().
unsigned csl::BinauralPanner::mNumBlocksToSum
blocks to include in sum per HRTF
Definition at line 60 of file Binaural.h.
Referenced by BinauralPanner().
unsigned csl::BinauralPanner::mFramesPerBlock
frames per block
Definition at line 61 of file Binaural.h.
Referenced by BinauralPanner(), and csl::BinauralSourceCache::BinauralSourceCache().
FFT_Wrapper csl::BinauralPanner::mInFFT protected
FFT Wrappers for in and out processing.
Definition at line 64 of file Binaural.h.
FFT_Wrapper csl::BinauralPanner::mOutFFT protected
Definition at line 65 of file Binaural.h.
Buffer csl::BinauralPanner::mInBuf protected
Definition at line 67 of file Binaural.h.
Referenced by BinauralPanner().
Buffer csl::BinauralPanner::mTmpBuf protected
Definition at line 67 of file Binaural.h.
Referenced by BinauralPanner().
Buffer csl::BinauralPanner::mOutBuf protected
temp buffers for input and FFT wrappers
Definition at line 67 of file Binaural.h.
SampleComplexVector csl::BinauralPanner::mHOutL protected
Definition at line 69 of file Binaural.h.
Referenced by BinauralPanner(), and ~BinauralPanner().
SampleComplexVector csl::BinauralPanner::mHOutR protected
buffers for the mixed HRTF & input data pre-IFFT
Definition at line 69 of file Binaural.h.
Referenced by BinauralPanner(), and ~BinauralPanner().
SampleBuffer csl::BinauralPanner::mIFFTOutL protected
Definition at line 70 of file Binaural.h.
Referenced by BinauralPanner(), and ~BinauralPanner().
SampleBuffer csl::BinauralPanner::mIFFTOutR protected
outputs of the IFFT
Definition at line 70 of file Binaural.h.
Referenced by BinauralPanner(), and ~BinauralPanner().
unsigned csl::BinauralPanner::mBlockInd protected
block index
Definition at line 72 of file Binaural.h.
UGenVector csl::SpatialPanner::mSources protected inherited
SpatialSource... refers to its input UGen, but with the knowledge of its position within a space.
Vector of pointers to the inputs
Definition at line 49 of file SpatialPanner.h.
Referenced by csl::SimplePanner::addSource(), csl::SpatialPanner::addSource(), csl::SpatialPanner::numSources(), csl::SimplePanner::removeSource(), and csl::SpatialPanner::removeSource().
vector<void *> csl::SpatialPanner::mCache protected inherited
Vector of pointers to the prior I/O data.
Definition at line 50 of file SpatialPanner.h.
Referenced by csl::SpatialPanner::addSource(), and csl::SpatialPanner::removeSource().
SpeakerLayout* csl::SpatialPanner::mSpeakerLayout protected inherited
If null, it will use the default layout by calling SpeakerLayout::defaultSpeakerLayout();.
Definition at line 52 of file SpatialPanner.h.
Referenced by csl::SpatialPanner::setSpeakerLayout(), csl::VBAP::speakerLayoutChanged(), csl::SpatialPanner::update(), csl::VBAP::VBAP(), csl::SpatialPanner::~SpatialPanner(), csl::StereoPanner::~StereoPanner(), and csl::SurroundPanner::~SurroundPanner().
Buffer csl::SpatialPanner::mTempBuffer protected inherited
Buffer used to temporarily hold input source data.
Definition at line 54 of file SpatialPanner.h.
Referenced by csl::SpatialPanner::SpatialPanner(), and csl::SpatialPanner::~SpatialPanner().
unsigned csl::UnitGenerator::mFrameRate protected inherited
trigger ignored here
the frame rate – initialized to be the default by the constructor
Definition at line 288 of file CSL_Core.h.
Referenced by csl::Abst_SoundFile::convertRate(), csl::Lorenz::dump(), csl::Abst_SoundFile::durationInSecs(), csl::UnitGenerator::frameRate(), csl::Filter::init(), csl::CASoundFile::initFromSndfile(), csl::JSoundFile::initFromSndfile(), csl::LSoundFile::initFromSndfile(), csl::RandEnvelope::nextSegment(), csl::SquareBL::nextWaveInto(), csl::SumOfSines::nextWaveInto(), csl::DelayLine::setDelayTime(), csl::UnitGenerator::setFrameRate(), csl::Abst_SoundFile::setStartSec(), csl::Abst_SoundFile::setStopSec(), csl::Butter::setupCoeffs(), csl::Formant::setupCoeffs(), csl::Notch::setupCoeffs(), and csl::Moog::setupCoeffs().
unsigned csl::UnitGenerator::mNumChannels protected inherited
my "expected" number of output channels
Definition at line 292 of file CSL_Core.h.
Referenced by csl::AmbisonicMixer::addInput(), csl::Mixer::allocateOpBuffer(), csl::AmbisonicDecoder::asProjection(), csl::AmbisonicDecoder::asPseudoInverse(), csl::BlockResizer::BlockResizer(), csl::Abst_SoundFile::channels(), csl::Abst_SoundFile::checkBuffer(), csl::FMInstrument::FMInstrument(), csl::GrainPlayer::GrainPlayer(), csl::AdditiveInstrument::init(), csl::JSoundFile::initFromSndfile(), csl::LSoundFile::initFromSndfile(), csl::AmbisonicMixer::initialize(), csl::SndFileInstrument::initialize(), csl::AmbisonicRotator::initialize(), csl::AmbisonicEncoder::initialize(), csl::AmbisonicDecoder::initialize(), csl::AmbisonicUnitGenerator::initOrder(), csl::RemoteStream::initPacket(), csl::Joiner::isActive(), csl::Joiner::Joiner(), csl::AmbisonicDecoder::makeInPhase(), csl::AmbisonicDecoder::makeMaxRE(), csl::Abst_SoundFile::mergeToMono(), csl::Mixer::Mixer(), csl::UnitGenerator::numChannels(), csl::Panner::Panner(), csl::CASoundFile::readBufferFromFile(), csl::JSoundFile::readBufferFromFile(), csl::LSoundFile::readBufferFromFile(), csl::RemoteStream::RemoteStream(), csl::UnitGenerator::setNumChannels(), csl::WavetableOscillator::setWaveform(), csl::Joiner::trigger(), and csl::AmbisonicRotator::~AmbisonicRotator().
BufferCopyPolicy csl::UnitGenerator::mCopyPolicy protected inherited
the policy I use if asked for more or fewer channels
Definition at line 293 of file CSL_Core.h.
Referenced by csl::UnitGenerator::copyPolicy(), and csl::UnitGenerator::setCopyPolicy().
UGenVector csl::UnitGenerator::mOutputs protected inherited
the vector of my output UGens
Definition at line 294 of file CSL_Core.h.
Referenced by csl::UnitGenerator::addOutput(), csl::UnitGenerator::dump(), csl::UnitGenerator::outputs(), and csl::UnitGenerator::removeOutput().
unsigned csl::UnitGenerator::mNumOutputs protected inherited
the number of outputs
Definition at line 295 of file CSL_Core.h.
Referenced by csl::UnitGenerator::addOutput(), csl::UnitGenerator::numOutputs(), and csl::UnitGenerator::removeOutput().
Buffer* csl::UnitGenerator::mOutputCache protected inherited
my past output ring buffer (only used in case of fan-out)
Definition at line 296 of file CSL_Core.h.
Referenced by csl::UnitGenerator::addOutput().
unsigned csl::UnitGenerator::mSequence protected inherited
the highest-seen buffer seq number
Definition at line 297 of file CSL_Core.h.
float csl::Observer::mPeriod inherited
virtual destructor (don't notify or delete observers in this version)
max update rate
Definition at line 299 of file CGestalt.h.
Referenced by csl::Model::attachObserver(), and csl::Observer::Observer().
int csl::Observer::mKey inherited
key selector (e.g., MIDI chan) I receive update() mesages from my model;
Definition at line 302 of file CGestalt.h.
Referenced by csl::Model::attachObserver(), and csl::Observer::Observer().
The documentation for this class was generated from the following files:
/Content/Code/CSL/CSL/Spatializers/Binaural/Binaural.h
/Content/Code/CSL/CSL/Spatializers/Binaural/Binaural.cpp