# C++ Windowed Executable Makefile autogenerated by premake
# Don't edit this file! Instead edit `premake.lua` then rerun `make`

ifndef CONFIG
  CONFIG=Debug
endif

# if multiple archs are defined turn off automated dependency generation
DEPFLAGS := $(if $(word 2, $(TARGET_ARCH)), , -MMD)

ifeq ($(CONFIG),Debug)
  BINDIR := build
  LIBDIR := build
  OBJDIR := build/intermediate/Debug
  OUTDIR := build
  CPPFLAGS := $(DEPFLAGS) -D "LINUX=1" -D "USE_JUCE" -D "USE_FFTREAL" -D "USE_HRTF" -D "USE_JSND" -I "../CSL/Includes" -I "../CSL/Spatializers/Binaural" -I "../CSL/Spatializers/Ambisonic" -I "../JUCE" -I "/home/stp/juce/"
  CFLAGS += $(CPPFLAGS) $(TARGET_ARCH) -g -ggdb -O0 -w
  CXXFLAGS += $(CFLAGS)
  LDFLAGS += -L$(BINDIR) -L$(LIBDIR) -mwindows -L"/usr/X11R6/lib/" -L"/usr/local/lib/" -L"/home/stp/juce/bin/" -lfreetype -lpthread -lX11 -lGL -lGLU -lXinerama -lasound -ljuce_debug
  LDDEPS :=
  RESFLAGS := -D "LINUX=1" -D "USE_JUCE" -D "USE_FFTREAL" -D "USE_HRTF" -D "USE_JSND" -I "../CSL/Includes" -I "../CSL/Spatializers/Binaural" -I "../CSL/Spatializers/Ambisonic" -I "../JUCE" -I "/home/stp/juce/"
  TARGET := CSL_JUCE
  MACAPP := CSL_JUCE.app/Contents
 BLDCMD = $(CXX) -o $(OUTDIR)/$(MACAPP)/MacOS/$(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(TARGET_ARCH)
endif

ifeq ($(CONFIG),Release)
  BINDIR := build
  LIBDIR := build
  OBJDIR := build/intermediate/Release
  OUTDIR := build
  CPPFLAGS := $(DEPFLAGS) -D "LINUX=1" -D "USE_JUCE" -D "USE_FFTREAL" -D "USE_HRTF" -D "USE_JSND" -I "../CSL/Includes" -I "../CSL/Spatializers/Binaural" -I "../CSL/Spatializers/Ambisonic" -I "../JUCE" -I "/home/stp/juce/"
  CFLAGS += $(CPPFLAGS) $(TARGET_ARCH) -O2 -O2 -w
  CXXFLAGS += $(CFLAGS)
  LDFLAGS += -L$(BINDIR) -L$(LIBDIR) -mwindows -Wl,-x -L"/usr/X11R6/lib/" -L"/usr/local/lib/" -L"/home/stp/juce/bin/" -lfreetype -lpthread -lX11 -lGL -lGLU -lXinerama -lasound -ljuce_debug
  LDDEPS :=
  RESFLAGS := -D "LINUX=1" -D "USE_JUCE" -D "USE_FFTREAL" -D "USE_HRTF" -D "USE_JSND" -I "../CSL/Includes" -I "../CSL/Spatializers/Binaural" -I "../CSL/Spatializers/Ambisonic" -I "../JUCE" -I "/home/stp/juce/"
  TARGET := CSL_JUCE
  MACAPP := CSL_JUCE.app/Contents
 BLDCMD = $(CXX) -o $(OUTDIR)/$(MACAPP)/MacOS/$(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(TARGET_ARCH)
endif

OBJECTS := \
	$(OBJDIR)/CGestalt.o \
	$(OBJDIR)/CSL_Core.o \
	$(OBJDIR)/BlockResizer.o \
	$(OBJDIR)/CPoint.o \
	$(OBJDIR)/FFT_Wrapper.o \
	$(OBJDIR)/FFTReal.o \
	$(OBJDIR)/RingBuffer.o \
	$(OBJDIR)/ThreadUtilities.o \
	$(OBJDIR)/Variable.o \
	$(OBJDIR)/Envelope.o \
	$(OBJDIR)/Granulator.o \
	$(OBJDIR)/KarplusString.o \
	$(OBJDIR)/Lorenz.o \
	$(OBJDIR)/Noise.o \
	$(OBJDIR)/Oscillator.o \
	$(OBJDIR)/OscillatorBL.o \
	$(OBJDIR)/SHARC.o \
	$(OBJDIR)/SimpleSines.o \
	$(OBJDIR)/Spectral.o \
	$(OBJDIR)/Window.o \
	$(OBJDIR)/BinaryOp.o \
	$(OBJDIR)/Clipper.o \
	$(OBJDIR)/Filters.o \
	$(OBJDIR)/FIR.o \
	$(OBJDIR)/Freeverb.o \
	$(OBJDIR)/InOut.o \
	$(OBJDIR)/Mixer.o \
	$(OBJDIR)/AdditiveInstrument.o \
	$(OBJDIR)/BasicFMInstrument.o \
	$(OBJDIR)/Instrument.o \
	$(OBJDIR)/SndFileInstrument.o \
	$(OBJDIR)/DistanceSimulator.o \
	$(OBJDIR)/SpatialAudio.o \
	$(OBJDIR)/SpatialPanner.o \
	$(OBJDIR)/SpatialSource.o \
	$(OBJDIR)/SpeakerLayout.o \
	$(OBJDIR)/Binaural.o \
	$(OBJDIR)/BinauralDB.o \
	$(OBJDIR)/Ambisonic.o \
	$(OBJDIR)/AmbisonicPanner.o \
	$(OBJDIR)/AmbisonicUtilities.o \
	$(OBJDIR)/SoundFile.o \
	$(OBJDIR)/SoundFileJ.o \
	$(OBJDIR)/MIDIIOJ.o \
	$(OBJDIR)/Test_Audio.o \
	$(OBJDIR)/Test_Control.o \
	$(OBJDIR)/Test_Effects.o \
	$(OBJDIR)/Test_Envelopes.o \
	$(OBJDIR)/Test_Oscillators.o \
	$(OBJDIR)/Test_Panners.o \
	$(OBJDIR)/Test_Sources.o \
	$(OBJDIR)/Test_Support.o \
	$(OBJDIR)/CSL_TestComponent.o \
	$(OBJDIR)/JCSL_Widgets.o \
	$(OBJDIR)/Main.o \

MKDIR_TYPE := msdos
CMD := $(subst \,\\,$(ComSpec)$(COMSPEC))
ifeq (,$(CMD))
  MKDIR_TYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  MKDIR_TYPE := posix
endif
ifeq ($(MKDIR_TYPE),posix)
  CMD_MKBINDIR := mkdir -p $(BINDIR)
  CMD_MKLIBDIR := mkdir -p $(LIBDIR)
  CMD_MKOUTDIR := mkdir -p $(OUTDIR)
  CMD_MKOBJDIR := mkdir -p $(OBJDIR)
else
  CMD_MKBINDIR := $(CMD) /c if not exist $(subst /,\\,$(BINDIR)) mkdir $(subst /,\\,$(BINDIR))
  CMD_MKLIBDIR := $(CMD) /c if not exist $(subst /,\\,$(LIBDIR)) mkdir $(subst /,\\,$(LIBDIR))
  CMD_MKOUTDIR := $(CMD) /c if not exist $(subst /,\\,$(OUTDIR)) mkdir $(subst /,\\,$(OUTDIR))
  CMD_MKOBJDIR := $(CMD) /c if not exist $(subst /,\\,$(OBJDIR)) mkdir $(subst /,\\,$(OBJDIR))
endif

.PHONY: clean

all: $(OUTDIR)/$(MACAPP)/PkgInfo $(OUTDIR)/$(MACAPP)/Info.plist $(OUTDIR)/$(MACAPP)/MacOS/$(TARGET)

$(OUTDIR)/$(MACAPP)/MacOS/$(TARGET): $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking CSL_JUCE
	-@$(CMD_MKBINDIR)
	-@$(CMD_MKLIBDIR)
	-@$(CMD_MKOUTDIR)
	-@if [ ! -d $(OUTDIR)/$(MACAPP)/MacOS ]; then mkdir -p $(OUTDIR)/$(MACAPP)/MacOS; fi
	@$(BLDCMD)

$(OUTDIR)/$(MACAPP)/PkgInfo:

$(OUTDIR)/$(MACAPP)/Info.plist:

clean:
	@echo Cleaning CSL_JUCE
ifeq ($(MKDIR_TYPE),posix)
	-@rm -rf $(OUTDIR)/$(TARGET).app
	-@rm -rf $(OBJDIR)
else
	-@if exist $(subst /,\,$(OUTDIR)/$(TARGET)) del /q $(subst /,\,$(OUTDIR)/$(TARGET))
	-@if exist $(subst /,\,$(OBJDIR)) del /q $(subst /,\,$(OBJDIR))
	-@if exist $(subst /,\,$(OBJDIR)) rmdir /s /q $(subst /,\,$(OBJDIR))
endif

$(OBJDIR)/CGestalt.o: ../CSL/Kernel/CGestalt.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/CSL_Core.o: ../CSL/Kernel/CSL_Core.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/BlockResizer.o: ../CSL/Utilities/BlockResizer.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/CPoint.o: ../CSL/Utilities/CPoint.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/FFT_Wrapper.o: ../CSL/Utilities/FFT_Wrapper.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/FFTReal.o: ../CSL/Utilities/FFTReal.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/RingBuffer.o: ../CSL/Utilities/RingBuffer.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/ThreadUtilities.o: ../CSL/Utilities/ThreadUtilities.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/Variable.o: ../CSL/Utilities/Variable.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/Envelope.o: ../CSL/Sources/Envelope.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/Granulator.o: ../CSL/Sources/Granulator.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/KarplusString.o: ../CSL/Sources/KarplusString.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/Lorenz.o: ../CSL/Sources/Lorenz.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/Noise.o: ../CSL/Sources/Noise.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/Oscillator.o: ../CSL/Sources/Oscillator.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/OscillatorBL.o: ../CSL/Sources/OscillatorBL.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/SHARC.o: ../CSL/Sources/SHARC.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/SimpleSines.o: ../CSL/Sources/SimpleSines.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/Spectral.o: ../CSL/Sources/Spectral.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/Window.o: ../CSL/Sources/Window.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/BinaryOp.o: ../CSL/Processors/BinaryOp.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/Clipper.o: ../CSL/Processors/Clipper.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/Filters.o: ../CSL/Processors/Filters.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/FIR.o: ../CSL/Processors/FIR.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/Freeverb.o: ../CSL/Processors/Freeverb.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/InOut.o: ../CSL/Processors/InOut.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/Mixer.o: ../CSL/Processors/Mixer.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/AdditiveInstrument.o: ../CSL/Instruments/AdditiveInstrument.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/BasicFMInstrument.o: ../CSL/Instruments/BasicFMInstrument.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/Instrument.o: ../CSL/Instruments/Instrument.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/SndFileInstrument.o: ../CSL/Instruments/SndFileInstrument.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/DistanceSimulator.o: ../CSL/Spatializers/DistanceSimulator.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/SpatialAudio.o: ../CSL/Spatializers/SpatialAudio.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/SpatialPanner.o: ../CSL/Spatializers/SpatialPanner.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/SpatialSource.o: ../CSL/Spatializers/SpatialSource.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/SpeakerLayout.o: ../CSL/Spatializers/SpeakerLayout.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/Binaural.o: ../CSL/Spatializers/Binaural/Binaural.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/BinauralDB.o: ../CSL/Spatializers/Binaural/BinauralDB.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/Ambisonic.o: ../CSL/Spatializers/Ambisonic/Ambisonic.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/AmbisonicPanner.o: ../CSL/Spatializers/Ambisonic/AmbisonicPanner.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/AmbisonicUtilities.o: ../CSL/Spatializers/Ambisonic/AmbisonicUtilities.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/SoundFile.o: ../CSL/IO/SoundFile.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/SoundFileJ.o: ../CSL/IO/SoundFileJ.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/MIDIIOJ.o: ../CSL/IO/MIDIIOJ.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/Test_Audio.o: ../CSL/Tests/Test_Audio.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/Test_Control.o: ../CSL/Tests/Test_Control.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/Test_Effects.o: ../CSL/Tests/Test_Effects.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/Test_Envelopes.o: ../CSL/Tests/Test_Envelopes.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/Test_Oscillators.o: ../CSL/Tests/Test_Oscillators.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/Test_Panners.o: ../CSL/Tests/Test_Panners.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/Test_Sources.o: ../CSL/Tests/Test_Sources.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/Test_Support.o: ../CSL/Tests/Test_Support.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/CSL_TestComponent.o: ../JUCE/CSL_TestComponent.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/JCSL_Widgets.o: ../JUCE/JCSL_Widgets.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

$(OBJDIR)/Main.o: ../JUCE/Main.cpp
	-@$(CMD_MKOBJDIR)
	@echo $(notdir $<)
	@$(CXX) $(CXXFLAGS) -o "$@" -c "$<"

-include $(OBJECTS:%.o=%.d)

